Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-09, with the labels that each got.

#520 EICNET-477: Add document language field to document media type
  config/sync/core.entity_form_display.media.eic_document.default.yml
  config/sync/core.entity_view_display.media.eic_document.default.yml
  config/sync/core.entity_view_display.media.eic_document.download.yml
  config/sync/core.entity_view_display.media.eic_document.media_library.yml
  config/sync/core.entity_view_display.media.eic_document.oe_theme_main_content.yml
  config/sync/field.field.media.eic_document.field_language.yml
  config/sync/field.storage.media.field_language.yml
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: backend, frontend

#556 [EICNET-1236]fix: Remove first spaces in domain mails field
  lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedEmailDomains.php
Labels: bug, backend

#518 EICNET-1225: Provide file download counter, node page views and entity flags (likes)
  config/sync/system.file.yml
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_content/src/Hooks/EntityOperations.php
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_media/modules/eic_media_statistics/eic_media_statistics.info.yml
  lib/modules/eic_media/modules/eic_media_statistics/eic_media_statistics.module
  lib/modules/eic_media/modules/eic_media_statistics/eic_media_statistics.services.yml
  lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Event/DownloadCountUpdate.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/eic_statistics.services.yml
  lib/modules/eic_statistics/src/Event/PageViewCountUpdate.php
  lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
Labels: backend, frontend

#563 Fix node document preprocess
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: bug, backend

#566 EICNET-1352: Group overview - Admins don't see all groups
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
Labels: backend

#565 EICNET-1288: Group header flags were not shown in the group header ex…
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#567 EICNET-XXXX: Fix issue when field_language doesn't exist.
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: bug, backend, frontend

#564 EICNET-1294: Import the job titles from SMED.
  config/sync/migrate_plus.migration.smed_job_titles.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_job_titles.yml
Labels: backend

#541 EICNET-1304: Show comments count in news and stories
  lib/modules/eic_comments/eic_comments.module
  lib/modules/eic_comments/src/Hooks/EntityOperations.php
Labels: backend

#545 [EICNET-1144]fix: Add fallback for comment type and fix date format
  config/sync/core.date_format.eu_format.yml
  config/sync/core.date_format.eu_short_date.yml
  lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
  lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
Labels: bug, backend, frontend

#554 EICNET-1345: SA/SCM should be able to edit all group content of any group
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
Labels: backend

#557 [EICNET-1100]fix: Add facets: language & document type for library overview
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.groups_overview.yml
  config/sync/context.context.members_overview.yml
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/core.entity_view_display.node.document.default.yml
  config/sync/core.entity_view_display.node.document.teaser.yml
  config/sync/core.entity_view_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.gallery.full.yml
  config/sync/core.entity_view_display.node.gallery.teaser.yml
  config/sync/core.entity_view_display.node.video.default.yml
  config/sync/field.field.node.document.field_document_type.yml
  config/sync/field.field.node.document.field_vocab_geo.yml
  config/sync/field.field.node.gallery.field_document_type.yml
  config/sync/field.field.node.video.field_document_type.yml
  config/sync/field.field.node.video.field_vocab_geo.yml
  config/sync/field.storage.node.field_document_type.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
Labels: backend

#559 [EICNET-1276]fix: Do not multiply rows by current page
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: bug, backend

#570 EICNET-1332: Define weight of every menu item in the group menu
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupFiles.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupMembers.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupWiki.php
Labels: backend

#574 EICNET-1359: Error when changing visibility of the group
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
Labels: bug, backend

#569 EICNET-1038: As a SCM I can view, edit and post comments
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#572 EICNET-1237: Wiki - Link Add wiki page is shown on moderated group
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/themes/eic_community/templates/content/node--book--full.html.twig
Labels: bug, backend

#558 [EICNET-1356]fix: Avoid adding array into array when value currently exists for a document
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: bug, backend

#578 [EICNET-1083]fix: Do not show the "remove" button on activity stream if user is not group owner
  lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/ActivityStream/DeleteActivityStream.js
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
Labels: bug, backend, frontend, react

#575 EICNET-1365: Group description > leads to about page
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#583 [EICNET-1251]fix: Get correct user id from group content membership
  lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: bug, backend

#581 EICNET-1366: Allow video and gallery for recommend, like and bookmark flags
  config/sync/flag.flag.bookmark_content.yml
  config/sync/flag.flag.like_content.yml
  config/sync/flag.flag.recommend.yml
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
Labels: backend

#580 EICNET-1368: Fix the display of topics for videos.
  config/sync/core.entity_form_display.node.book.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_view_display.message.log_group_state_change.pre_render.yml
  config/sync/core.entity_view_display.node.video.default.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/filter.format.filtered_html.yml
Labels: frontend

#579 EICNET-1384: Update modules and core to their latest version.
  composer.json
  composer.lock
Labels: backend

#588 [EICNET] feat: Introduce static code analysis
  .gitlab-ci.yml
  composer.json
  composer.lock
  phpstan.neon
Labels: enhancement

#589 [EICNET]feat: Decode special characters into global search
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: react

#586 [EICNET-1184]feat: Add also statistics for likes + fix icon time
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/Footer.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
Labels: frontend, react

#585 [EICNET-843]fix: contextualize global search to group with redirect
  lib/modules/eic_groups/src/Form/SearchMenuGroupForm.php
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Search/Sources/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
Labels: bug, backend

#584 [EICNET-1101]feat: Add total downloaded document into solr and react
  config/sync/context.context.search.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: backend, frontend, react

#577 [EICNET-770]feat: Implement discussion overview with highlight, and show latest comment
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsSearchApiReindex.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Discussion/Comment.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: enhancement, backend, frontend, react

#576 EICNET-1369: Adapt comment section on video detail page (group library)
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/core.entity_view_display.node.video.default.yml
  config/sync/field.field.node.video.field_comments.yml
  config/sync/field.field.node.video.field_related_contributors.yml
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_content/modules/eic_content_discussion/eic_content_discussion.module
  lib/modules/eic_content/src/Hooks/EntityOperationsContributor.php
Labels: backend

#568 EICNET-1354: Generate the statistics for the stories / news in the backend
  lib/modules/eic_block_types/eic_block_types.module
  lib/modules/eic_block_types/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
  lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
Labels: backend

#573 EICNET-1373: Change "invite member" default settings in group creation form based on joining method
  lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
Labels: backend

#571 EICNET-962: As a GO I want to choose a URL alias for my group
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/language.content_settings.redirect.redirect.yml
  config/sync/redirect.settings.yml
  config/sync/system.action.redirect_delete_action.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/views.view.redirect.yml
Labels: backend

#548 EICNET-1336: File download counter refactoring
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/entity_usage.settings.yml
  config/sync/field.storage.media.oe_media_image.yml
  config/sync/media.settings.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  lib/modules/eic_media/modules/eic_media_statistics/eic_media_statistics.module
  lib/modules/eic_media/modules/eic_media_statistics/eic_media_statistics.services.yml
  lib/modules/eic_media/modules/eic_media_statistics/src/Access/MediaFileDownloadAccessCheck.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
  lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
  lib/modules/eic_media/modules/eic_media_statistics/src/EventSubscriber/MediaDownloadRouteSubscriber.php
Labels: backend

#582 EICNET-1367: Add social share block to Video CT.
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/templates/content/node--video--full.html.twig
Labels: frontend

#551 EICNET-1283: As a GM I can edit every wiki page from my groups
  config/sync/core.entity_form_display.node.book.default.yml
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.book.default.yml
  config/sync/core.entity_view_display.node.book.teaser.yml
  config/sync/core.entity_view_display.node.discussion.default.yml
  config/sync/core.entity_view_display.node.discussion.teaser.yml
  config/sync/core.entity_view_display.node.document.default.yml
  config/sync/core.entity_view_display.node.document.teaser.yml
  config/sync/core.entity_view_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.gallery.full.yml
  config/sync/core.entity_view_display.node.gallery.teaser.yml
  config/sync/core.entity_view_display.node.news.default.yml
  config/sync/core.entity_view_display.node.news.teaser.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/core.entity_view_display.node.page.full.yml
  config/sync/core.entity_view_display.node.page.teaser.yml
  config/sync/core.entity_view_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.teaser.yml
  config/sync/core.entity_view_display.node.video.default.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/group.role.group-member.yml
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
  lib/modules/eic_groups/src/Commands/CreateFieldEditAccess.php
  lib/modules/eic_groups/src/Constants/NodeProperty.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
Labels: backend

#552 Feature/EICNET-1018: Sort handled requests by closed_date (desc)
  config/sync/views.view.closed_requests.yml
Labels: backend

#587 [EICNET-1385] feat: Add an apache/tika container
  composer.json
  composer.lock
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  config/sync/search_api_attachments.admin_config.yml
  docker-compose.yml
Labels: enhancement

#598 EICNET-1402: Show correct breadcrumb when viewing CTypes Gallery and Document
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_overviews/eic_overviews.routing.yml
  lib/modules/eic_overviews/src/GroupOverviewPages.php
Labels: backend

#599 EICNET-1267-1268: As a AU/GM, I can download videos from the content of a News/Story detailed page
  lib/modules/eic_media/eic_media.module
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/templates/content/node--story--full.html.twig
Labels: backend, frontend

#600 EICNET-391: As a GO/GA, I can manage videos in the content of a Discussion detailed page
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_view_display.node.discussion.default.yml
  config/sync/core.entity_view_display.node.discussion.teaser.yml
  config/sync/field.field.node.discussion.field_video.yml
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
  lib/themes/eic_community/templates/content/node--discussion--full.html.twig
Labels: enhancement, backend, frontend

#597 [EICNET-1390] feat: Deploy jobs for develop & QA
  .gitlab-ci.yml
Labels: enhancement

#592 EICNET-1371: Fix group file statistics for group content Gallery
  lib/modules/eic_statistics/modules/eic_group_statistics/drush.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#606 EICNET-1369: Adapt comment section on video detail page (group library) Part 2
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
Labels: backend, frontend

#601 [EICNET-1388] Data fixtures
  Makefile
  composer.json
  composer.lock
  config/sync/config_split.config_split.development.yml
  lib/modules/eic_default_content/content/block_content/34a810c9-d608-4979-ac40-00657bce344b.yml
  lib/modules/eic_default_content/content/block_content/4b678ea5-f56e-45af-8399-7adde0abab77.yml
  lib/modules/eic_default_content/content/block_content/5b0c5199-f4b0-4b8a-90fa-68d424e8315b.yml
  lib/modules/eic_default_content/content/block_content/8271c779-92e1-43f2-beb5-3addbfd84c70.yml
  lib/modules/eic_default_content/content/block_content/844a381c-6076-4279-834e-a75de967cf65.yml
  lib/modules/eic_default_content/content/block_content/880aff79-c4fa-416e-9703-0a3119bff5d0.yml
  lib/modules/eic_default_content/content/block_content/e1aefa16-ad60-4d15-ac07-4a9a2d8b6044.yml
  lib/modules/eic_default_content/content/file/3ccd6e97-f4d6-43df-8176-ec148da6fdb5.yml
  lib/modules/eic_default_content/content/file/511e7b45-d7ac-43f5-bf0c-83e7b7b66264.yml
  lib/modules/eic_default_content/content/file/515a8396-bea2-487a-9e33-0d13ac1e7e6b.yml
  lib/modules/eic_default_content/content/file/994-640x360.jpg
  lib/modules/eic_default_content/content/file/beautiful-tree-middle-field-covered-with-grass-with-tree-line-background.jpg
  lib/modules/eic_default_content/content/file/bf6cd939-12f5-4b6a-a82b-0c1c754b37ea.yml
  lib/modules/eic_default_content/content/file/chae-son-hot-spring-national-park-sunrise-lampang-province-thailand.jpg
  lib/modules/eic_default_content/content/file/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass.jpg
  lib/modules/eic_default_content/content/fragment/1b3fd03a-1809-4fc7-91cc-98e501c423da.yml
  lib/modules/eic_default_content/content/fragment/21d808f7-0c94-4093-a787-2da2f016047f.yml
  lib/modules/eic_default_content/content/fragment/29e0e971-0a3c-4e89-ab33-40deac6ae3f0.yml
  lib/modules/eic_default_content/content/fragment/572d06c5-1137-4afa-9a05-0dde42f48eef.yml
  lib/modules/eic_default_content/content/fragment/6d72a836-a912-41a7-b2cb-bd09714774ba.yml
  lib/modules/eic_default_content/content/fragment/cb09d2c3-86c7-4e94-8fb6-6f355fd55e5c.yml
  lib/modules/eic_default_content/content/media/f8df97c3-5505-47a6-8910-3f2282e6abcf.yml
  lib/modules/eic_default_content/content/menu_link_content/177d1a62-32c5-481e-a334-7b65be18f164.yml
  lib/modules/eic_default_content/content/menu_link_content/51a20c19-583d-4d8e-997a-bd78688ddf51.yml
  lib/modules/eic_default_content/content/menu_link_content/559d2b0b-f362-41af-b233-9e81c37badd9.yml
  lib/modules/eic_default_content/content/menu_link_content/81fa78a7-1601-4b97-9fdb-0e693db13039.yml
  lib/modules/eic_default_content/content/menu_link_content/9db0bc0c-877e-43c9-a440-707c91ee9928.yml
  lib/modules/eic_default_content/content/menu_link_content/f9f63eb3-d39d-46b1-90a8-f7511068d971.yml
  lib/modules/eic_default_content/content/node/31acecdc-7e2a-4521-8a42-340a2ee15f6b.yml
  lib/modules/eic_default_content/content/overview_page/23535531-875c-43f7-b1bf-af1e13cca1c5.yml
  lib/modules/eic_default_content/content/overview_page/aca89e07-3b4a-494c-9a71-24ea2ef6d330.yml
  lib/modules/eic_default_content/content/overview_page/b665f2a1-238b-41b1-9538-37550e55eba1.yml
  lib/modules/eic_default_content/content/taxonomy_term/06ebe2d2-0d23-43a7-b38f-1a70cea0edbd.yml
  lib/modules/eic_default_content/content/taxonomy_term/538468b5-718b-4e63-8846-323487bbf39c.yml
  lib/modules/eic_default_content/content/taxonomy_term/589c3dc4-6e6c-4836-9630-0850f1c4cee7.yml
  lib/modules/eic_default_content/content/taxonomy_term/6c4a40ca-d17b-44bd-828f-fbf0f28d99b7.yml
  lib/modules/eic_default_content/content/taxonomy_term/8f482971-901d-4e8c-9a3f-4e7d171f6a41.yml
  lib/modules/eic_default_content/content/taxonomy_term/eec3f017-d51e-4bfa-9abb-1fb3f7f2b1de.yml
  lib/modules/eic_default_content/eic_default_content.info.yml
  lib/modules/eic_default_content/eic_default_content.module
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
  lib/modules/eic_default_content/src/Generator/CoreGenerator.php
  lib/modules/eic_default_content/src/Generator/GroupGenerator.php
  lib/modules/eic_default_content/src/Generator/NewsGenerator.php
  lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
  lib/modules/eic_default_content/src/Generator/StoryGenerator.php
  lib/modules/eic_default_content/src/Generator/TaxonomyGenerator.php
  lib/themes/eic_community/includes/preprocess/blocks/block--cta-tiles.inc
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: enhancement

#595 EICNET-1395: Add local tasks on all contents
  config/sync/context.context.local_tasks.yml
Labels: backend

#603 EICNET-392: As a GO/GA, I can manage videos in the content of a Wiki detailed page
  lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
Labels: backend

#604 EICNET-1172: A group can only have one GO
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Validation/Constraint/GroupMembershipConstraint.php
  lib/modules/eic_groups/src/Plugin/Validation/Constraint/GroupMembershipConstraintValidator.php
Labels: backend

#610 EICNET-1188: CT gallery back-end (rework)
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/field.field.node.gallery.field_body.yml
  config/sync/field.field.node.gallery.field_document_type.yml
Labels: backend

#612 EICNET-1432: Conflict between redirect and group_permissions module
  lib/modules/eic_groups/eic_groups.module
Labels: bug, backend

#613 EICNET-1187: CT Video back-end (rework)
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/field.field.node.video.field_document_type.yml
  config/sync/field.field.node.video.field_video_media.yml
  config/sync/pathauto.pattern.library.yml
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
Labels: backend

#615 EICNET-1189: CT document back-end (rework)
  config/sync/field.field.node.document.field_document_media.yml
Labels: backend

#616 EICNET-1408: Update OpenEuropa modules to their latest version
  composer.json
  composer.lock
Labels: backend

#593 EICNET-1237: Wiki - Link Add wiki page is shown on moderated group (Part 2)
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
Labels: bug, backend

#594 EICNET-1397: Allow members to create videos in groups
  config/sync/eic_groups.group_features.eic_groups_files.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-member.yml
  config/sync/group.role.group-owner.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_files.yml
Labels: backend

#605 EICNET-1345: SA/SCM should be able to edit all group content of any group (Part 2)
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupNode.php
Labels: bug, backend

#621 EICNET-1375: Create all the follow flags
  config/sync/flag.flag.follow_content.yml
  config/sync/flag.flag.follow_taxonomy_term.yml
  config/sync/system.action.flag_action.follow_content_flag.yml
  config/sync/system.action.flag_action.follow_content_unflag.yml
  config/sync/system.action.flag_action.follow_taxonomy_term_flag.yml
  config/sync/system.action.flag_action.follow_taxonomy_term_unflag.yml
  config/sync/user.role.authenticated.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
Labels: enhancement, backend

#619 EICNET-1378: Automatically subscribe (flag) user on certain user actions
  config/sync/flag.flag.follow_content.yml
  config/sync/flag.flag.follow_taxonomy_term.yml
  config/sync/system.action.flag_action.follow_content_flag.yml
  config/sync/system.action.flag_action.follow_content_unflag.yml
  config/sync/system.action.flag_action.follow_taxonomy_term_flag.yml
  config/sync/system.action.flag_action.follow_taxonomy_term_unflag.yml
  config/sync/user.role.authenticated.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
Labels: enhancement, backend

#617 [EICNET-1396] fix: Some PHPStan error fixes
  composer.json
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
  lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupDiscussions.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupFiles.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupMembers.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Access/MediaFileDownloadAccessCheck.php
  lib/modules/eic_messages/eic_messages.module
  lib/modules/eic_messages/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Plugin/QueueWorker/MessageNotifyQueueWorker.php
  lib/modules/eic_messages/src/Plugin/views/filter/MessageTemplateType.php
  lib/modules/eic_messages/src/Service/CommentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
  lib/modules/eic_overviews/src/Form/OverviewPageForm.php
  lib/modules/eic_overviews/src/OverviewPageAccessControlHandler.php
  lib/modules/eic_private_content/eic_private_content.module
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/src/StatisticsStorage.php
  lib/modules/eic_statistics/src/StatisticsStorageInterface.php
  lib/modules/eic_webservices/src/Controller/SubRequestController.php
  lib/modules/eic_webservices/src/ParamConverter/SmedIdConverter.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserUpdateResource.php
  lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
  lib/modules/oec_group_comments/src/OecGroupCommentsAccessControlHandler.php
  lib/modules/oec_group_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
  lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
  lib/modules/oec_group_flex/src/GroupVisibilityDatabaseStorage.php
  lib/modules/oec_group_flex/src/GroupVisibilityDatabaseStorageInterface.php
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
  lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibilityManager.php
  lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
  phpstan.neon
Labels: enhancement

#624 [EICNET] fix: use correct type-hint for $plugin_id
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
Labels: bug, backend

#596 EICNET-1401: Fix download button URL in CT Document
  lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Hooks/EntityOperations.php
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: backend

#614 EICNET-962: As a GO I want to choose a URL alias for my group (rework)
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Hooks/Pathauto.php
Labels: backend

#626 EICNET-1355: Do not make avatar clickable for anonymous users
  lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
  lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/patterns/components/author.html.twig
Labels: bug, backend, frontend

#607 EICNET-787: Global search fixes.
  lib/themes/eic_community/data/teaser/search.data.js
  lib/themes/eic_community/images/sprite/custom/alert.svg
  lib/themes/eic_community/images/sprite/custom/arrow-down.svg
  lib/themes/eic_community/images/sprite/custom/bin.svg
  lib/themes/eic_community/images/sprite/custom/check_circle.svg
  lib/themes/eic_community/images/sprite/custom/clear.svg
  lib/themes/eic_community/images/sprite/custom/close.svg
  lib/themes/eic_community/images/sprite/custom/comment.svg
  lib/themes/eic_community/images/sprite/custom/company.svg
  lib/themes/eic_community/images/sprite/custom/content-page.svg
  lib/themes/eic_community/images/sprite/custom/discussion.svg
  lib/themes/eic_community/images/sprite/custom/document.svg
  lib/themes/eic_community/images/sprite/custom/documents.svg
  lib/themes/eic_community/images/sprite/custom/download.svg
  lib/themes/eic_community/images/sprite/custom/email.svg
  lib/themes/eic_community/images/sprite/custom/euro.svg
  lib/themes/eic_community/images/sprite/custom/facebook.svg
  lib/themes/eic_community/images/sprite/custom/feed.svg
  lib/themes/eic_community/images/sprite/custom/follow.svg
  lib/themes/eic_community/images/sprite/custom/group-approved.svg
  lib/themes/eic_community/images/sprite/custom/group.svg
  lib/themes/eic_community/images/sprite/custom/group_circle.svg
  lib/themes/eic_community/images/sprite/custom/handshake.svg
  lib/themes/eic_community/images/sprite/custom/highlight.svg
  lib/themes/eic_community/images/sprite/custom/idea.svg
  lib/themes/eic_community/images/sprite/custom/invite.svg
  lib/themes/eic_community/images/sprite/custom/leave.svg
  lib/themes/eic_community/images/sprite/custom/like.svg
  lib/themes/eic_community/images/sprite/custom/link.svg
  lib/themes/eic_community/images/sprite/custom/linkedin.svg
  lib/themes/eic_community/images/sprite/custom/list.svg
  lib/themes/eic_community/images/sprite/custom/lock.svg
  lib/themes/eic_community/images/sprite/custom/mail.svg
  lib/themes/eic_community/images/sprite/custom/mail_circle.svg
  lib/themes/eic_community/images/sprite/custom/mappin.svg
  lib/themes/eic_community/images/sprite/custom/message.svg
  lib/themes/eic_community/images/sprite/custom/more.svg
  lib/themes/eic_community/images/sprite/custom/news.svg
  lib/themes/eic_community/images/sprite/custom/objectif.svg
  lib/themes/eic_community/images/sprite/custom/pdf.svg
  lib/themes/eic_community/images/sprite/custom/question.svg
  lib/themes/eic_community/images/sprite/custom/remote.svg
  lib/themes/eic_community/images/sprite/custom/star_circle.svg
  lib/themes/eic_community/images/sprite/custom/story.svg
  lib/themes/eic_community/images/sprite/custom/tag.svg
  lib/themes/eic_community/images/sprite/custom/time.svg
  lib/themes/eic_community/images/sprite/custom/twitter.svg
  lib/themes/eic_community/images/sprite/custom/user.svg
  lib/themes/eic_community/images/sprite/custom/user_circle.svg
  lib/themes/eic_community/images/sprite/custom/views.svg
  lib/themes/eic_community/images/sprite/custom/wiki.svg
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/patterns/compositions/search/search.teaser.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
  lib/themes/eic_community/react/svg/svg.js
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/scripts/svg-sprites.js
  lib/themes/eic_community/styleguide/pages/search.stories.js
Labels: frontend

#631 [EICNET-1396] fix: PHPCS fixes for eic_flags
  composer.json
  lib/modules/eic_flags/eic_flags.api.php
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Access/RequestAccessCheck.php
  lib/modules/eic_flags/src/Controller/FlagRequestController.php
  lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
  lib/modules/eic_flags/src/FlaggingListBuilder.php
  lib/modules/eic_flags/src/Form/ListBuilderFilters.php
  lib/modules/eic_flags/src/Form/NewRequestForm.php
  lib/modules/eic_flags/src/Form/RequestCloseForm.php
  lib/modules/eic_flags/src/Hooks/FlagTokens.php
  lib/modules/eic_flags/src/Plugin/GroupContentEnabler/RequestDelete.php
  lib/modules/eic_flags/src/Plugin/QueueWorker/EICFlagNotifyQueueWorker.php
  lib/modules/eic_flags/src/RequestStatus.php
  lib/modules/eic_flags/src/RequestTypes.php
  lib/modules/eic_flags/src/Routing/EntityRequestRouteProvider.php
  lib/modules/eic_flags/src/Routing/RequestRoutes.php
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
  lib/modules/eic_flags/src/Service/HandlerInterface.php
  lib/modules/eic_flags/src/Service/RequestHandlerCollector.php
Labels: enhancement, backend

#602 [EICNET-798]fix: site_admin should also see content with community restriction
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
Labels: backend

#628 EICNET-1433: Video comments styling fix.
  lib/themes/eic_community/sass/compositions/_comment-overview.scss
Labels: frontend

#620 Feature/eicnet 1312 entity referencemigration
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_article.yml
  lib/modules/eic_migrate/eic_migrate.services.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend

#623 Bugfix/eicnet 971 make story author not linkable
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#625 [EICNET] fix: Reset owner & group for transferred files
  .gitlab-ci.yml
  .rsyncignore
Labels: bug

#636 EICNET-976: Removed unneeded html to get disclaimer styling correct
  lib/themes/eic_community/templates/field/field--node--field-disclaimer.html.twig
  lib/themes/eic_community/templates/field/fragment.html.twig
Labels: frontend

#609 [EICNET-1417]feat: Create comment system in react
  config/sync/context.context.group_discussion_detail.yml
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/themes/eic_community/eic_community.libraries.yml
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/react/Services/Translations.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/LoadMore.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupRequest.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/Permissions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/entrypoint.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
  lib/themes/eic_community/webpack.mix.js
Labels: enhancement, backend, frontend, react

#637 Feature/eicnet 1329 sort last liked
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.group_search.yml
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_search/src/SolrIndexes.php
Labels: backend

#622 EICNET-1164: When contributor field is left empty, the story can't be saved
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: backend

#641 EICNET-1329: Fix missing use statement.
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
Labels: bug, backend

#642 Bugfix: error disabling a group feature
  lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
Labels: bug, backend

#647 Bugfix: Add missing dependencies in eic_search and eic_flags module
  lib/modules/eic_flags/eic_flags.info.yml
  lib/modules/eic_search/eic_search.info.yml
Labels: bug, backend

#632 [EICNET-1333]feat: Create overview for stories and news
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/StorySourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/Services/TimeHelper.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/Footer.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Discussion/Comment.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: backend, frontend, react

#646 EICNET-1226: As a GM, I can upload my own videos
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#611 EICNET-1136: Member country overflow fix.
  lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/bundles/member.stories.js
Labels: frontend

#629 EICNET-1153 topic overflow fix
  lib/themes/eic_community/sass/components/_tag.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
Labels: frontend

#643 EICNET-1213: Search results update.
  lib/themes/eic_community/data/teaser/search.data.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
  lib/themes/eic_community/sass/compositions/_teaser-overview.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/pages/search.stories.js
Labels: frontend

#634 EICNET-975: Story attachment styling fixes.
  lib/themes/eic_community/sass/components/_attachment.scss
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/snippets/wysiwyg-example.html.twig
Labels: frontend

#618 EICNET-1099: Collapsible options new variant.
  lib/themes/eic_community/patterns/compositions/editorial-header.html.twig
  lib/themes/eic_community/patterns/compositions/simple-banner.html.twig
  lib/themes/eic_community/sass/compositions/_collapsible-options.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/compositions/collapsible-options.stories.js
  lib/themes/eic_community/templates/navigation/eic-content-actions.html.twig
Labels: frontend

#630 EICNET-784 update stats / removed unneeded flags / update copy of menu
  lib/themes/eic_community/data/subnavigation/overview.data.js
  lib/themes/eic_community/styleguide/bundles/group.stories.js
Labels: frontend

#536 Added navigation title for book content
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-content-book-navigation.inc
  lib/themes/eic_community/templates/blocks/block--eic-content-book-navigation.html.twig
Labels: backend, frontend

#658 Feature/eicnet 1323 sort by last commented
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.group_search.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Search/Sources/StorySourceType.php
Labels: backend

#656 EICNET-1367: Add metatags configuration for Video CT.
  config/sync/metatag.metatag_defaults.node__video.yml
Labels: backend

#640 EICNET-1365: Group description > leads to about page (rework)
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/themes/eic_community/includes/preprocess/field/field.inc
Labels: backend

#657 EICNET-730: Sorted group form fields as in design.
  config/sync/core.entity_form_display.group.group.default.yml
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/sass/components/_form.scss
  lib/themes/eic_community/templates/form/input--radio.html.twig
Labels: backend

#667 [EICNET]feat: Add SMTP module
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/smtp.settings.yml
  config/sync/system.mail.yml
Labels: enhancement, backend

#665 Fix: Add cursor pointer on Select
  lib/themes/eic_community/sass/components/_select.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: frontend

#662 add max width and more padding on activity stream
  lib/themes/eic_community/data/activity-stream.data.js
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
Labels: frontend

#663 Fix: add max-width on the modal content and remove the outline on the cancel btn
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/sass/core/_viewport.scss
Labels: frontend

#666 Feat: add correct design to comments
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/sass/compositions/_comment.scss
Labels: frontend, react
