Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-12, with the labels that each got.

#956 [EICNET]chore: rollback subpathauto so add content group works again
  composer.json
  composer.lock
Labels: backend

#939 EICNET-1736: Group ownership transfer: email notification
  config/sync/core.entity_form_display.message.notify_transfer_group_ownership.default.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.default.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.mail_subject.yml
  config/sync/field.field.message.notify_transfer_group_ownership.field_group_ref.yml
  config/sync/field.field.message.notify_transfer_group_ownership.field_related_user.yml
  config/sync/language/en/message.template.notify_transfer_group_ownership.yml
  config/sync/message.template.notify_transfer_group_ownership.yml
  lib/modules/eic_groups/modules/eic_group_membership/src/Controller/GroupMembershipController.php
  lib/modules/eic_messages/src/Util/NotificationMessageTemplates.php
Labels: enhancement, backend

#950 EICNET-1630: Private profile: back-end theming
  config/sync/core.date_format.month_full_year.yml
  config/sync/flag.flag.follow_user.yml
  lib/modules/eic_helper/src/DateTimeHelper.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/eic_user.services.yml
  lib/modules/eic_user/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/patterns/compositions/editorial-header.html.twig
  lib/themes/eic_community/styleguide/bundles/member.stories.js
  lib/themes/eic_community/templates/user/user--full.html.twig
Labels: enhancement, backend

#952 [EICNET] add no image state on member in react items
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
Labels: frontend, react

#943 [EICNET-1598] add related wiki in topics details page
  lib/themes/eic_community/data/featured-content-collection/discussion.data.js
  lib/themes/eic_community/data/featured-content-collection/index.js
  lib/themes/eic_community/data/featured-content-collection/wiki.data.js
  lib/themes/eic_community/data/teaser/index.js
  lib/themes/eic_community/data/teaser/wiki.data.js
  lib/themes/eic_community/patterns/compositions/topic/topic.details.html.twig
  lib/themes/eic_community/patterns/compositions/wiki/wiki.teaser.html.twig
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
  lib/themes/eic_community/styleguide/compositions/teaser.docs.mdx
  lib/themes/eic_community/styleguide/compositions/teaser.stories.js
Labels: frontend

#930 [EICNET] correct style for pagination
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
  lib/themes/eic_community/sass/compositions/_pagination.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: frontend, react

#897 [EICNET-1628] correct design for user profile and member overview
  lib/themes/eic_community/data/featured-content-sections/flagged-events.data.js
  lib/themes/eic_community/data/featured-content-sections/index.js
  lib/themes/eic_community/data/member-information-block.data.js
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/patterns/components/expandable-definitions.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.full.html.twig
  lib/themes/eic_community/sass/components/_address.scss
  lib/themes/eic_community/sass/components/_button.scss
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/sass/compositions/_collapsible-options.scss
  lib/themes/eic_community/sass/compositions/_contact-information-block.scss
  lib/themes/eic_community/sass/compositions/_extended-list.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/bundles/member.stories.js
Labels: frontend

#960 [EICNET-1830]feat: Filter on the correct group id
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#949 [EICNET-1761]feat: Add first section of the footer menu
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#951 [EICNET-1656]feat: Implement new access views plugin to allow block if linked feature enabled
  config/sync/core.entity_form_display.message.stream_share_content.default.yml
  config/sync/core.entity_view_display.user.user.compact.yml
  config/sync/views.view.group_discussions.yml
  config/sync/views.view.group_documents.yml
  config/sync/views.view.group_events.yml
  lib/modules/oec_group_features/src/Plugin/views/access/GroupFeatureAccess.php
Labels: backend

#907 Feature/eicnet 1718 topics overview fe
  config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
  config/sync/views.view.taxonomy_related_content.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_topics/src/TopicsManager.php
  lib/themes/eic_community/includes/alter/theme_suggestions/block.inc
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/ecl.inc
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/patterns/compositions/featured-content-collection.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.stats.html.twig
  lib/themes/eic_community/sass/compositions/_section-wrapper.scss
  lib/themes/eic_community/templates/blocks/block--eic-topics-statistics-block.html.twig
  lib/themes/eic_community/templates/blocks/block--global-block-taxonomy-term-page.html.twig
  lib/themes/eic_community/templates/blocks/block--system-main-block--taxonomy-term.html.twig
  lib/themes/eic_community/templates/content/node--event--teaser.html.twig
  lib/themes/eic_community/templates/layout/page--taxonomy--term.html.twig
  lib/themes/eic_community/templates/views/views-view--taxonomy--block-taxonomy-overview.html.twig
  lib/themes/eic_community/templates/views/views-view-unformatted--nude.html.twig
Labels: backend, frontend

#946 Feature/eicnet 1783 organisation visibility
  config/sync/core.extension.yml
  lib/modules/eic_groups/modules/eic_organisations/eic_organisations.info.yml
  lib/modules/eic_groups/modules/eic_organisations/src/Plugin/CustomRestrictedVisibility/RestrictedOrganisations.php
  lib/modules/eic_groups/src/Constants/GroupVisibilityType.php
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibilityBase.php
Labels: backend

#919 EICNET-1666: Force showing invitation group title event when user doesn't access to the group itself.
  lib/modules/eic_groups/eic_groups.module
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: bug, backend

#964 EICNET-1718: Add correct classes to the related wiki pages.
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: frontend

#916 EICNET-1689: Homepage last updated groups (rework)
  config/sync/views.view.groups_homepage.yml
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/templates/group/group--group--teaser.html.twig
Labels: bug, backend

#976 EICNET-1841: List of events in group overview page - show ongoing events
  config/sync/views.view.group_events.yml
Labels: backend

#974 EICNET-1780: Create News & Stories and Events overview pages in default content
  config/sync/core.entity_view_display.overview_page.overview_page.default.yml
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/MenuGenerator.php
  lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
  lib/modules/eic_overviews/eic_overviews.module
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: backend

#968 [EICNET] add search icon in subnav search
  lib/themes/eic_community/templates/group/eic-group-search-menu-field-search-submit.html.twig
Labels: frontend

#934 [EICNET] rework style of the comments modal
  lib/themes/eic_community/.DS_Store
  lib/themes/eic_community/data/.DS_Store
  lib/themes/eic_community/mails/mail-dist/.DS_Store
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/patterns/compositions/topic/topic.details.html.twig
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupComponents/Actions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupComponents/Layout.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupComponents/TaggedUsersModal.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupRequest.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TaggedUsers.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/Author.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
  lib/themes/eic_community/react/components/Block/Gallery/.DS_Store
  lib/themes/eic_community/sass/.DS_Store
  lib/themes/eic_community/sass/components/_author.scss
  lib/themes/eic_community/sass/components/_button.scss
  lib/themes/eic_community/sass/components/_modal.scss
  lib/themes/eic_community/sass/compositions/_comment-overview.scss
  lib/themes/eic_community/sass/compositions/_comment-thread.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/_mui.scss
Labels: frontend, react

#979 EICNET-1838: Display breadcrumbs below global overview banner
  config/sync/context.context.global.yml
  config/sync/context.context.global_breadcrumbs.yml
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc
  lib/themes/eic_community/templates/overview_pages/overview-page.html.twig
Labels: backend

#966 EICNET-286: As a site admin I want to be able to adapt the non logged in homepage welcome header content (Rework)
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: bug, backend

#975 EICNET-1627: As a user, I want to have a profile page so that I can see the personal informations of another user (Back-end)
  config/sync/flag.flag.follow_user.yml
  config/sync/user.role.trusted_user.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/src/Plugin/ActionLink/EICFlagCountLinkButton.php
  lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/templates/flag/eic-flag-count.html.twig
Labels: bug, enhancement, backend

#977 EICNET-1839: Private images re-used in homepage banner are not shown for anonymous
  composer.lock
  composer.patches.json
  config/sync/entity_usage.settings.yml
Labels: bug, enhancement, backend

#982 [EICNET] correct width on mobile for .ecl-editorial-article__content
  lib/themes/eic_community/sass/components/_gallery.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/templates/content/node--gallery--full.html.twig
Labels: bug, frontend

#973 EICNET-1835: User profile - My groups
  config/sync/views.view.groups.yml
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/templates/views/views-view--teaser-overview-with-wrapper.html.twig
Labels: enhancement, backend

#983 [EICNET] Event filelist add space between files and change btn style
  lib/themes/eic_community/sass/components/_filelist.scss
Labels: frontend

#981 [EICNET] Group discussions change the key author by name in the twig file
  lib/themes/eic_community/templates/content/node--discussion--full.html.twig
Labels: bug, frontend

#980 [EICNET] Teaser elements add click on empty state image
  lib/themes/eic_community/patterns/compositions/filelist/filelist.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/gallery/gallery.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/organisation/organisation.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/project/project.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/story/story.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/video/video.teaser.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
Labels: frontend, react

#969 Feature/eicnet homepage global responsive
  lib/themes/eic_community/patterns/compositions/mainmenu.html.twig
  lib/themes/eic_community/patterns/layout/base.html.twig
  lib/themes/eic_community/sass/components/_title.scss
  lib/themes/eic_community/sass/compositions/_fact-figures-wrapper.scss
  lib/themes/eic_community/sass/compositions/_global-header.scss
  lib/themes/eic_community/sass/compositions/_mainmenu.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/templates/navigation/menu--main.html.twig
Labels: frontend

#987 Feature/eicnet 1860 data export [Part 1]
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/views/field/GroupMembersByRole.php
  lib/modules/eic_groups/src/Plugin/views/field/RestrictedOrganisationTypes.php
  lib/modules/eic_groups/src/Plugin/views/field/RestrictedOrganisations.php
  lib/modules/oec_group_flex/oec_group_flex.module
  lib/modules/oec_group_flex/src/Plugin/views/field/GroupFlexFieldPluginBase.php
  lib/modules/oec_group_flex/src/Plugin/views/field/GroupVisibility.php
  lib/modules/oec_group_flex/src/Plugin/views/field/RestrictedEmailDomains.php
  lib/modules/oec_group_flex/src/Plugin/views/field/RestrictedUsers.php
Labels: backend

#971 Feature/eicnet groups responsive
  lib/themes/eic_community/includes/preprocess/blocks/block.inc
  lib/themes/eic_community/patterns/compositions/subnavigation.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/sass/components/_attachment.scss
  lib/themes/eic_community/sass/compositions/_base-layout.scss
  lib/themes/eic_community/sass/compositions/_discussion-thread.scss
  lib/themes/eic_community/sass/compositions/_subnavigation.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/templates/blocks/block--group-content-menu.html.twig
Labels: frontend, react

#984 [EICNET] members card remove margin on organisation
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#988 [EICNET] React comments responsive
  lib/themes/eic_community/.DS_Store
  lib/themes/eic_community/data/.DS_Store
  lib/themes/eic_community/mails/mail-dist/.DS_Store
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/Author.js
  lib/themes/eic_community/react/components/Block/Gallery/.DS_Store
  lib/themes/eic_community/sass/.DS_Store
  lib/themes/eic_community/sass/components/_modal.scss
  lib/themes/eic_community/sass/compositions/_comment-overview.scss
  lib/themes/eic_community/sass/compositions/_comment-thread.scss
  lib/themes/eic_community/sass/compositions/_comment.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
Labels: frontend

#989 [EICNET-1846] remove empty svg in sidebar of overview layout in react
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
Labels: frontend, react

#991 [EICNET-1849] correct checkbox style
  lib/themes/eic_community/sass/components/_checkbox.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: frontend

#992 [EICNET-1850] correct icon for tag in group overview
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js
  lib/themes/eic_community/sass/components/_tag.scss
Labels: frontend

#967 [EICNET-1790] correct design for Organisation overview in storybook
  lib/themes/eic_community/patterns/compositions/organisation/organisation.overview.html.twig
  lib/themes/eic_community/patterns/compositions/teaser-overview.html.twig
  lib/themes/eic_community/sass/compositions/_teaser-overview.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/bundles/organisation.stories.js
Labels: frontend

#985 [EICNET] Groups tables change view on mobile
  lib/themes/eic_community/sass/compositions/_table.scss
  lib/themes/eic_community/templates/views/views-view-table.html.twig
Labels: frontend

#990 [EICNET-1848] add placeholder and icon
  lib/themes/eic_community/images/sprite/custom/search.svg
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/sass/compositions/_filter-sidebar.scss
Labels: frontend, react

#1006 [EICNET-1670]feat: Adapt comment section for non-group content
  config/sync/context.context.comments.yml
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/oec_group_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
Labels: backend

#1002 [EICNET-1728]fix: remove empty email when trying to invite people
  lib/modules/eic_user/src/Hooks/FormAlter.php
Labels: backend
