Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-07, with the labels that each got.

#411 EICNET-981: Based login redirect on current url instead of group url.
  config/sync/context.context.group_discussion_detail.yml
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#408 [EICNET-1071] fix: Group alias update - check for null
  lib/modules/eic_groups/src/Hooks/CronOperations.php
Labels: backend

#414 EICNET-1070: Improve - validation of URLs of social channels on the user profile
  config/sync/context.context.group_global.yml
  lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
Labels: backend

#417 EICNET-1129: Missing some flags in the group header
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#421 EICNET-1134: Rename the admin role to "Drupal admin"
  config/sync/group.role.group-a416e6833.yml
  config/sync/user.role.administrator.yml
Labels: backend, enhancement

#396 EICNET-1113: Implement the missing statistics to the group header
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/entity_usage.settings.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_groups/eic_groups.info.yml
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.info.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticTypes.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatistics.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelperInterface.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsSearchApiReindex.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorageInterface.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
Labels: backend

#416 EICNET-1044: Create separate business role for site admin separate from user 1 admin (part 2)
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-dcb2f93df.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#422 EICNET-1139: Show group menu on wiki pages
  config/sync/context.context.group_wiki_overview.yml
  config/sync/context.context.group_wiki_page.yml
Labels: backend

#413 EICNET-1126: Changed copy on about page.
  config/sync/context.context.group_wiki_overview.yml
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: frontend

#424 [EICNET-1107] As an anonymous user I can share a public story on social media
  config/sync/metatag.metatag_defaults.node__story.yml
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/templates/content/node--story--full.html.twig
Labels: backend, enhancement

#425 [EICNET-1150] Backend - Empty Contributor paragraph added by default
  config/sync/core.entity_form_display.node.story.default.yml
Labels: backend

#419 [EICNET-962] chore: As a GO I want to choose a URL alias for my group
  config/sync/core.entity_form_display.group.group.default.yml
Labels: backend, enhancement

#418 [EICNET-957] A a site user I'm not allowed to create group content outside of a group
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/OrphanGroupContentAccessCheck.php
  lib/modules/eic_groups/src/ForbiddenOrphanContentTypes.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
Labels: backend

#390 [EICNET-841]feature: Implement layout source configuration + User gal…
  .env
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/modules/eic_search/templates/search-overview-block.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/react/svg/svg.js
Labels: backend, frontend

#429 EICNET-963: Remove "add book page" from options to post content inside a group
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
Labels: backend

#427 EICNET-1140: Allow bypass access check for user 1 and drupal admin
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
  lib/modules/eic_groups/src/Access/PublishGroupAccessChecker.php
  lib/modules/eic_groups/src/EicGroupsServiceProvider.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
  lib/modules/eic_user/src/UserHelper.php
Labels: backend

#420 EICNET-1130: Remove the helptext shown on the LinkedIn field on a member profile
  lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
Labels: backend, bug

#428 Feature/eicnet 1143 activity stream checkbox node edit form
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  lib/modules/eic_messages/eic_messages.module
  lib/modules/eic_messages/eic_messages.services.yml
  lib/modules/eic_messages/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
  lib/modules/eic_messages/src/Service/MessageCreatorBase.php
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: backend

#437 Bugfix: Load group statistics from SOLR
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
Labels: backend, bug

#438 EICNET-1157: Group content still accessible to anonymous users after visibility change to "private"
  lib/modules/oec_group_flex/src/Plugin/RestrictedGroupVisibilityBase.php
Labels: backend, bug

#440 EICNET-997: As an anonymous user I can like a public story
  config/sync/flag.flag.like_content.yml
  config/sync/flag.flag.recommend_group.yml
Labels: backend

#439 [EICNET]chore: Upgrade storybook with webpack
  lib/themes/eic_community/.storybook/main.js
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: frontend

#441 EICNET-1165: Group statistics doesn't update for logged in users
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend, bug

#434 Fixed bugs found by Q&A.
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc
Labels: frontend

#431 EICNET-1151: Added search form to main menu.
  lib/themes/eic_community/templates/navigation/menu--main.html.twig
Labels: frontend

#445 [EICNET-1175]feature: add dedicated pages for people, groups and search. disable some views feature
  config/sync/context.context.group_members_overviews.yml
  config/sync/context.context.group_wiki_overview.yml
  config/sync/context.context.groups_overview.yml
  config/sync/context.context.members_overview.yml
  config/sync/context.context.search.yml
  config/sync/facets.facet.global_members_job_title.yml
  config/sync/facets.facet.global_members_topics_of_interest.yml
  config/sync/facets.facet.members_job_title.yml
  config/sync/facets.facet.members_topics_of_interest.yml
  config/sync/facets_summary.facets_summary.group_members_summary.yml
  config/sync/search_api_solr.solr_field_type.text_en_6_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_en_7_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_und_6_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_und_7_0_0.yml
  config/sync/search_api_sorts.search_api_sorts_field.views_page---global_overviews__page_1_flag_recommend_group_count.yml
  config/sync/search_api_sorts.search_api_sorts_field.views_page---global_overviews__search_search_api_relevance.yml
  config/sync/search_api_sorts.search_api_sorts_field.views_page---group_overviews__search_group_search_api_relevance.yml
  config/sync/views.view.global_overviews.yml
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_groups/src/Form/SearchMenuGroupForm.php
  lib/modules/eic_search/eic_search.routing.yml
  lib/modules/eic_search/src/Controller/SearchController.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: backend
