Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-10, with the labels that each got.

#661 [EICNET-1448]feat: Implement no results on results overview
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: backend, frontend, react

#678 Bugfix: Fix error in eic_community_preprocess_node__document()
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: bug, backend

#668 EICNET-1415: Email notification queue for subscriptions
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Event/MessageSubscriptionEvents.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/CronOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionHelper.php
Labels: backend

#670 EICNET-1472: Send message upon user actions and subscribe users to it using the correct flags (PART 2)
  config/sync/core.entity_form_display.message.sub_new_content_recommendation.default.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.default.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_new_content_recommendation.notify_weekly_digest.yml
  config/sync/field.field.message.sub_new_content_recommendation.field_referenced_node.yml
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.services.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Event/MessageSubscriptionEvents.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/MessageSubscriptionEventSubscriber.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionHelper.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
  lib/modules/eic_messages/src/Service/NodeMessageCreator.php
Labels: backend

#655 Feature/eicnet 1331 last flagged items
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.group_search.yml
  config/sync/flag.flag.bookmark_content.yml
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_search/eic_search.info.yml
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Search/Sources/StorySourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#672 EICNET-1355: Allow SA/SCM and TU to view user profiles (Rework)
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: backend

#683 EICNET-1461: As a TU I can't create a story
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.service_authentication.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: backend

#685 EICNET-1410: Unexpected error when viewing About page of public group as TU
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: bug, backend

#682 EICNET-1467: Groups - Specific user not saved in visibility Custom restriction
  lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
  lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedUsers.php
Labels: bug, backend

#686 EICNET-1403: Story - Document shows body text instead of title
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: backend

#688 EICNET-1511: Group overview in Drupal admin
  config/sync/views.view.admin_groups.yml
  lib/modules/eic_admin/eic_admin.links.menu.yml
Labels: backend

#684 EICNET-1404: Story - Only 1st document is shown
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
  lib/themes/eic_community/templates/content/node--story--full.html.twig
Labels: bug, backend

#690 EICNET-1133: Fix the group menu active item
  config/sync/context.context.group_global.yml
  lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php
  lib/themes/eic_community/includes/preprocess/blocks/block.inc
  lib/themes/eic_community/templates/blocks/block--eic-group-content-menu.html.twig
Labels: bug, backend

#692 EICNET-1493: Groups - Group owner in group teaser links to groups overview
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: bug, backend, frontend

#673 EICNET-635 Fix: change position of the CommentForm
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: frontend, react

#664 Feat: scroll to top when page change
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: frontend, react

#699 EICNET-1133: Fix error when trying to create a group as a TU
  lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php
Labels: bug, backend

#709 EICNET-1369 Fix: Add margin after comment overview above an video
  lib/themes/eic_community/patterns/compositions/comment/comment-overview.html.twig
Labels: frontend

#714 EICNET-1367 | Feat: Follow-us item for the homepage
  lib/themes/eic_community/patterns/components/follow-us.html.twig
  lib/themes/eic_community/patterns/compositions/follow-us.html.twig
  lib/themes/eic_community/patterns/pages/homepage/homepage.private.html.twig
  lib/themes/eic_community/patterns/pages/homepage/homepage.public.html.twig
  lib/themes/eic_community/sass/components/_follow-us.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/styleguide/components/follow-us.docs.mdx
  lib/themes/eic_community/styleguide/components/follow-us.stories.js
  lib/themes/eic_community/styleguide/compositions/follow-us.docs.mdx
  lib/themes/eic_community/styleguide/compositions/follow-us.stories.js
  lib/themes/eic_community/styleguide/pages/homepage.stories.js
Labels: frontend

#711 EICNET-1497: Internal server error when adding document to group
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/MediaLibrary/MediaLibraryFieldWidgetOpener.php
Labels: backend

#716 EICNET-1535: Basic file extensions for MT document
  config/sync/field.field.media.eic_document.field_media_file.yml
Labels: backend

#722 EICNET-1343: Documents in Discussion are not shown
  config/sync/core.entity_view_display.node.discussion.default.yml
  config/sync/field.field.node.discussion.field_related_documents.yml
  lib/themes/eic_community/templates/content/node--discussion--full.html.twig
Labels: backend, frontend

#704 Feature/eicnet 1416 anti spam threshold
  config/sync/eic_messages.settings.yml
  lib/modules/eic_messages/config/install/eic_messages.settings.yml
  lib/modules/eic_messages/config/schema/eic_messages.schema.yml
  lib/modules/eic_messages/eic_messages.services.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/MessageSubscriptionEventSubscriber.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
  lib/modules/eic_messages/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/src/MessageIdentifierInterface.php
  lib/modules/eic_messages/src/Service/CommentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
  lib/modules/eic_messages/src/Service/MessageCreatorBase.php
  lib/modules/eic_messages/src/Service/MessageCreatorInterface.php
  lib/modules/eic_messages/src/Service/NodeMessageCreator.php
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
  lib/modules/eic_messages/src/Util/ActivityStreamMessageTemplates.php
Labels: backend

#705 [EICNET-1101]feat: send translations separated by source, default sort selected + implement new statistics
  config/sync/context.context.group_files_overviews.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/SortOption.js
Labels: backend, frontend, react

#732 [EICNET] chore: Ignore some files during rsync
  .gitlab-ci.yml
  .rsyncignore
Labels: enhancement

#660 [EICNET-1205]feat: Adapt also comments for gallery and video
  config/sync/context.context.gallery_detail.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.gallery.full.yml
  config/sync/core.entity_view_display.node.gallery.teaser.yml
  config/sync/field.field.node.gallery.field_related_contributors.yml
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/themes/eic_community/patterns/compositions/video/video.full.html.twig
Labels: backend

#679 [EICNET-745]feature: Do not force delete, use soft delete and replace by message
  config/sync/core.entity_form_display.comment.node_comment.default.yml
  config/sync/core.entity_view_display.comment.node_comment.default.yml
  config/sync/field.field.comment.node_comment.field_comment_deletion_date.yml
  config/sync/field.field.comment.node_comment.field_comment_is_soft_deleted.yml
  config/sync/field.storage.comment.field_comment_deletion_date.yml
  config/sync/field.storage.comment.field_comment_is_soft_deleted.yml
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_search/eic_search.info.yml
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/Permissions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: backend, frontend, react

#744 [EICNET-1405]feat: if there is no values for required field tree, scroll to it
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
Labels: react

#747 [EICNET]fix: Fix community path on different env
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/Permissions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/UrlHelper.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: react

#739 Fix: correct color for public tag
  lib/themes/eic_community/sass/components/_tag.scss
Labels: frontend

#738 EICNET-1476 | Fix: wrap header in a story
  lib/themes/eic_community/sass/compositions/_editorial-header.scss
Labels: frontend

#749 EICNET-1520: Fix issue when creating a new node.
  lib/modules/eic_comments/eic_comments.module
Labels: bug, backend
