Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-08, with the labels that each got.

#451 [EICNET-967] chore: Add the request reason to handled requests list
  config/sync/views.view.closed_requests.yml
Labels: backend, enhancement

#450 [EICNET-1016] fix: Add a link to the moderator in archived mails
  config/sync/language/en/message.template.notify_delete_request_archived.yml
  config/sync/message.template.notify_delete_request_archived.yml
Labels: backend

#449 [EICNET-831] Add entity label in request mail's subject
  config/sync/message.template.notify_new_archival_request.yml
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: backend, enhancement

#447 [EICNET-1171] fix: Add a link to the entity title in new archival request mails
  config/sync/message.template.notify_new_archival_request.yml
Labels: backend

#453 [EICNET-841]fix: Change template to gallery instead of list
  config/sync/context.context.members_overview.yml
Labels: backend

#452 [EICNET-787]fix: Remove the word "page" after content type
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: frontend

#446 [EICNET-1164] fix: Prevent error for optional contributor fields
  lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc
Labels: backend

#442 EICNET-975: Fix Story document title
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: backend

#460 EICNET-1192: Group in Draft state can not be saved as Draft state
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
  config/sync/workflows.workflow.groups.yml
Labels: backend

#461 EICNET-1185: Delete the recommend flag on stories
  config/sync/flag.flag.recommend.yml
  lib/modules/eic_content/eic_content.services.yml
  lib/modules/eic_content/src/ContentBreadcrumbBuilder.php
Labels: backend

#458 EICNET-1211/EICNET-1212: Make topic field required for CT Document and CT Gallery
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/field.field.node.document.field_vocab_topics.yml
  config/sync/field.field.node.gallery.field_vocab_topics.yml
Labels: backend

#455 EICNET-1129: Missing invite flag in group header
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
Labels: enhancement, backend

#456 EICNET-1166: Fix ajax callback issues in forms
  lib/modules/eic_messages/src/Hooks/FormOperations.php
Labels: bug, backend

#457 EICNET-1165: Fix Group statistics update on install
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
Labels: bug, backend

#465 EICNET-1167: Adapt the group statistics when group content is archived
  lib/modules/eic_comments/eic_comments.services.yml
  lib/modules/eic_comments/src/CommentsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#444 Feature/EICNET-1124: Standardize local envs
  .env
  .env.docker
  .gitignore
  Makefile
  README.md
  docker-compose.yml
  docker/apache/Dockerfile
  docker/apache/apache-foreground
  docker/apache/vhosts/localhost.conf
  docker/php/Dockerfile
  docker/php/database-healthcheck.sh
  docker/php/dev.ini
  docker/php/php.ini
  runner.yml.dist
  web/sites/default/default.settings.local.php
Labels: enhancement, backend

#466 EICNET-1193: Discussions tab of public group not shown for anonymous user/TU
  config/sync/eic_groups.group_features.eic_groups_discussions.yml
  config/sync/eic_groups.group_features.eic_groups_members.yml
  config/sync/eic_groups.group_features.eic_groups_wiki.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_discussions.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_members.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_wiki.yml
  lib/modules/eic_groups/config/schema/eic_groups.group_features.schema.yml
  lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
Labels: backend

#435 EICNET-976: As an anonymous user I can see the disclaimer of this story
  config/sync/core.entity_form_display.fragment.banner.default.yml
  config/sync/core.entity_form_display.fragment.disclaimer.default.yml
  config/sync/core.entity_form_display.fragment.fact_figure.default.yml
  config/sync/core.entity_view_display.fragment.banner.default.yml
  config/sync/core.entity_view_display.fragment.disclaimer.default.yml
  config/sync/core.entity_view_display.fragment.fact_figure.default.yml
  config/sync/field.field.fragment.banner.field_body.yml
  config/sync/field.field.fragment.disclaimer.field_body.yml
  config/sync/field.field.fragment.fact_figure.field_body.yml
  config/sync/field.storage.fragment.field_body.yml
Labels: backend, frontend

#462 [EICNET-1175]feature: Add spellcheck on search and more filters
  config/sync/context.context.search.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend, frontend

#464 [EICNET-1187]feature: Create video content type
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/field.field.node.video.field_body.yml
  config/sync/field.field.node.video.field_comments.yml
  config/sync/field.field.node.video.field_video_media.yml
  config/sync/field.field.node.video.field_vocab_topics.yml
  config/sync/field.storage.node.field_video_media.yml
  config/sync/node.type.video.yml
Labels: backend

#463 [EICNET-959]feature: Add query to prefilter private content for anonymous
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: backend

#459 EICNET-1176: Maintenance sprint 21
  composer.json
  composer.lock
  config/sync/views.view.scheduler_scheduled_content.yml
Labels: backend

#468 [EICNET-1221] chore: Allow multiple media in Document's field_document_media
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/field.storage.node.field_document_media.yml
Labels: enhancement, backend

#472 [EICNET-1180] chore: Label change for the group follow flag
  config/sync/flag.flag.follow_group.yml
Labels: backend

#471 [EICNET-1173] chore: Do not display social_share block on private news & stories
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: backend

#477 [EICNET-1163]feature: Add "disable top level selection" so moderator will not be able to select top options
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_form_display.node.video.default.yml
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/themes/eic_community/react/components/Field/EntityTree/entrypoint.js
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
Labels: backend, frontend

#475 [EICNET-1172]fix: Remove the "group owner" option in the group invite form
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Hooks/FormOperations.php
Labels: backend

#473 [EICNET-1182]fix: Remove the "leave group" link if group in draft/pending or if the user is the group owner
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#433 EICNET-899: Migration of users.
  config/sync/migrate_plus.migration.upgrade_d7_user.yml
  config/sync/migrate_plus.migration.upgrade_d7_user_to_profile.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_document_type.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_to_profile.yml
Labels: backend

#469 [EICNET-1191] feat: Add a permission and endpoint to highlight group content
  config/sync/flag.flag.highlight_content.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-owner.yml
  config/sync/search_api.index.global.yml
  config/sync/system.action.flag_action.highlight_content_flag.yml
  config/sync/system.action.flag_action.highlight_content_unflag.yml
  lib/modules/eic_groups/eic_groups.group.permissions.yml
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/HighlightGroupContentAccessCheck.php
  lib/modules/eic_groups/src/Controller/GroupOperationsController.php
  lib/modules/eic_search/eic_search.module
Labels: backend

#470 [EICNET-1188]feature: Add paragraph slides field to gallery and refactor the solr processor
  .gitignore
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.paragraph.gallery_slide.default.yml
  config/sync/core.entity_view_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.gallery.full.yml
  config/sync/core.entity_view_display.node.gallery.teaser.yml
  config/sync/core.entity_view_display.paragraph.gallery_slide.default.yml
  config/sync/field.field.node.gallery.field_gallery_slides.yml
  config/sync/field.field.node.gallery.field_photos.yml
  config/sync/field.field.paragraph.gallery_slide.field_gallery_slide_legend.yml
  config/sync/field.field.paragraph.gallery_slide.field_gallery_slide_media.yml
  config/sync/field.storage.node.field_gallery_slides.yml
  config/sync/field.storage.paragraph.field_gallery_slide_legend.yml
  config/sync/field.storage.paragraph.field_gallery_slide_media.yml
  config/sync/paragraphs.paragraphs_type.gallery_slide.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  private_files/.gitkeep
  web/sites/default/default.settings.local.php
Labels: backend

#474 [EICNET-1181]fix: If group does not allow to invite members, hide invite group link in header
  config/sync/core.entity_form_display.group.group.default.yml
  config/sync/core.entity_view_display.group.group.about_page.yml
  config/sync/core.entity_view_display.group.group.default.yml
  config/sync/core.entity_view_display.group.group.teaser.yml
  config/sync/field.field.group.group.field_group_invite_members.yml
  config/sync/field.storage.group.field_group_invite_members.yml
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#483 [EICNET-1245] Introduce NFS mounts for macOS users
  Makefile
  README.md
  docker/macos.volumes.yml
  docker/solr/6.x/accents_en.txt
  docker/solr/6.x/accents_und.txt
  docker/solr/6.x/elevate.xml
  docker/solr/6.x/protwords_en.txt
  docker/solr/6.x/protwords_und.txt
  docker/solr/6.x/schema.xml
  docker/solr/6.x/schema_extra_fields.xml
  docker/solr/6.x/schema_extra_types.xml
  docker/solr/6.x/solrconfig.xml
  docker/solr/6.x/solrconfig_extra.xml
  docker/solr/6.x/solrconfig_index.xml
  docker/solr/6.x/solrcore.properties
  docker/solr/6.x/stopwords_en.txt
  docker/solr/6.x/stopwords_und.txt
  docker/solr/6.x/synonyms_en.txt
  docker/solr/6.x/synonyms_und.txt
Labels: enhancement

#486 EICNET-955: Truncate group description to 350 chars in group header.
  config/sync/core.entity_view_display.group.group.default.yml
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#487 [EICNET-1179]feature: Show draft/pending groups for matching group owner
  config/sync/context.context.groups_overview.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: backend, frontend

#489 EICNET-1079: Create a group feature for "Latest activity"
  config/sync/eic_groups.group_features.eic_groups_latest_activity_stream.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_latest_activity_stream.yml
  lib/modules/eic_groups/eic_groups.group.permissions.yml
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
Labels: backend

#480 EICNET-906: Fixed labels for media fields, added topics and region fields
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/field.field.node.wiki_page.field_vocab_geo.yml
  config/sync/field.field.node.wiki_page.field_vocab_topics.yml
  lib/themes/eic_community/templates/form/fieldset.html.twig
Labels: backend

#500 [EICNET-1162] fix: Add login link on groups page and destination on all login links
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/templates/layout/page--groups.html.twig
Labels: backend

#502 [EICNET-1144]feat: show last five members of a group
  config/sync/core.date_format.eu_format.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/LastGroupMembersBlock.php
  lib/modules/eic_groups/templates/eic-group-last-members.html.twig
Labels: backend, frontend

#499 [EICNET-1163]fix: If the option disable top selection is enable, do not propose in search element and hide checkbox
  lib/modules/eic_content/src/Controller/EntityTreeController.php
  lib/modules/eic_content/src/Services/EntityTreeManager.php
  lib/themes/eic_community/react/components/Field/EntityTree/Result/ResultItem.js
  lib/themes/eic_community/react/components/Field/EntityTree/Result/Results.js
  lib/themes/eic_community/react/components/Field/EntityTree/Result/Search.js
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
Labels: backend, frontend

#497 [EICNET-1248]feat: Add loadmore option on the overview
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/LoadMore.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend, frontend

#511 EICNET-111: Added please in the comments context.
  config/sync/context.context.comment_pages.yml
Labels: bug, backend

#504 [EICNET] chore: call make build-front during update
  Makefile
Labels: enhancement

#514 EICNET-1133: Patch the group_content_menu to fix the active trail.
  composer.lock
  composer.patches.json
  lib/themes/eic_community/includes/preprocess/blocks/block--group-menu.inc
Labels: backend

#505 Feature/eicnet 1159 import languages taxonomy
  composer.json
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.taxonomy_term.document_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.funding_source.default.yml
  config/sync/core.entity_form_display.taxonomy_term.geo.default.yml
  config/sync/core.entity_form_display.taxonomy_term.job_titles.default.yml
  config/sync/core.entity_form_display.taxonomy_term.languages.default.yml
  config/sync/core.entity_form_display.taxonomy_term.topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.user_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.document_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.funding_source.default.yml
  config/sync/core.entity_view_display.taxonomy_term.geo.default.yml
  config/sync/core.entity_view_display.taxonomy_term.job_titles.default.yml
  config/sync/core.entity_view_display.taxonomy_term.languages.default.yml
  config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.user_types.default.yml
  config/sync/field.field.taxonomy_term.document_types.field_smed_id.yml
  config/sync/field.field.taxonomy_term.funding_source.field_smed_id.yml
  config/sync/field.field.taxonomy_term.geo.field_smed_id.yml
  config/sync/field.field.taxonomy_term.job_titles.field_smed_id.yml
  config/sync/field.field.taxonomy_term.languages.field_smed_id.yml
  config/sync/field.field.taxonomy_term.topics.field_smed_id.yml
  config/sync/field.field.taxonomy_term.user_types.field_smed_id.yml
  config/sync/field.storage.taxonomy_term.field_smed_id.yml
  config/sync/migrate_plus.migration.smed_spoken_languages.yml
  config/sync/migrate_plus.migration.smed_thematics_topics_lvl1.yml
  config/sync/migrate_plus.migration.smed_thematics_topics_lvl2.yml
  config/sync/migrate_plus.migration.smed_thematics_topics_lvl3.yml
  config/sync/migrate_plus.migration_group.eic_smed_taxonomy.yml
  lib/modules/eic_webservices/README.md
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_spoken_languages.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_thematics_topics_lvl1.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_thematics_topics_lvl2.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_thematics_topics_lvl3.yml
  lib/modules/eic_webservices/eic_webservices.info.yml
  lib/modules/eic_webservices/src/Plugin/migrate/source/EicSmedUrl.php
  lib/modules/eic_webservices/src/Plugin/migrate_plus/data_fetcher/EicHttpSmedTaxonomyPost.php
  lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
  web/sites/default/default.settings.local.php
Labels: backend

#507 Feature/eicnet 1255: Added activity stream.
  lib/themes/eic_community/data/activity-stream.data.js
  lib/themes/eic_community/data/members.data.js
  lib/themes/eic_community/data/subnavigation/activity.data.js
  lib/themes/eic_community/data/subnavigation/index.js
  lib/themes/eic_community/patterns/components/author.html.twig
  lib/themes/eic_community/patterns/compositions/activity-stream.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.full--activity.html.twig
  lib/themes/eic_community/sass/components/_author.scss
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/components/author.stories.js
  lib/themes/eic_community/styleguide/compositions/activity-stream.docs.mdx
  lib/themes/eic_community/styleguide/compositions/activity-stream.stories.js
Labels: frontend

#512 EICNET-1216: Discussion teaser shows HTML code
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
Labels: bug, backend

#509 EICNET-1132: a SA can see all groups in every state
  config/sync/oec_group_flex.settings.yml
  lib/modules/oec_group_flex/config/install/oec_group_flex.settings.yml
  lib/modules/oec_group_flex/oec_group_flex.module
  lib/modules/oec_group_flex/src/Form/GroupVisibilitySettingsForm.php
  lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PrivateVisibility.php
Labels: bug, backend

#513 EICNET-1156: Breadcrumb - Story should be Stories
  lib/modules/eic_content/src/ContentBreadcrumbBuilder.php
Labels: backend

#515 EICNET-400: Text formats - input filter to block iframes
  config/sync/core.extension.yml
  config/sync/filter.format.filtered_html.yml
  config/sync/filter.format.full_html.yml
  config/sync/oe_webtools_cookie_consent.settings.yml
Labels: backend

#508 [EICNET-783]fix: Use correctly the group directly instead of loading wrong group content
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: bug, backend

#519 EICNET-389/390: Enable media type "Video" in "News" and "Story"
  config/sync/core.entity_view_display.media.video.default.yml
  config/sync/field.field.node.news.field_video.yml
  config/sync/field.field.node.story.field_video.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: backend

#517 EICNET-1243: Moved homepage facts and figures block down.
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/templates/layout/page--front--anonymous.html.twig
  lib/themes/eic_community/templates/layout/page--front.html.twig
Labels: backend, frontend

#496 moved video bundle under group
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/bundles/video.stories.js
Labels: frontend

#523 EICNET-1162: Multiple fixes.
  lib/themes/eic_community/includes/preprocess/comments/comment.inc
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/templates/content/comment.html.twig
  lib/themes/eic_community/templates/content/node--discussion--full.html.twig
  lib/themes/eic_community/templates/field/field--node--field-comments.html.twig
Labels: backend, frontend

#524 Feature/eicnet 1256: Added modal + activity stream deletion of messages
  lib/themes/eic_community/data/activity-stream.data.js
  lib/themes/eic_community/patterns/compositions/activity-stream.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.full--activity.html.twig
  lib/themes/eic_community/patterns/layout/base.html.twig
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
  lib/themes/eic_community/sass/core/_viewport.scss
  lib/themes/eic_community/sass/schema/_typography.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
Labels: frontend

#387 Feature/eicnet 851 create overview pages
  composer.json
  composer.lock
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_members_overviews.yml
  config/sync/context.context.group_search.yml
  config/sync/core.entity_form_display.overview_page.overview_page.default.yml
  config/sync/core.entity_view_display.overview_page.overview_page.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.overview_page.overview_page.field_overview_block.yml
  config/sync/field.storage.overview_page.field_overview_block.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/group.role.group-member.yml
  config/sync/group.role.group-owner.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_administrator.yml
  config/sync/views.view.global_overviews.yml
  config/sync/views.view.group_overviews.yml
  lib/modules/eic_default_content/content/file/3ccd6e97-f4d6-43df-8176-ec148da6fdb5.yml
  lib/modules/eic_default_content/content/file/511e7b45-d7ac-43f5-bf0c-83e7b7b66264.yml
  lib/modules/eic_default_content/content/file/beautiful-tree-middle-field-covered-with-grass-with-tree-line-background.jpg
  lib/modules/eic_default_content/content/file/bf6cd939-12f5-4b6a-a82b-0c1c754b37ea.yml
  lib/modules/eic_default_content/content/file/chae-son-hot-spring-national-park-sunrise-lampang-province-thailand.jpg
  lib/modules/eic_default_content/content/file/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass.jpg
  lib/modules/eic_default_content/content/menu_link_content/177d1a62-32c5-481e-a334-7b65be18f164.yml
  lib/modules/eic_default_content/content/menu_link_content/81fa78a7-1601-4b97-9fdb-0e693db13039.yml
  lib/modules/eic_default_content/content/overview_page/23535531-875c-43f7-b1bf-af1e13cca1c5.yml
  lib/modules/eic_default_content/content/overview_page/aca89e07-3b4a-494c-9a71-24ea2ef6d330.yml
  lib/modules/eic_default_content/content/overview_page/b665f2a1-238b-41b1-9538-37550e55eba1.yml
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupDiscussions.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupMembers.php
  lib/modules/eic_overviews/README.md
  lib/modules/eic_overviews/config/install/core.entity_form_display.overview_page.overview_page.default.yml
  lib/modules/eic_overviews/config/install/core.entity_view_display.overview_page.overview_page.default.yml
  lib/modules/eic_overviews/config/install/field.field.overview_page.overview_page.field_overview_block.yml
  lib/modules/eic_overviews/config/install/field.storage.overview_page.field_overview_block.yml
  lib/modules/eic_overviews/eic_overviews.group.permissions.yml
  lib/modules/eic_overviews/eic_overviews.info.yml
  lib/modules/eic_overviews/eic_overviews.links.action.yml
  lib/modules/eic_overviews/eic_overviews.links.menu.yml
  lib/modules/eic_overviews/eic_overviews.links.task.yml
  lib/modules/eic_overviews/eic_overviews.permissions.yml
  lib/modules/eic_overviews/eic_overviews.routing.yml
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
  lib/modules/eic_overviews/src/Entity/OverviewPage.php
  lib/modules/eic_overviews/src/Form/OverviewPageForm.php
  lib/modules/eic_overviews/src/Form/OverviewPageSettingsForm.php
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
  lib/modules/eic_overviews/src/OverviewPageAccessControlHandler.php
  lib/modules/eic_overviews/src/OverviewPageInterface.php
  lib/modules/eic_overviews/src/OverviewPageListBuilder.php
  lib/modules/eic_overviews/src/OverviewPageViewBuilder.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
Labels: backend

#525 [EICNET-874] chore: Compute reading time in preprocess node
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#528 [EICNET] fix: delete symlinks before creating them
  Makefile
Labels: enhancement

#527 [EICNET-1256]feat: implement delete feature in react
  lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
  lib/themes/eic_community/react/components/Block/ActivityStream/DeleteActivityStream.js
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
  lib/themes/eic_community/react/components/Block/ActivityStream/partials/ResultItemWrapper.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/CommentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DiscussionStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DocumentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/WikiStreamResultItem.js
Labels: backend, frontend

#510 [EICNET-1232]feat: Sort by default on creation date
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
Labels: backend

#531 [EICNET] fix: Enable GD's jpeg support
  docker/php/Dockerfile
Labels: enhancement

#529 [EICNET-1253]fix: Set 5000 as length cause custom widget have labels in value
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
Labels: bug, backend

#532 EICNET-1233: Fixed visibility search sort options arrow.
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/SortOption.js
Labels: frontend, react

#492 EICNET-1178: Show fallback group image in react overview.
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: frontend

#494 added react watcher to general command
  lib/themes/eic_community/package.json
Labels: frontend

#535 [EICNET-1217]fix: add more fields to search in
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
Labels: bug, backend

#534 [EICNET]refactor: replace simple class by just const function
  lib/themes/eic_community/react/components/Block/ActivityStream/DeleteActivityStream.js
  lib/themes/eic_community/react/components/Block/ActivityStream/LoadMore.js
  lib/themes/eic_community/react/components/Block/ActivityStream/partials/ResultItemWrapper.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/CommentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DiscussionStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DocumentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/Footer.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/WikiStreamResultItem.js
Labels: frontend, react

#533 [EICNET-1191]feat: put overviews block in correct group tabs + fix the collapse add items
  config/sync/context.context.group_activity_stream_overviews.yml
  config/sync/context.context.group_files_overviews.yml
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/themes/eic_community/images/sprite/custom/plus.svg
  lib/themes/eic_community/react/Services/CollapseOptions.js
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
Labels: backend, frontend

#503 Feature/eicnet 1196 add storybook styling to group files detail
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/templates/content/node--document--full.html.twig
Labels: backend, frontend

#522 EICNET-1170: Group about page: move the hardcoded text from the theme to the module
  lib/modules/eic_groups/src/Constants/GroupJoiningMethodType.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#506 EICNET-1206: Added storybook styling to group video detail.
  config/sync/core.entity_view_display.node.video.default.yml
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/templates/content/node--video--full.html.twig
Labels: backend, frontend

#537 EICNET-1206: Corrected function name.
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: bug, backend

#540 [EICNET-1211] chore: Display a custom error message for the entity_tree
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
Labels: frontend

#553 EICNET-1344: Fix issue when entity doesn't have a status field.
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
Labels: backend

#555 EICNET-1337: Fix the global overview page IDs.
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
Labels: backend
