Repository EIC-EA/EIC-community-D8, pull requests merged in 2021-11, with the labels that each got.

#755 EICNET-1593: Overview page banner back-end
  config/sync/core.entity_view_display.overview_page.overview_page.default.yml
  lib/modules/eic_overviews/eic_overviews.module
  lib/modules/eic_overviews/src/Entity/OverviewPage.php
  lib/modules/eic_overviews/src/OverviewPageViewBuilder.php
  lib/modules/eic_overviews/templates/overview-page.html.twig
  lib/themes/eic_community/templates/field/field--overview-page--banner-image--full.html.twig
Labels: backend, frontend

#778 [EICNET-1350]feat: Keep same label visibility type
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: backend, frontend, react

#789 EICNET-1602: Fix main menu active trail when viewing group pages
  composer.json
  composer.lock
  composer.patches.json
  config/sync/core.extension.yml
  config/sync/menu_trail_by_path.settings.yml
  config/sync/system.menu.main.yml
  lib/modules/eic_menus/eic_menus.info.yml
  lib/modules/eic_menus/eic_menus.services.yml
  lib/modules/eic_menus/src/EICMenuTrailByPathActiveTrail.php
Labels: backend

#787 EICNET-1601: Increment event files in group file statistics
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#790 [EICNET-1609]feat: implement contact user form + allow config by profile + implment into overview link
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.user.user.field_user_can_contact.yml
  config/sync/field.storage.user.field_user_can_contact.yml
  config/sync/search_api.index.global.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
  lib/modules/eic_private_message/eic_private_message.info.yml
  lib/modules/eic_private_message/eic_private_message.module
  lib/modules/eic_private_message/eic_private_message.permissions.yml
  lib/modules/eic_private_message/eic_private_message.routing.yml
  lib/modules/eic_private_message/src/Constants/PrivateMessage.php
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
  lib/modules/eic_private_message/templates/user-private-message-mail.html.twig
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
Labels: backend, frontend, react

#792 [EICNET]fix: remove bad config eic_search_block
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.search.yml
Labels: backend

#785 EICNET-1223: Also search on gallery media names.
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
Labels: backend

#771 Feature/eicnet 1534 group event overview
  config/sync/context.context.group_events_overviews.yml
  config/sync/eic_groups.group_features.eic_groups_group_events.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_group_events.yml
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupGroupEvents.php
  lib/modules/eic_overviews/eic_overviews.group.permissions.yml
  lib/modules/eic_overviews/eic_overviews.routing.yml
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: backend

#800 EICNET-1534: Fix access to group events overview.
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
Labels: bug, backend

#796 [EICNET-1621] table style
  lib/themes/eic_community/sass/compositions/_table.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/templates/views/views-view-table.html.twig
Labels: frontend

#766 Feature/forms | make a correct layout for add group form
  lib/themes/eic_community/data/form/components/checkbox.data.js
  lib/themes/eic_community/data/form/components/files.data.js
  lib/themes/eic_community/data/form/components/input.data.js
  lib/themes/eic_community/data/form/components/radio.data.js
  lib/themes/eic_community/data/form/components/radioBlock.data.js
  lib/themes/eic_community/data/form/components/select.data.js
  lib/themes/eic_community/data/form/components/textarea.data.js
  lib/themes/eic_community/data/form/group.data.js
  lib/themes/eic_community/data/form/index.js
  lib/themes/eic_community/images/sprite/custom/lock.svg
  lib/themes/eic_community/patterns/components/form/form-file.html.twig
  lib/themes/eic_community/patterns/components/form/form-radio-block.html.twig
  lib/themes/eic_community/patterns/components/form/form-section.html.twig
  lib/themes/eic_community/sass/components/_form.scss
  lib/themes/eic_community/sass/components/_select.scss
  lib/themes/eic_community/styleguide/bundles/forms.stories.js
  lib/themes/eic_community/styleguide/components/form.docs.mdx
  lib/themes/eic_community/styleguide/components/form.stories.js
Labels: frontend

#803 EICNET-1534: Fix GroupEvent for overviews.
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: bug, backend

#802 [EICNET-1623] add empty state in the table
  config/sync/views.view.group_pending_members.yml
Labels: backend

#794 [EICNET]feat: Add sorting relevance
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_members_overviews.yml
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Search/Sources/StorySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
Labels: backend

#805 Feature/eicnet 1641 contact form
  lib/themes/eic_community/sass/components/_form.scss
Labels: frontend

#801 EICNET-1531: Add Event CT to default content.
  lib/modules/eic_default_content/src/Generator/GroupGenerator.php
Labels: enhancement, backend

#811 [EICNET-1651] Feat: storybook add "manage" in collapsible options
  lib/themes/eic_community/patterns/compositions/collapsible-options.html.twig
  lib/themes/eic_community/sass/compositions/_collapsible-options.scss
  lib/themes/eic_community/styleguide/compositions/collapsible-options.stories.js
Labels: frontend

#813 [EICNET-1658] FEAT: new style for notification
  lib/themes/eic_community/patterns/compositions/notification-banner.html.twig
  lib/themes/eic_community/sass/compositions/_notification-banner.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/templates/status/status-messages.html.twig
Labels: frontend

#817 [EICNET-1532]feat: glue group detail page in back-end
  config/sync/context.context.group_event_homepage.yml
  config/sync/context.context.group_group_homepage.yml
  config/sync/group.content_type.group_content_type_dd4142e7f0cf7.yml
  lib/themes/eic_community/eic_community.theme
  lib/themes/eic_community/patterns/components/event-infos.html.twig
  lib/themes/eic_community/patterns/compositions/group/group-event.full.html.twig
  lib/themes/eic_community/styleguide/bundles/group.stories.js
Labels: backend, react

#809 [EICNET]fix: check if target_bundles is not null
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
Labels: backend

#808 EICNET-1546: As a SA/SCM I must provide a reason to block a group
  config/sync/core.entity_form_display.flagging.block_group.default.yml
  config/sync/core.entity_view_display.flagging.block_group.default.yml
  config/sync/field.field.flagging.block_group.field_block_reason.yml
  config/sync/field.storage.flagging.field_block_reason.yml
  config/sync/flag.flag.block_group.yml
  config/sync/system.action.flag_action.block_group_flag.yml
  config/sync/system.action.flag_action.block_group_unflag.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/views.view.admin_blocked_entities.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.permissions.yml
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Access/EntityBlockAccessChecker.php
  lib/modules/eic_flags/src/BlockFlagTypes.php
  lib/modules/eic_flags/src/Form/EntityBlockForm.php
  lib/modules/eic_flags/src/Routing/EntityBlockRouteProvider.php
  lib/modules/eic_flags/src/Service/EntityBlockHandler.php
  lib/modules/eic_groups/eic_groups.links.task.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/GroupsModerationHelper.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#810 EICNET-1506: As a TU, I want to see a message on blocked groups (Part 2)
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
Labels: bug, backend

#812 [EICNET-1647] I want an option on group invitation so that I can resend an invitation to a user
  config/sync/core.entity_form_display.group_content.group-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.group-group_invitation.default.yml
  config/sync/field.field.group_content.group-group_invitation.field_invitation_counter.yml
  config/sync/field.storage.group_content.field_invitation_counter.yml
  config/sync/group.content_type.group-group_invitation.yml
  config/sync/views.view.group_invitations.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Controller/GroupMembershipInvitationController.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/views/field/ResendInvitation.php
  lib/themes/eic_community/includes/preprocess/form/input--search.inc
Labels: backend

#824 EICNET-1652: Homepage welcome message for logged in users
  config/sync/context.context.homepage.yml
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php
  lib/themes/eic_community/includes/preprocess/theme/eic-content-actions.inc
  lib/themes/eic_community/templates/navigation/eic-content-actions.html.twig
Labels: backend

#815 [EICNET] Request group join | FEAT: change style of form actions
  lib/themes/eic_community/sass/components/_form.scss
Labels: frontend

#828 [EICNET]feat: implement banner image in back template
  config/sync/core.entity_view_display.overview_page.overview_page.default.yml
  lib/modules/eic_overviews/eic_overviews.module
  lib/modules/eic_overviews/templates/overview-page.html.twig
  lib/modules/eic_topics/eic_topics.module
  lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics.html.twig
Labels: backend

#807 [EICNET-1608]feat: Create new route to contact multiple users in a group
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
  lib/modules/eic_private_message/eic_private_message.permissions.yml
  lib/modules/eic_private_message/eic_private_message.routing.yml
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
  lib/modules/eic_private_message/src/Plugin/EntityReferenceSelection/MembershipSelection.php
  lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php
Labels: backend

#806 [EICNET-1591] fix: An endpoint archival/delete requests
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Access/RequestAccessCheck.php
  lib/modules/eic_flags/src/Controller/RequestEndpointController.php
  lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
  lib/modules/eic_flags/src/Routing/EntityRequestRouteProvider.php
  lib/modules/eic_flags/src/Service/HandlerInterface.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupRequest.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: bug, backend

#819 EICNET-1575: Group admin view rework
  config/sync/views.view.admin_groups.yml
Labels: enhancement, backend

#820 EICNET-1679: Create Events admin view
  config/sync/views.view.admin_groups.yml
  lib/modules/eic_admin/eic_admin.links.menu.yml
Labels: enhancement, backend

#780 EICNET-1581: Issue when generating group content URLs
  config/sync/pathauto.pattern.wiki_pages.yml
  config/sync/pathauto.settings.yml
  lib/modules/eic_content/modules/eic_content_book/eic_content_book.module
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php
  lib/modules/eic_groups/src/Hooks/GroupTokens.php
Labels: bug, backend

#814 EICNET-1508: Email notification for a group transitioned to blocked
  config/sync/core.entity_form_display.message.notify_entity_blocked.default.yml
  config/sync/core.entity_view_display.message.notify_entity_blocked.default.yml
  config/sync/core.entity_view_display.message.notify_entity_blocked.mail_body.yml
  config/sync/core.entity_view_display.message.notify_entity_blocked.mail_subject.yml
  config/sync/field.field.message.notify_entity_blocked.field_event_executing_user.yml
  config/sync/field.field.message.notify_entity_blocked.field_referenced_flag.yml
  config/sync/language/en/message.template.notify_entity_blocked.yml
  config/sync/message.template.notify_entity_blocked.yml
  lib/modules/eic_messages/eic_messages.services.yml
  lib/modules/eic_messages/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_messages/src/Service/EntityBlockMessageCreator.php
  lib/modules/eic_messages/src/Util/NotificationMessageTemplates.php
Labels: enhancement, backend

#829 [EICNET]feat: Add permissions for scm group members + add cache dependency on block
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
Labels: backend

#831 EICNET-1506: As a TU, I want to see a message on blocked groups (Part 3)
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: bug, backend

#833 EICNET-1645: TU (as GM or GO) only sees Overview, About & wiki page of the group (Bugfix)
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
Labels: bug, backend

#834 ECINET-XXXX: Fix duplciate event preprocess function.
  lib/themes/eic_community/eic_community.theme
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/events.inc
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: bug, backend

#835 [EICNET-1611]feat: Handle inbetween, before-after, ... date-filter query range
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: backend

#838 EICNET-1656: Empty states for enabled empty blocks
  config/sync/context.context.group_event_homepage.yml
  config/sync/context.context.homepage.yml
  config/sync/views.view.group_discussions.yml
  config/sync/views.view.group_documents.yml
  config/sync/views.view.group_related_groups.yml
  config/sync/views.view.group_related_news_stories.yml
  lib/themes/eic_community/templates/views/views-view--featured-content-collection.html.twig
Labels: backend

#837 EICNET-XXXX: Add event node type and use bundle label.
  lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php
Labels: backend

#822 Feature/eicnet 1686 group sharing
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/patterns/compositions/editorial-header.html.twig
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/_wtShare.scss
  lib/themes/eic_community/templates/blocks/eic-group-header-block.html.twig
  lib/themes/eic_community/templates/content/node--gallery--full.html.twig
  lib/themes/eic_community/templates/content/node--story--full.html.twig
  lib/themes/eic_community/templates/content/node--video--full.html.twig
  lib/themes/eic_community/templates/oe_webtools/oe-webtools-social-share.html.twig
Labels: frontend

#848 EICNET-XXXX: Group overview events list
  config/sync/context.context.group_group_homepage.yml
  config/sync/views.view.group_events.yml
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
Labels: enhancement, backend

#845 [EICNET-1623] Feat: add more padding on members tables
  lib/themes/eic_community/sass/compositions/_table.scss
Labels: frontend

#847 [EICNET-1702] Fix: height of the teaser groups when title take 2 lines
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#654 Feature/eicnet 1199 add slider to gallery detail page
  .gitignore
  lib/themes/eic_community/data/gallery.data.js
  lib/themes/eic_community/eic_community.libraries.yml
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/patterns/compositions/filelist/filelist.gallery.html.twig
  lib/themes/eic_community/react/components/Block/Gallery/FileInfo.jsx
  lib/themes/eic_community/react/components/Block/Gallery/Gallery.jsx
  lib/themes/eic_community/react/components/Block/Gallery/entrypoint.js
  lib/themes/eic_community/sass/components/_gallery.scss
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/styleguide/compositions/gallery.stories.js
  lib/themes/eic_community/styleguide/react/gallery.stories.js
  lib/themes/eic_community/templates/content/node--gallery--full.html.twig
  lib/themes/eic_community/webpack.mix.js
Labels: backend, frontend

#853 [EICNET-1493]feat: put an url on the user teaser for group
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#857 [EICNET-1698]feat: Check if results has been initiated before showing no results message
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: react

#858 EICNET-1679: Fix Admin Events page title
  config/sync/views.view.admin_groups.yml
Labels: bug, backend

#859 EICNET-1373: Change "invite member" default settings in group creation form (Rework)
  lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
Labels: backend

#873 [EICNET]feat: Set sidebar on the right and banner outside content region for Topic
  lib/modules/eic_topics/eic_topics.module
  lib/themes/eic_community/templates/layout/page--taxonomy--term.html.twig
  lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics.html.twig
Labels: backend

#877 Feature/eicnet 1711 topic detail page fe
  config/sync/context.context.taxonomy_topics_detail_page.yml
  lib/modules/eic_topics/eic_topics.module
  lib/themes/eic_community/data/featured-content-collection/companies.data.js
  lib/themes/eic_community/data/featured-content-collection/index.js
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/blocks/block--topics-statistics.inc
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/patterns/compositions/activity-stream.html.twig
  lib/themes/eic_community/patterns/compositions/editorial-overview.html.twig
  lib/themes/eic_community/patterns/compositions/featured-content-collection.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.stats.html.twig
  lib/themes/eic_community/sass/compositions/_featured-content-collection.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/sass/compositions/_topic.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/utils/_mixins.scss
  lib/themes/eic_community/styleguide/bundles/organisation.stories.js
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
  lib/themes/eic_community/templates/blocks/topics-statistics-block.html.twig
Labels: backend, frontend

#881 [EICNET] Fix: add padding on the form
  lib/themes/eic_community/sass/components/_form.scss
Labels: frontend

#852 Feature/eicnet 1573 topics activity stream
  config/sync/context.context.group_activity_stream_overviews.yml
  config/sync/context.context.taxonomy_topics_detail_page.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
  lib/modules/eic_search/eic_search.routing.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#884 Feature/eicnet 1711 topic detail page fe
  config/sync/context.context.taxonomy_topics_detail_page.yml
  config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/templates/content/node--discussion--teaser.html.twig
  lib/themes/eic_community/templates/content/node--document--teaser.html.twig
  lib/themes/eic_community/templates/content/node--event--teaser.html.twig
  lib/themes/eic_community/templates/content/node--gallery--teaser.html.twig
  lib/themes/eic_community/templates/content/node--story--teaser.html.twig
  lib/themes/eic_community/templates/content/node--video--teaser.html.twig
  lib/themes/eic_community/templates/content/node--wiki-page--teaser.html.twig
  lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics.html.twig
  lib/themes/eic_community/templates/views/views-view--featured-content-collection.html.twig
  lib/themes/eic_community/templates/views/views-view--featured-contributors.html.twig
  lib/themes/eic_community/templates/views/views-view--featured-topics.html.twig
Labels: backend, frontend

#886 [EICNET] Feat: Topics overview in storybook
  lib/themes/eic_community/patterns/compositions/topic/topic.details.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.item.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.list.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.subitem.html.twig
  lib/themes/eic_community/sass/compositions/_topic.scss
  lib/themes/eic_community/snippets/index.js
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
  lib/themes/eic_community/styleguide/compositions/topics.docs.mdx
  lib/themes/eic_community/styleguide/compositions/topics.stories.js
Labels: frontend

#883 Feature/eicnet group review message
  lib/themes/eic_community/templates/layout/page--group--review.html.twig
Labels: frontend

#890 [EICNET-1719]chore: Refactor the way we get global overview page
  config/sync/core.entity_form_display.overview_page.overview_page.default.yml
  config/sync/core.entity_view_display.overview_page.overview_page.default.yml
  config/sync/field.field.overview_page.overview_page.field_overview_id.yml
  config/sync/field.storage.overview_page.field_overview_id.yml
  lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_overviews/eic_overviews.module
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: enhancement, backend

#898 [EICNET-1669] fix: Use entity_tree field type for group topics
  config/sync/core.entity_form_display.group.group.default.yml
Labels: enhancement, backend

#888 [EICNET] Feat: add "esc" event listener on the modal to close it
  lib/themes/eic_community/react/components/Block/ShareModal/components/ShareModal.js
Labels: frontend, react

#903 [EICNET-1597]chore: Re-do the way we build prefiltered query params
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/SearchHelper.php
  lib/modules/eic_topics/eic_topics.module
  lib/modules/eic_topics/src/TopicsManager.php
Labels: enhancement, backend

#887 [EICNET]feat: Add state label of the event in group overview
  config/sync/context.context.group_events_overviews.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.event.field_vocab_geo.yml
  lib/modules/eic_events/eic_events.info.yml
  lib/modules/eic_events/eic_events.module
  lib/modules/eic_events/eic_events.services.yml
  lib/modules/eic_events/src/Commands/UpdateSolrEventsCommands.php
  lib/modules/eic_events/src/Constants/Event.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#909 [EICNET-1695]fix: make file label clickable
  lib/themes/eic_community/patterns/components/filelist.html.twig
  lib/themes/eic_community/sass/components/_filelist.scss
Labels: frontend

#910 [EICNET-1696]fix: Separate filename by comma
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
Labels: frontend, react

#893 [EICNET-1671] chore: Add edit/revert story permissions for SA/SCM
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: bug, backend

#889 [EICNET-1683] add share icon in group flags
  lib/themes/eic_community/templates/oe_webtools/oe-webtools-social-share.html.twig
Labels: frontend

#882 [EICNET] fix: Group groups by bundle
  README.md
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/modules/eic_groups/src/Controller/GroupMembershipInvitationController.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/react/components/Block/ShareModal/components/ShareModal.js
  lib/themes/eic_community/react/components/Block/ShareModal/index.js
  lib/themes/eic_community/templates/flag/eic-flag-count.html.twig
  scripts/install.sh
Labels: bug, enhancement, backend, frontend

#894 [EICNET-1676] chore: Add the manage archival/deletion requests permission to SCM
  config/sync/user.role.content_administrator.yml
Labels: enhancement, backend

#904 [EICNET-1709] chore: Allow delete/archival requests for draft groups
  lib/modules/eic_groups/src/Access/FlagRequestAccessCheck.php
Labels: enhancement, backend

#902 Feature/eicnet 1716 topic term teaser
  config/sync/views.view.taxonomy.yml
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_overviews/eic_overviews.routing.yml
  lib/modules/eic_overviews/src/Controller/TaxonomyOverviewController.php
  lib/modules/eic_statistics/eic_statistics.services.yml
  lib/modules/eic_statistics/src/StatisticsHelper.php
  lib/modules/eic_user/eic_user.services.yml
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/includes/alter/theme_suggestions/taxonomy.inc
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics--full.html.twig
  lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics--teaser.html.twig
Labels: backend, frontend

#892 Feature/eicnet 1715 topics overview page
  lib/modules/eic_overviews/src/Controller/TaxonomyOverviewController.php
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
Labels: backend

#899 [EICNET] add image empty state
  lib/themes/eic_community/patterns/compositions/topic/topic.overview.subitem.html.twig
  lib/themes/eic_community/sass/compositions/_topic.scss
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
Labels: frontend

#917 [EICNET] Fix topic details stats keys name
  lib/themes/eic_community/patterns/compositions/topic/topic.stats.html.twig
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
Labels: frontend

#911 [EICNET-1700]feat: Add cache tags to comments block + condition to hide if comment system not open
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_view_display.node.document.default.yml
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: backend

#906 [EICNET-1694]fix: ADd correct permission + icon state for highlight content
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
Labels: backend, frontend, react

#913 [EICNET-1674]feat: Re-index dependant entities of group membership group content
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
Labels: backend, frontend, react

#896 [EICNET] fix: Local setup dependencies
  lib/modules/eic_statistics/eic_statistics.services.yml
  lib/modules/eic_statistics/src/StatisticsHelper.php
  lib/modules/oec_group_flex/oec_group_flex.services.yml
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
Labels: bug, backend

#922 Feature/eicnet 1732 maintainance update
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.node.book.default.yml
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_form_display.paragraph.contributor.default.yml
  config/sync/core.entity_form_display.paragraph.quote.default.yml
  config/sync/core.entity_form_display.paragraph.text_and_media_content.default.yml
  config/sync/core.entity_view_display.node.book.default.yml
  config/sync/core.entity_view_display.node.book.teaser.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/core.entity_view_display.node.page.full.yml
  config/sync/core.entity_view_display.node.page.teaser.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
Labels: backend

#923 [EICNET]fix: do not use Commands in namespace but Services
  lib/modules/eic_events/eic_events.services.yml
  lib/modules/eic_events/src/Services/UpdateSolrEvents.php
Labels: backend

#920 EICNET-1642: Modify user messages for the user contact form.
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: enhancement

#926 EICNET-1733: Define different set of group features depending on the group type.
  config/sync/oec_group_features.group_type_features.event.yml
  config/sync/oec_group_features.group_type_features.group.yml
  lib/modules/oec_group_features/config/schema/oec_group_features.group_type_features.schema.yml
  lib/modules/oec_group_features/oec_group_features.module
  lib/modules/oec_group_features/oec_group_features.services.yml
  lib/modules/oec_group_features/src/GroupFeatureHelper.php
  lib/modules/oec_group_features/src/Hooks/EntityOperations.php
Labels: backend

#912 EICNET-286: Allow SA/SCM users to edit custom blocks
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#914 EICNET-1506: Show group under review message (cache issues)
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#915 EICNET-1725: Error when adding a topic of interest in user profile
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
Labels: bug, backend

#924 EICNET-1510: Email notification for a group transitioned to unblocked
  config/sync/core.entity_form_display.message.notify_content_status_changed.default.yml
  config/sync/core.entity_view_display.message.notify_content_status_changed.default.yml
  config/sync/core.entity_view_display.message.notify_content_status_changed.mail_body.yml
  config/sync/core.entity_view_display.message.notify_content_status_changed.mail_subject.yml
  config/sync/field.field.message.notify_content_status_changed.field_entity_prev_status_label.yml
  config/sync/field.field.message.notify_content_status_changed.field_entity_status_label.yml
  config/sync/field.field.message.notify_content_status_changed.field_entity_url.yml
  config/sync/field.field.message.notify_content_status_changed.field_message_subject.yml
  config/sync/field.field.message.notify_content_status_changed.field_referenced_entity_label.yml
  config/sync/field.storage.message.field_entity_prev_status_label.yml
  config/sync/field.storage.message.field_entity_status_label.yml
  config/sync/field.storage.message.field_entity_url.yml
  config/sync/language/en/message.template.notify_content_status_changed.yml
  config/sync/message.template.notify_content_status_changed.yml
  lib/modules/eic_messages/src/Hooks/EntityOperations.php
Labels: enhancement, backend

#932 EICNET-1673: Fix issue with wrong visibility for stories/news.
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#938 [EICNET]chore: fix dependencies
  lib/modules/eic_events/eic_events.info.yml
  lib/modules/eic_statistics/eic_statistics.info.yml
  lib/modules/eic_statistics/eic_statistics.services.yml
  lib/modules/eic_statistics/src/StatisticsHelper.php
Labels: backend

#905 [EICNET] Fix color for custom group's tags
  lib/themes/eic_community/sass/components/_tag.scss
Labels: frontend

#942 [EICNET] Convert non-standard reverse proxy headers to standard ones
  docker/nginx/servers/default.conf
  lib/modules/eic_helper/eic_helper.services.yml
  lib/modules/eic_helper/src/StackMiddleware/HeaderMapper.php
  web/sites/default/default.settings.local.php
Labels: enhancement, backend

#925 [EICNET] align the style with the figma
  lib/themes/eic_community/patterns/components/attachment.html.twig
  lib/themes/eic_community/sass/components/_attachment.scss
Labels: frontend

#921 Features/eicnet correct homepage styling
  lib/themes/eic_community/data/bulletin-block.data.js
  lib/themes/eic_community/sass/compositions/_card-wrapper.scss
  lib/themes/eic_community/sass/compositions/_fact-figures-wrapper.scss
  lib/themes/eic_community/styleguide/pages/homepage.stories.js
Labels: frontend

#908 [EICNET] Fix label style for media field in a form
  lib/themes/eic_community/sass/components/_form.scss
Labels: frontend

#652 EICNET-1214: Overview empty state
  lib/themes/eic_community/.DS_Store
  lib/themes/eic_community/data/.DS_Store
  lib/themes/eic_community/images/sprite/custom/arrow.svg
  lib/themes/eic_community/mails/mail-dist/.DS_Store
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/patterns/compositions/activity-stream.html.twig
  lib/themes/eic_community/patterns/compositions/discussion/discussion.overview.html.twig
  lib/themes/eic_community/patterns/compositions/event/event.overview.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.full--discussion.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.full--document.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.full--member.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.overview.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.overview.html.twig
  lib/themes/eic_community/patterns/compositions/organisation/organisation.overview.html.twig
  lib/themes/eic_community/patterns/compositions/project/project.overview.html.twig
  lib/themes/eic_community/patterns/compositions/story/story.overview.html.twig
  lib/themes/eic_community/patterns/compositions/teaser-overview.html.twig
  lib/themes/eic_community/patterns/pages/search/search.html.twig
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
  lib/themes/eic_community/react/components/Block/Gallery/.DS_Store
  lib/themes/eic_community/sass/.DS_Store
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
  lib/themes/eic_community/sass/compositions/_teaser-overview.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/compositions/activity-stream.docs.mdx
  lib/themes/eic_community/styleguide/compositions/teaser-overview.docs.mdx
Labels: frontend

#928 [EICNET-1729]feat: Invite multiple users (platform/external)
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserInvitesListSourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/Hooks/FormAlter.php
  lib/themes/eic_community/react/components/Field/EntityTree/Result/Search.js
  lib/themes/eic_community/react/components/Field/EntityTree/entrypoint.js
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
  lib/themes/eic_community/sass/admin/_entity_tree_field.scss
Labels: enhancement, backend, frontend, react

#929 Bugfix/20211125 ludo
  composer.lock
  composer.patches.json
  config/sync/group.role.event-anonymous.yml
  config/sync/group.role.event-outsider.yml
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: bug, backend

#937 [EICNET] add image empty state on all member teaser
  lib/themes/eic_community/patterns/compositions/member-information-block.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig
  lib/themes/eic_community/sass/compositions/_contact-information-block.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/bundles/member.stories.js
Labels: frontend

#931 [EICNET] add click on the teasers image
  lib/themes/eic_community/data/teaser/group.data.js
  lib/themes/eic_community/data/teaser/project.data.js
  lib/themes/eic_community/patterns/compositions/featured-content-grid.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/project/project.teaser.html.twig
Labels: frontend

#901 [EICNET-1692] fix: Remove the url alias field from the join form
  config/sync/core.entity_form_display.group_content.group-group_membership.default.yml
Labels: enhancement, backend

#955 [EICNET] refactor comments in react
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: react
