Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-10, with the labels that each got.

#1996 EICNET-2841: Downgrade smtp module to version 1.0 until this issue is…
  composer.json
  composer.lock
Labels: backend

#1999 Feature/eicnet 2870 video thumbnail
  config/sync/field.field.node.video.field_image.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVideo.php
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
Labels: backend

#2001 Feature/eicnet 1451 general maintenance fixes
  composer.json
  composer.lock
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1994 EICNET-2697: Do not link users to their profile for anonymous users.
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#1998 Feature/eicnet 2807 invitee email access
  config/sync/user.role.trusted_user.yml
  config/sync/views.view.group_invitations.yml
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
Labels: backend

#2000 EICNET-2880: Fix Topics breadrcumb.
  lib/modules/eic_topics/eic_topics.services.yml
  lib/modules/eic_topics/src/TermBreadcrumbBuilder.php
Labels: backend

#1983 EICNET-2823: Don't assign roles upon cas user registration.
  config/sync/cas.settings.yml
Labels: backend

#1981 Feature/eicnet 2853 group permission revisions
  composer.patches.json
  lib/modules/eic_admin/src/Form/UpdateAllGroupPermissionsForm.php
  lib/modules/eic_deploy/eic_deploy.module
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/eic_groups.install.inc
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/oec_group_features/src/GroupFeatureHelper.php
  lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
Labels: backend

#1993 [EICNET-2879]fix: place correctly the recommend action as second option without removing like
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
Labels: backend

#2010 [EICNET-2712]fix: remove unused required svg call
  lib/themes/eic_community/sass/components/_drupal-webforms.scss
Labels: bug, frontend

#2007 EICNET-2885: On user profile edition Country should be empty not afghanistan by default
  composer.lock
  composer.patches.json
Labels: bug, backend

#2004 EICNET-2488: Fix epty items for Event GT.
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: backend

#2008 Feature/eicnet 2440 icons path fix
  lib/modules/eic_user/templates/account-header-block.html.twig
  lib/themes/eic_community/patterns/compositions/featured-content-grid.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
  lib/themes/eic_community/templates/group/group--group--teaser.html.twig
  lib/themes/eic_community/templates/paragraphs/paragraph--contributor.html.twig
Labels: backend

#2011 EICNET-2846: Enable the media_embed plugin for entity_usage.
  config/sync/entity_usage.settings.yml
Labels: backend

#2013 Feature/eicnet 2878 contact form
  config/sync/contact.form.contact_form.yml
  lib/modules/eic_contact/eic_contact.module
  lib/modules/eic_contact/eic_contact.services.yml
  lib/modules/eic_contact/src/Constants/ContactFormIds.php
  lib/modules/eic_contact/src/ContactFormEditForm.php
  lib/modules/eic_contact/src/ContactMailHandler.php
Labels: backend

#2014 EICNET-2856: Take into account the user of group prefix in the alias migration
  lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
Labels: backend, migration

#2015 EICNET-2438: Always display News and Events views in Organisation GT.
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
Labels: backend

#2016 EICNET-2890: Fix missing DependencySerializationTrait.
  lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
Labels: backend

#2017 EICNET-1138: Change the link to help and guidance.
  lib/modules/eic_content/src/Constants/HelpAndGuidance.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
Labels: backend

#2005 [EICNET-2888]fix: Set OR operator for certain facet fields
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#2006 [EICNET-2830]fix: Allow trusted user to create tag on fly
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: backend

#2020 Feature/eicnet 2894 fix notification links
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Controller/UserMySettingsRedirectController.php
  lib/themes/eic_community/includes/preprocess/mail/mail.inc
  lib/themes/eic_community/mails/mail-dist/digest.html
  lib/themes/eic_community/mails/mail-dist/header_footer.html
  lib/themes/eic_community/mails/mail-dist/layout.html
  lib/themes/eic_community/templates/mimemail/mimemail-message.html.twig
Labels: backend

#2018 EICNET-2882: Remove obsolete News group menu items.
  lib/modules/eic_groups/eic_groups.install
Labels: backend

#2022 EICNET-2745: Closed joining method for events (Rework)
  config/sync/group.type.event.yml
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
Labels: enhancement, backend

#2025 EICNET-2771: Fix uninitialised variables on global overviews.
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
Labels: backend

#2002 Feature/eicnet 2722 flag access check
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Plugin/Flag/EntityFlagType.php
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_flags/src/Service/BlockRequestHandler.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_moderation/eic_moderation.services.yml
  lib/modules/eic_moderation/src/ModerationHelper.php
  lib/modules/eic_recommend_content/eic_recommend_content.services.yml
  lib/modules/eic_recommend_content/src/Access/RecommendContentAccessCheck.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/common.inc
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: backend

#2029 EICNET-2433: Empty state of [My settings][Email notifications][Your %group_type% notifications] missing
  lib/themes/eic_community/react/components/Block/NotifManagement/index.js
Labels: bug, frontend

#2027 EICNET-2637: When going to the wiki tab inside a global event the breadcrumbs say group
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: bug, backend

#2026 EICNET-2761: Add button to create discussion at the dicsussion level
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
Labels: bug, backend

#2032 [EICNET-2368]chore: Display visibility label for events
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
Labels: backend, frontend

#2035 [EICNET-2620]feat: make chip message for comment translatable
  lib/modules/eic_content/src/Services/EntityTreeManager.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: backend, react

#2028 EICNET-2753: Remove email from entity user reference view.
  config/sync/views.view.entity_reference_user.yml
Labels: backend

#2034 [EICNET-2859]fix: show nested menu on mobile
  lib/themes/eic_community/sass/compositions/_mainmenu.scss
Labels: frontend

#2031 [EICNET-2748]fix: remove sticky position
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
Labels: enhancement, frontend

#2030 [EICNET-1723]fix: fix link cursor
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
Labels: bug, frontend

#2033 EICNET-2898: Validate user entity and send out custom message if not valid.
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResourceBase.php
Labels: backend

#2037 EICNET-XXXX: chore: Fix missing dependency on install.
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/BlockRequestHandler.php
Labels: backend

#2036 Feature/eicnet 2811 anonymous invitations
  config/sync/group.content_type.event-group_invitation.yml
  config/sync/group.content_type.group-group_invitation.yml
  config/sync/group.content_type.organisation-group_invitation.yml
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/src/Controller/UserMyInvitationsController.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/Hooks/UserTokens.php
Labels: backend

#2024 EICNET-2758: [Event] No one should be allowed to comment on a draft story
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_moderation/src/ModerationHelper.php
  lib/modules/eic_moderation/src/Service/ContentModerationManager.php
Labels: bug, backend

#2038 EICNET-2899: contact form - sent mails - the reply message from is missing some information
  composer.lock
  composer.patches.json
  lib/modules/eic_contact/eic_contact.module
Labels: bug, backend

#2039 EICNET-2746: Relabel references to "group" with neutral labels
  config/sync/eic_admin.action_forms.group_membership_leave.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
Labels: bug, backend

#2042 EICNET-1921: Activity stream shows undefined link for deleted content
  lib/modules/eic_messages/eic_messages.install
  lib/modules/eic_messages/eic_messages.install.inc
  lib/modules/eic_messages/src/Hooks/EntityOperations.php
Labels: bug, backend

#2045 EICNET-2901: Views count in stories not working properly
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessor.php
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessorInterface.php
  lib/modules/eic_statistics/src/Hooks/CronOperations.php
  lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
  lib/modules/eic_statistics/src/StatisticsHelper.php
Labels: bug, backend

#2051 EICNET-2876: Group description header read more anchor is not working
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/patterns/compositions/extended-list/extended-list-item.html.twig
Labels: bug, backend, frontend

#2052 EICNET-2074: Improve method to get group content from entity
  config/sync/context.context.book_pages.yml
  config/sync/context.context.group_wiki_page.yml
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/Preprocess.php
  lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php
  lib/modules/eic_content/src/EICContentHelper.php
  lib/modules/eic_content/src/EICContentHelperInterface.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Hooks/EntityAdminUpdateNotifier.php
  lib/modules/eic_messages/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Service/CommentMessageCreator.php
Labels: enhancement, backend
