Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-02, with the labels that each got.

#1111 EICNET-2003: Group creation status draft banner improvements
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-moderated-message-box.inc
  lib/themes/eic_community/templates/blocks/eic-group-moderated-message-box.html.twig
Labels: bug, backend

#1108 Feature/eicnet 1785 membership webservice
  config/sync/rest.resource.eic_webservices_group_membership.yml
  config/sync/user.role.service_authentication.yml
  lib/modules/eic_events/src/Constants/Event.php
  lib/modules/eic_groups/modules/eic_organisations/src/Constants/Organisations.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/MembershipResource.php
Labels: backend

#1109 EICNET-873: Regression issues in group about page
  lib/themes/eic_community/templates/group/group--group--about-page.html.twig
Labels: bug, backend

#1096 EICNET-1858: Group ownership transfer confirmation improvements
  composer.lock
  composer.patches.json
  config/sync/context.context.group_content_global.yml
  config/sync/core.entity_form_display.message.notify_transfer_owner_req_cancel.default.yml
  config/sync/core.entity_view_display.message.notify_transfer_owner_req_cancel.default.yml
  config/sync/core.entity_view_display.message.notify_transfer_owner_req_cancel.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transfer_owner_req_cancel.mail_subject.yml
  config/sync/field.field.message.notify_transfer_owner_req_cancel.field_entity_type.yml
  config/sync/field.field.message.notify_transfer_owner_req_cancel.field_entity_url.yml
  config/sync/field.field.message.notify_transfer_owner_req_cancel.field_referenced_entity_label.yml
  config/sync/field.field.message.notify_transfer_owner_req_cancel.field_referenced_flag.yml
  config/sync/language/en/message.template.notify_new_transfer_owner_req.yml
  config/sync/language/en/message.template.notify_transfer_owner_req_cancel.yml
  config/sync/message.template.notify_new_transfer_owner_req.yml
  config/sync/message.template.notify_transf_owner_expire_admin.yml
  config/sync/message.template.notify_transf_owner_expire_owner.yml
  config/sync/message.template.notify_transfer_owner_req_cancel.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Access/CancelRequestAccessCheck.php
  lib/modules/eic_flags/src/Form/NewRequestForm.php
  lib/modules/eic_flags/src/Form/RequestCancelForm.php
  lib/modules/eic_flags/src/Form/RequestCloseForm.php
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_flags/src/Hooks/FlagTokens.php
  lib/modules/eic_flags/src/RequestStatus.php
  lib/modules/eic_flags/src/RequestTypes.php
  lib/modules/eic_flags/src/Routing/EntityRequestRouteProvider.php
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/HandlerInterface.php
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/src/Plugin/views/field/TransferOwnershipStatus.php
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: enhancement, backend

#1124 Feature/eicnet 1481 event webservice
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.role.service_authentication.yml
  config/sync/workflows.workflow.groups.yml
  lib/modules/eic_webservices/src/Controller/SubRequestController.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/GroupResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/MembershipResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php
Labels: backend

#1126 [EICNET] Author image empty state
  lib/themes/eic_community/react/components/Block/ActivityStream/partials/ResultItemWrapper.js
  lib/themes/eic_community/sass/components/_author.scss
Labels: frontend, react

#1116 EICNET-2014: Allow SA/SCM to sort archival and delete request in administration view
  lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
Labels: enhancement, backend

#1118 EICNET-1825: Masquerade a user
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#1129 EICNET-1573: Add missing fields to gallery and video activity stream messages.
  config/sync/core.entity_form_display.message.stream_gallery_insert_update.default.yml
  config/sync/core.entity_form_display.message.stream_video_insert_update.default.yml
  config/sync/core.entity_view_display.message.stream_gallery_insert_update.default.yml
  config/sync/core.entity_view_display.message.stream_video_insert_update.default.yml
  config/sync/field.field.message.stream_gallery_insert_update.field_entity_type.yml
  config/sync/field.field.message.stream_video_insert_update.field_entity_type.yml
Labels: bug, backend

#1137 EICNET-1825: Masquerade a user (rework)
  composer.lock
  composer.patches.json
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: bug, backend

#1135 EICNET-1896: Color group states on homepage
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#1140 EICNET-2064: As a non logged in (anonymous user) I cannot access wiki pages on the upper level
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/EventSubscriber/BookPageRedirectSubscriber.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
Labels: bug, backend

#1141 [EICNET-1847] cancel the jump when we use a filter on mobile
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CollapsedOptions.js
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js
Labels: frontend, react

#1134 Feature/eicnet 1898 global search
  lib/themes/eic_community/sass/compositions/_mainmenu.scss
  lib/themes/eic_community/templates/navigation/menu--main.html.twig
Labels: frontend

#1131 [EICNET-1907] change image style - change tag style
  lib/themes/eic_community/sass/compositions/_organisation.scss
  lib/themes/eic_community/styleguide/bundles/organisation.stories.js
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: frontend

#1130 [EICNET-1569] restyle correctly related discussion in topics
  lib/themes/eic_community/data/featured-content-collection/discussion.data.js
  lib/themes/eic_community/sass/compositions/_discussion-thread.scss
Labels: frontend

#1115 [EICNET-1885]feat: Check if feature is enabled for current organisation to show/hide blocks
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: backend

#1055 [EICNET-1929] wiki pages front end
  .env.docker
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-groups-wiki-book-navigation.inc
  lib/themes/eic_community/js/components/drupal.navigation-list.js
  lib/themes/eic_community/patterns/components/navigation-list/navigation-list-items.html.twig
  lib/themes/eic_community/patterns/components/navigation-list/navigation-list.html.twig
  lib/themes/eic_community/sass/components/_navigation-list.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/templates/blocks/block--eic-groups-wiki-book-navigation.html.twig
  lib/themes/eic_community/templates/content/node--wiki-page--full.html.twig
  lib/themes/eic_community/templates/layout/page--node--wiki-page.html.twig
Labels: frontend

#1099 [EICNET-1782] rework design of ecl-teaser story
  config/sync/search_api.index.global.yml
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_search/eic_search.info.yml
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Collector/DocumentProcessorCollector.php
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessor.php
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessorInterface.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDocument.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupEvent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorNewsStory.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVisibility.php
  lib/modules/eic_search/src/Search/Sources/NewsSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1132 Feature/eicnet 1661 topic detail page rework
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/compositions/featured-contributors.stories.js
  lib/themes/eic_community/templates/views/views-view--featured-contributors.html.twig
Labels: backend, frontend

#1143 EICNET-2063: As non logged in user looking at a wiki page gives CTA which overlaps with the wiki itself
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/field.field.node.wiki_page.field_comments.yml
Labels: backend

#1148 EICNET-1896: Color group states on homepage (Custom restricted groups)
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#1150 EICNET-2085: Anonymous user sees Group management button
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/themes/eic_community/includes/preprocess/common.inc
Labels: bug, backend

#1009 EICNET-1843: S3 Storage
  composer.json
  composer.lock
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  config/sync/s3fs.settings.yml
  lib/modules/eic_default_content/src/Generator/CoreGenerator.php
Labels: backend

#1145 [EICNET-2075] hide stats and likes action on hidden comments
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: frontend, react

#1152 EICNET-1896: Color group states (sitewide)
  lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#1091 [EICNET]chore: Upgrade to php 7.4
  Makefile
  composer.json
  docker-compose.yml
  docker/php/Dockerfile
  docker/php/database-healthcheck.sh
Labels: enhancement, backend

#1157 EICNET-1532: Filelist header width fix.
  lib/themes/eic_community/sass/components/_filelist.scss
Labels: frontend

#1151 EICNET-2076: Disable like action and statistics in comments
  config/sync/core.entity_form_display.comment.node_comment.default.yml
  config/sync/core.entity_view_display.comment.node_comment.default.yml
  config/sync/field.field.comment.node_comment.field_comment_is_archived.yml
  config/sync/field.storage.comment.field_comment_is_archived.yml
  lib/modules/eic_comments/eic_comments.module
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/FlagAccessCheck.php
  lib/modules/eic_groups/src/Access/UnFlagAccessCheck.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: backend

#1155 [EICNET-1908]feat: Create new endpoint for organisation "/team" overview
  config/sync/context.context.group_members_overviews.yml
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupAnchorFeature/GroupAnchorMembers.php
  lib/modules/eic_overviews/eic_overviews.routing.yml
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
Labels: backend

#1149 EICNET-1728: Group invite users in bulk (improvements)
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupInvitationBulkAccessChecker.php
  lib/modules/eic_groups/src/Form/BulkGroupInvitationConfirm.php
  lib/modules/eic_groups/src/GroupsModerationHelper.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
Labels: backend

#1158 [EICNET-1881]fix: Replace translation + addresses label + autocomplete internal link
  config/sync/core.entity_form_display.group.organisation.default.yml
  config/sync/core.entity_form_display.paragraph.organisation_location.default.yml
  config/sync/core.entity_view_display.group.organisation.default.yml
  config/sync/core.entity_view_display.paragraph.organisation_location.default.yml
  config/sync/field.field.group.organisation.field_locations.yml
  config/sync/field.field.paragraph.organisation_location.field_city.yml
  config/sync/field.field.paragraph.organisation_location.field_country.yml
  config/sync/field.storage.group.field_locations.yml
  config/sync/field.storage.paragraph.field_city.yml
  config/sync/field.storage.paragraph.field_country.yml
  config/sync/paragraphs.paragraphs_type.organisation_location.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_private_message/src/Plugin/EntityReferenceSelection/MembershipSelection.php
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: backend

#1160 EICNET-1811: Remove SMED related fields from config.
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.compact.yml
  config/sync/core.entity_view_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.teaser.yml
  config/sync/field.field.user.user.field_message_from_service.yml
  config/sync/field.field.user.user.field_updated_profile_by_service.yml
  config/sync/field.field.user.user.field_updated_profile_by_user.yml
  config/sync/field.field.user.user.field_user_status.yml
  config/sync/field.storage.user.field_message_from_service.yml
  config/sync/field.storage.user.field_updated_profile_by_service.yml
  config/sync/field.storage.user.field_updated_profile_by_user.yml
  config/sync/field.storage.user.field_user_status.yml
Labels: backend

#1159 EICNET-2098: Enable group invitations in Organisations
  config/sync/core.entity_form_display.group_content.organisation-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.organisation-group_invitation.default.yml
  config/sync/field.field.group_content.organisation-group_invitation.field_invitation_counter.yml
  config/sync/field.field.group_content.organisation-group_invitation.group_roles.yml
  config/sync/field.field.group_content.organisation-group_invitation.invitation_status.yml
  config/sync/field.field.group_content.organisation-group_invitation.invitee_mail.yml
  config/sync/group.content_type.organisation-group_invitation.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-owner.yml
  lib/modules/eic_groups/src/Access/GroupInvitationBulkAccessChecker.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
Labels: backend

#1165 EICNET-1753: Footer site name (rework)
  config/sync/field.field.block_content.basic.body.yml
Labels: backend

#1167 EICNET-2102: Create-a-new-group CTA not working and wrong color
  lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc
Labels: bug, backend

#1170 EICNET-2101: Maintenance Sprint 32
  composer.json
  composer.lock
  config/sync/facets.facet.discussions_regions_countries.yml
  config/sync/facets.facet.discussions_topics.yml
  config/sync/facets.facet.discussions_type.yml
  config/sync/facets.facet.global_members_job_title.yml
  config/sync/facets.facet.global_members_languages.yml
  config/sync/facets.facet.global_members_location_country_code.yml
  config/sync/facets.facet.global_members_topics_of_expertise.yml
  config/sync/facets.facet.groups_regions_countries.yml
  config/sync/facets.facet.groups_topics.yml
  config/sync/facets.facet.members_languages.yml
  config/sync/facets.facet.members_topics_of_expertise.yml
  config/sync/facets.facet.members_topics_of_interest.yml
  config/sync/facets.facet.search_content_type.yml
  config/sync/facets.facet.search_group_content_type.yml
  config/sync/facets.facet.search_group_regions_countries.yml
  config/sync/facets.facet.search_group_topics.yml
  config/sync/facets.facet.search_regions_countries.yml
  config/sync/facets.facet.search_topics.yml
  lib/modules/eic_default_content/eic_default_content.info.yml
  lib/modules/eic_default_content/src/Generator/GroupGenerator.php
  lib/modules/eic_default_content/src/Generator/OrganisationGenerator.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
Labels: backend

#1175 [EICNET-1945]feat: Implement correct filter for profile activity feed + set correct datasource feed
  config/sync/context.context.my_profile.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
Labels: backend, frontend, react

#1182 [EICNET]feat: Change route url for my interests
  config/sync/context.context.group_global.yml
  config/sync/context.context.my_profile.yml
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Controller/MyProfileController.php
  lib/modules/eic_user/src/Plugin/Block/MyProfileHeaderBlock.php
Labels: backend

#1180 [EICNET-1907]fix: Use group getMembers method instead of statistics
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
Labels: backend

#1183 EICNET-2107: Allow admin roles to edit all comments in all group types.
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/user.role.content_administrator.yml
Labels: backend

#1185 EICNET-2095: Breadcrumbs on contact must be below the banner
  config/sync/context.context.contact_page.yml
  config/sync/context.context.contact_page_anonymous.yml
  config/sync/context.context.global_breadcrumbs.yml
Labels: backend

#1178 Feature/eicnet 1924 share group content rework
  config/sync/group.content_type.event-group_shared_content.yml
  config/sync/group.content_type.group-group_shared_content.yml
  config/sync/group.content_type.group_content_type_4a2cdf9ed8847.yml
  lib/modules/eic_content/src/EICContentHelper.php
  lib/modules/eic_groups/modules/eic_share_content/eic_share_content.services.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Hooks/SolrDocumentDecorator.php
  lib/modules/eic_groups/modules/eic_share_content/src/Plugin/GroupContentEnabler/SharedContent.php
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: backend

#1189 [EICNET]fix: use load more for activity feed
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend, frontend, react

#1114 [EICNET-1747]feat: Add new paragraph external user
  config/sync/core.entity_form_display.paragraph.organisation_member.default.yml
  config/sync/core.entity_form_display.paragraph.organisation_member_external.default.yml
  config/sync/core.entity_view_display.paragraph.organisation_member.default.yml
  config/sync/core.entity_view_display.paragraph.organisation_member_external.default.yml
  config/sync/field.field.group.organisation.field_team_members.yml
  config/sync/field.field.paragraph.organisation_member.field_organisations.yml
  config/sync/field.field.paragraph.organisation_member_external.field_full_name.yml
  config/sync/field.field.paragraph.organisation_member_external.field_job_title.yml
  config/sync/field.field.paragraph.organisation_member_external.field_location.yml
  config/sync/field.field.paragraph.organisation_member_external.field_media.yml
  config/sync/field.field.paragraph.organisation_member_external.field_organisations.yml
  config/sync/field.storage.group.field_team_members.yml
  config/sync/field.storage.paragraph.field_full_name.yml
  config/sync/field.storage.paragraph.field_location.yml
  config/sync/field.storage.paragraph.field_organisations.yml
  config/sync/paragraphs.paragraphs_type.organisation_member_external.yml
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/patterns/compositions/organisation/organisation.member.teaser.html.twig
  lib/themes/eic_community/sass/compositions/_featured-content-collection.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
  lib/themes/eic_community/templates/paragraphs/paragraph--organisation-member-external.html.twig
Labels: backend, frontend

#1176 EICNET-1940: Email notification for user tagging in comments (Improvements)
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: backend

#1187 EICNET-2087: About section in global events
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/themes/eic_community/includes/preprocess/events.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/templates/group/group--event--about-page.html.twig
Labels: backend

#1153 [EICNET-1782]feat: Set introduction field in teaser of search news
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
Labels: backend, react

#1191 EICNET-1907: Overview double load fix.
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: frontend

#1171 EICNET-2094: Restructure mailtemplates.
  lib/themes/eic_community/mails/mail-dist/full_text.html
  lib/themes/eic_community/mails/mail-dist/group_ownership_transfer.html
  lib/themes/eic_community/mails/mail-dist/group_ownership_transfer_02.html
  lib/themes/eic_community/mails/mail-dist/layout.html
  lib/themes/eic_community/mails/mail-dist/my_update.html
  lib/themes/eic_community/mails/mail-dist/template.html
  lib/themes/eic_community/mails/mail-dist/template_02.html
  lib/themes/eic_community/mails/mail-dist/user_tagged.html
  lib/themes/eic_community/mails/src/components/footer.mjml
  lib/themes/eic_community/mails/src/components/header.mjml
  lib/themes/eic_community/mails/src/full_text.mjml
  lib/themes/eic_community/mails/src/templates/full_text.mjml
  lib/themes/eic_community/mails/src/templates/group_ownership_transfer.mjml
  lib/themes/eic_community/mails/src/templates/group_ownership_transfer_02.mjml
  lib/themes/eic_community/mails/src/templates/layout.mjml
  lib/themes/eic_community/mails/src/templates/my_update.mjml
  lib/themes/eic_community/mails/src/templates/template.mjml
  lib/themes/eic_community/mails/src/templates/template_02.mjml
  lib/themes/eic_community/mails/src/templates/user_tagged.mjml
  lib/themes/eic_community/package.json
Labels: frontend

#1184 EICNET-2092: Make sure group overviews return access denied when group is blocked.
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupPageAccessChecker.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
Labels: backend

#1196 [EICNET-1909]fix: Set event type instead of topics in teaser tag + format image
  config/sync/search_api.index.global.yml
  lib/modules/eic_overviews/src/GroupOverviewPages.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupEvent.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js
Labels: backend, react

#1195 [EICNET-190]fix: do not enable add news/event add content for GM
  config/sync/eic_groups.group_features.eic_groups_anchor_group_events.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_members.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_news.yml
Labels: backend

#1193 EICNET-2086: Homepage - upcoming events should show "view all events"
  config/sync/views.view.groups_homepage.yml
Labels: bug, backend
