Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-08, with the labels that each got.

#1878 [EICNET]chore: Improve instancied menu links from group to not be rediscovered
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
  lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
  lib/modules/oec_group_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
  lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
Labels: enhancement, backend

#1884 EICNET-2708: [Event] Link to event registration does not work.
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: bug, backend

#1885 EICNET-2680: Check why config always needs to be synced
  config/sync/context.context.contribution.yml
  config/sync/context.context.events_overview.yml
  config/sync/context.context.following.yml
  config/sync/context.context.group_discussions_overviews.yml
  config/sync/context.context.group_events_overviews.yml
  config/sync/context.context.group_files_overviews.yml
  config/sync/context.context.group_members_overviews.yml
  config/sync/context.context.group_news_overviews.yml
  config/sync/context.context.group_search.yml
  config/sync/context.context.groups_overview.yml
  config/sync/context.context.interests.yml
  config/sync/context.context.members_overview.yml
  config/sync/context.context.search.yml
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/search_api_solr.solr_field_type.text_und_6_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_und_7_0_0.yml
  config/sync/views.view.global_index_group_content.yml
Labels: backend

#1888 Feature/eicnet 2705 performance fixes
  composer.patches.json
  config/sync/views.view.admin_blocked_entities.yml
  config/sync/views.view.admin_groups.yml
  config/sync/views.view.admin_messages.yml
  config/sync/views.view.closed_requests.yml
  config/sync/views.view.eic_admin_groups_data_export.yml
  config/sync/views.view.eic_group_members.yml
  config/sync/views.view.eic_group_nodes.yml
  config/sync/views.view.eic_group_pending_members.yml
  config/sync/views.view.global_index_group_content.yml
  config/sync/views.view.group_discussions.yml
  config/sync/views.view.group_documents.yml
  config/sync/views.view.group_events.yml
  config/sync/views.view.group_related_groups.yml
  config/sync/views.view.group_related_news_stories.yml
  config/sync/views.view.groups.yml
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
  patches/group_permissions/group_permissions-cache_performance_issue.patch
Labels: backend

#1892 EICNET-2740: SmedId param convert: allow finding users also by email.
  lib/modules/eic_webservices/eic_webservices.module
  lib/modules/eic_webservices/eic_webservices.services.yml
  lib/modules/eic_webservices/src/ParamConverter/SmedIdConverter.php
Labels: backend

#1891 EICNET-2701: Filter out blocked users in search overviews.
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1896 EICNET-2720: Switch 'Recently updated' from timestamp to changed time.
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
Labels: backend

#1897 EICNET-2721: Allow other statuses for my drafts.
  lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1900 EICNET-2754: Moderated workflow: allow Publish transistion from unpublished.
  config/sync/workflows.workflow.eic_moderated_workflow.yml
Labels: backend

#1901 EICNET-2763: Display user display name in authoring information.
  composer.patches.json
Labels: backend

#1894 EICNET-2776: SA and SCM do not have access to the UIT
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: bug, backend

#1898 EICNET-2741: Fix group_permissions module when group is not saved yet.
  composer.patches.json
  patches/group_permissions/group_permissions-cache_performance_issue.patch
Labels: bug, backend

#1886 EICNET-2717: Stories - Posting date is wrong by default
  composer.lock
  composer.patches.json
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#1895 EICNET-2734: [User profile] A trusted user should be able to edit his role.
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/UserHelper.php
Labels: bug, backend

#1899 EICNET-2766: [Organisation] Trusted should not join organisation without approaval of the admnistrator/owner
  config/sync/group.role.organisation-dcb2f93df.yml
  config/sync/group.role.organisation-outsider.yml
  lib/modules/eic_groups/eic_groups.install
Labels: bug, backend

#1902 EICNET-2760: [Event] News have confusing instructions
  lib/modules/eic_moderation/src/Service/ContentModerationManager.php
Labels: bug, backend

#1903 EICNET-2778: [Event] News and stories created within an event should only be visible to the member of that event
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
Labels: bug, backend

#1904 EICNET-XXXX: Add cas hard-coded variable in settings.php.
  web/sites/default/default.settings.k8s.php
Labels: backend

#1911 ICNET-2784: Make sure we don't discloe users email address when inviting to groups.
  lib/modules/eic_groups/src/Form/BulkGroupInvitationConfirm.php
Labels: backend

#1910 EICNET-2783: Mimic Drupal\contact\MailHandler::sendMailMessages() logic to handle anonymous users.
  lib/modules/eic_contact/eic_contact.module
Labels: backend

#1909 Feature/eicnet 2720 groups sorting options
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroup.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
Labels: backend

#1907 EICNET-2705: Fix issue with group permissions.
  composer.patches.json
Labels: backend

#1916 Feature/eicnet 2750 events visibility
  lib/modules/eic_groups/eic_groups.api.php
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
  lib/modules/oec_group_features/src/GroupFeatureHelper.php
  lib/modules/oec_group_flex/oec_group_flex.api.php
  lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PublicVisibility.php
Labels: backend

#1834 Feature/eicnet 2375 user profile edit form
  config/sync/core.entity_form_display.profile.member.default.yml
  config/sync/core.entity_form_display.user.user.default.yml
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.module
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php
  lib/modules/eic_user/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: backend

#1912 [EICNET-2781]feat: Do not allow group content (from event) to be shown for non-members (only SOLR)
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: backend

#1913 [EICNET-2768]feat: Hide related groups in news
  config/sync/core.entity_form_display.node.news.default.yml
Labels: backend

#1914 [EICNET-2787]feat: Disable bookmark content
  config/sync/flag.flag.bookmark_content.yml
Labels: backend

#1918 EICNET-2733: Disable user type for SMED users.
  lib/modules/eic_user/src/Hooks/FormAlter.php
Labels: backend

#1921 Feature/eicnet 2786 exclude global news
  config/sync/user.role.trusted_user.yml
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
Labels: backend

#1924 EICNET-2793: Fix activity stream item URLs.
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
Labels: backend

#1926 EICNET-2785: Webservice: fix error with user creation.
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
Labels: backend

#1928 Feature/eicnet 2800 user smed status bulk update
  config/sync/views.view.user_admin_people.yml
  lib/modules/eic_user/modules/eic_user_login/config/schema/eic_user_login.schema.yml
  lib/modules/eic_user/modules/eic_user_login/src/Plugin/Action/ChangeUserSmedStatus.php
Labels: backend

#1929 EICNET-2794: Follow taxonomy terms for entitu_usage.
  config/sync/entity_usage.settings.yml
Labels: backend

#1931 EICNET-2808: Enlarage users base to check against SMED and update SME…
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
Labels: backend

#1930 Release/0.43.10 / v1.0.9
  config/sync/core.extension.yml
  config/sync/entity_usage.settings.yml
  config/sync/views.view.user_admin_people.yml
  lib/modules/eic_user/modules/eic_user_login/config/schema/eic_user_login.schema.yml
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Plugin/Action/ChangeUserSmedStatus.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
Labels: backend

#1935 EICNET-2818 - smed webservice fixes
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserConnection.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
Labels: backend
