Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-09, with the labels that each got.

#1936 Feature/eicnet 2795 organisation required fields
  config/sync/field.field.group.organisation.field_vocab_services_products.yml
  config/sync/field.field.group.organisation.field_vocab_target_markets.yml
  config/sync/field.field.group.organisation.field_vocab_topics.yml
  lib/modules/eic_groups/modules/eic_organisations/eic_organisations.module
  lib/modules/eic_groups/modules/eic_organisations/src/Hooks/FormOperations.php
Labels: backend

#1939 EICNET-2829: Add taxonomy overview page access permission.
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#1937 Feature/eicnet 2817 group user management permissions
  config/sync/block.block.eicpagecontextualactionblock.yml
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/group.role.group-owner.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-owner.yml
  config/sync/views.view.eic_group_members.yml
  lib/modules/eic_blocks/eic_blocks.api.php
  lib/modules/eic_blocks/eic_blocks.module
  lib/modules/eic_blocks/src/Plugin/Block/PageContextualActionBlock.php
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/eic_groups.install.inc
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/src/Plugin/GroupMembershipPermissionProvider.php
  lib/modules/eic_groups/modules/eic_group_membership/src/Routing/RouteSubscriber.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-action-block.inc
  lib/themes/eic_community/templates/blocks/eic-action-block.html.twig
Labels: backend, frontend

#1940 EICNET-2799: Latest News/Stories, change thumbnail source.
  lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
Labels: backend

#1934 [EICNET-2802]feat: Implement also profile update into the user one
  config/sync/rest.resource.eic_webservices_profile.yml
  config/sync/user.role.service_authentication.yml
  lib/modules/eic_helper/eic_helper.services.yml
  lib/modules/eic_helper/src/SocialLinksFieldHelper.php
  lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
  lib/modules/eic_webservices/config/install/rest.resource.eic_webservices_profile.yml
  lib/modules/eic_webservices/eic_webservices.services.yml
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicProfileResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserUpdateResource.php
  lib/modules/eic_webservices/src/Utility/EicWsHelper.php
  lib/modules/eic_webservices/src/Utility/WsRestHelper.php
Labels: backend

#1941 EICNET-2779: [Event] A none logged user should not see pending events
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVisibility.php
Labels: bug, backend

#1943 Feature/eicnet 2832 user smed check fix
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.module
  lib/modules/eic_user/modules/eic_user_login/src/Controller/MemberAccessController.php
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserConnection.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
Labels: backend

#1944 EICNET-2797: Disable visibility sorting.
  config/sync/views.view.admin_groups.yml
Labels: backend

#1948 Feature/eicnet 2801 profile about you default format
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/field.field.profile.member.field_body.yml
  lib/modules/eic_user/eic_user.install
Labels: backend

#1954 EICNET-2802: Make sure to include the base_path in sub-requests.
  lib/modules/eic_webservices/src/Utility/EicWsHelper.php
Labels: backend

#1846 EICNET-2670: As a user, I want a limit on group invitation reminders so that I am not spammed
  config/sync/core.entity_form_display.group_content.event-group_invitation.default.yml
  config/sync/core.entity_form_display.group_content.group-group_invitation.default.yml
  config/sync/core.entity_form_display.group_content.organisation-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.event-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.group-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.organisation-group_invitation.default.yml
  config/sync/eic_groups.settings.yml
  config/sync/field.field.group_content.event-group_invitation.field_invitation_reminder_count.yml
  config/sync/field.field.group_content.event-group_invitation.field_invitation_reminder_date.yml
  config/sync/field.field.group_content.group-group_invitation.field_invitation_reminder_count.yml
  config/sync/field.field.group_content.group-group_invitation.field_invitation_reminder_date.yml
  config/sync/field.field.group_content.organisation-group_invitation.field_invitation_reminder_count.yml
  config/sync/field.field.group_content.organisation-group_invitation.field_invitation_reminder_date.yml
  config/sync/field.storage.group_content.field_invitation_reminder_count.yml
  config/sync/field.storage.group_content.field_invitation_reminder_date.yml
  lib/modules/eic_groups/config/install/eic_groups.settings.yml
  lib/modules/eic_groups/src/Hooks/CronOperations.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
Labels: backend

#1956 EICNET-2805: Handle social links for Events in WS.
  lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
Labels: backend

#1955 [EICNET-2719]feat: Add second sorts options + remove spaces before saving node/group
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_helper/eic_helper.services.yml
  lib/modules/eic_helper/src/SocialLinksFieldHelper.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1951 EICNET-2798: Filters on a the topics do not point to correct taxonomy
  lib/modules/eic_topics/src/Plugin/Block/TopicStatisticsBlock.php
Labels: bug, backend

#1953 Feature/eicnet 2790 missinghp block
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/pathauto.pattern.node_page.yml
  lib/modules/eic_blocks/eic_blocks.install
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/MessageSubscriptionEventSubscriber.php
  lib/themes/eic_community/templates/blocks/block--homepage-usp-tiles.html.twig
  lib/themes/eic_community/templates/content/node--page--teaser.html.twig
Labels: backend

#1950 EICNET-2850: [Groups] TU cannot see created group in groups list
  lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: bug, backend

#1963 EICNET-2715: [Stories] Manage content display wrong information for draft
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
Labels: bug, backend

#1959 EICNET-2816: [Notifications] Missing the first name of the user in the greeting line
  config/sync/group.content_type.event-group_invitation.yml
  config/sync/group.content_type.group-group_invitation.yml
  config/sync/group.content_type.organisation-group_invitation.yml
Labels: bug, backend

#1966 EICNET-2715: [Stories] Manage content display wrong information for draft (Rework)
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
Labels: bug, backend

#1970 EICNET-900: Recommend content (small fixes)
  lib/modules/eic_recommend_content/templates/eic-recommend-content-link.html.twig
Labels: bug, backend

#1971 EICNET-900: Fix endpoint URL in recommend content data attributes.
  lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
Labels: bug, backend

#1969 EICNET-2849: Global contact message cron issue
  config/sync/core.entity_form_display.message.notify_contact_global_confirm.default.yml
  config/sync/core.entity_form_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_form_display.message.notify_mt_contact_global.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_mt_contact_global.default.yml
  config/sync/core.entity_view_display.message.notify_mt_contact_global.mail_body.yml
  config/sync/core.entity_view_display.message.notify_mt_contact_global.mail_subject.yml
  config/sync/field.field.message.notify_contact_global_confirm.field_sender_name.yml
  config/sync/field.field.message.notify_contact_global_copy.field_sender_name.yml
  config/sync/field.field.message.notify_mt_contact_global.field_sender_email.yml
  config/sync/field.field.message.notify_mt_contact_global.field_sender_name.yml
  config/sync/field.storage.message.field_sender_email.yml
  config/sync/field.storage.message.field_sender_name.yml
  config/sync/language/en/message.template.notify_contact_global_confirm.yml
  config/sync/language/en/message.template.notify_contact_global_copy.yml
  config/sync/language/en/message.template.notify_mt_contact_global.yml
  config/sync/message.template.notify_contact_global_confirm.yml
  config/sync/message.template.notify_contact_global_copy.yml
  config/sync/message.template.notify_mt_contact_global.yml
  lib/modules/eic_contact/eic_contact.module
  lib/themes/eic_community/includes/preprocess/content/message.inc
Labels: bug, backend

#1968 EICNET-2857: [Organisation] created organisation miss of the default features
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/GroupResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php
Labels: bug, backend

#1967 EICNET-2834: [Events] Not possible to edit event description in draft events
  lib/modules/eic_events/eic_events.module
  lib/modules/eic_events/src/Hooks/EntityOperations.php
  lib/modules/eic_events/src/Hooks/FormOperations.php
Labels: enhancement, backend

#1972 EICNET-2765: [Organsiation] inviting a user page replace reference to groups with "Organsiation"
  config/sync/eic_admin.action_forms.ginvite.invitation.bulk.confirm.yml
  config/sync/eic_admin.action_forms.ginvite.invitation.bulk.yml
Labels: bug, backend

#1973 EICNET-2865: Change the "Send notification" checkbox label and add field description
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: enhancement, backend

#1946 EICNET-2804: [Event/stories overview page] Cannot search for my events or My stories (timeout)
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js
Labels: bug, backend

#1980 EICNET-2715: [Stories] Manage content display wrong information for draft (Rework)
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
Labels: bug, backend

#1976 EICNET-2869: Skip non-existing group content entities.
  lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentUrlAliasUpdate.php
Labels: backend

#1977 EICNET-2867: Do not send contact submissions to SA/SCM.
  lib/modules/eic_contact/eic_contact.module
Labels: backend

#1991 EICNET-2875: mails from contact form are stuck in the queue
  lib/themes/eic_community/includes/preprocess/content/message.inc
Labels: bug, backend

#1988 Feature/eicnet 2841 module updates
  composer.json
  composer.lock
  composer.patches.json
Labels: backend

#1992 EICNET-2875: mails from contact form are stuck in the queue
  lib/themes/eic_community/includes/preprocess/content/message.inc
Labels: bug, backend

#1990 EICNET-2745: Closed joining method for events
  lib/modules/oec_group_flex/oec_group_flex.install
  lib/modules/oec_group_flex/oec_group_flex.services.yml
  lib/modules/oec_group_flex/src/GroupJoiningMethodDatabaseStorage.php
  lib/modules/oec_group_flex/src/GroupJoiningMethodDatabaseStorageInterface.php
  lib/modules/oec_group_flex/src/GroupJoiningMethodRecord.php
  lib/modules/oec_group_flex/src/GroupJoiningMethodRecordInterface.php
  lib/modules/oec_group_flex/src/OECGroupFlexGroupDecorator.php
  lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
  lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuCloseMethod.php
Labels: enhancement, backend
