Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-05, with the labels that each got.

#1476 [EICNET-1933]feat: Introduce notification settings for organisations
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Controller/MySettingsController.php
  lib/modules/eic_user/src/NotificationTypes.php
  lib/modules/eic_user/src/Plugin/Block/NotificationsSettingsBlock.php
  lib/modules/eic_user/src/Service/NotificationSettingsManager.php
Labels: enhancement, backend

#1475 [EICNET-2233]feat: Unset default copy checkbox from contact + add custom
  lib/modules/eic_contact/eic_contact.module
Labels: backend

#1480 [EICNET-2358]chore: Hide the published checkbox for documents
  config/sync/config_ignore.settings.yml
  config/sync/core.entity_form_display.media.eic_document.default.yml
  config/sync/pathauto.pattern.books.yml
  config/sync/pathauto.pattern.discussions.yml
  config/sync/pathauto.pattern.events.yml
  config/sync/pathauto.pattern.library.yml
  config/sync/pathauto.pattern.news.yml
  config/sync/pathauto.pattern.stories.yml
  config/sync/pathauto.pattern.wiki_pages.yml
  web/sites/default/default.settings.k8s.php
Labels: enhancement, backend

#1455 [EICNET-2015]fix: On reset, reset the state drupal + state to false if smed id group migration
  lib/modules/eic_migrate/src/Commands/MigrateToolsOverrideCommands.php
Labels: backend

#1481 [EICNET-2351|EICNET-2343]chore: User contact form enhancements
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: enhancement, backend

#1450 [EICNET-1703]fix: Add permissions for page type
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: backend

#1494 [EICNET-2426]fix: If node delete form route, do not show comments
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
Labels: backend

#1498 Feature/eicnet 2378 files migration fix
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/FieldableFile.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/FileComplete.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/FileCompleteWithSMEDIds.php
Labels: backend, migration

#1488 EICNET-2028: Update message template body (MT08).
  config/sync/language/en/message.template.notify_group_access_change.yml
  config/sync/message.template.notify_group_access_change.yml
Labels: backend

#1496 EICNET-2387: Group invitation - if user does not exist anymore, it throws 500 error
  lib/modules/eic_user/src/Hooks/FormAlter.php
Labels: bug, backend

#1495 [EICNET-2414]fix: If anonymous user do not show post content in sidebar
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend, react

#1477 [EICNET-2174]feat: Always allow access for latest activity
  config/sync/group.role.group-anonymous.yml
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
Labels: backend

#1479 [cypress] add regretion test to check user invitation access
  e2e/cypress.json
  e2e/cypress/integration/user/invitation.spec.js
Labels: cypress

#1504 [EICNET] Add missing settings
  web/sites/default/default.settings.k8s.php
Labels: enhancement, backend

#1497 [EICNET-2389]chore: Adapt the breadcrumb for the add group pages
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
Labels: enhancement, backend

#1490 [EICNET-2223]chore: Add an organisations list page under community/groups
  config/sync/views.view.admin_groups.yml
  lib/modules/eic_admin/eic_admin.links.menu.yml
  lib/modules/eic_admin/eic_admin.links.task.yml
Labels: enhancement, backend

#1505 [EICNET-2411] notification unsubcribe reload when we unsubscribe
  lib/modules/eic_user/src/Controller/MySettingsController.php
  lib/themes/eic_community/react/components/Block/NotifManagement/index.js
Labels: frontend, react

#1343 Feature/eicnet 2257 user profile completion check
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.services.yml
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/ProfileConst.php
  lib/modules/eic_user/src/UserHelper.php
Labels: backend

#1513 Release 0.37.0
  config/sync/group.role.group-anonymous.yml
  config/sync/language/en/message.template.notify_group_access_change.yml
  config/sync/message.template.notify_group_access_change.yml
  config/sync/views.view.admin_groups.yml
  e2e/cypress.json
  e2e/cypress/integration/user/invitation.spec.js
  lib/modules/eic_admin/eic_admin.links.menu.yml
  lib/modules/eic_admin/eic_admin.links.task.yml
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.services.yml
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/Controller/MySettingsController.php
  lib/modules/eic_user/src/Hooks/FormAlter.php
  lib/modules/eic_user/src/ProfileConst.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/mails/mail-dist/header_footer.html
  lib/themes/eic_community/mails/src/templates/header_footer.mjml
  lib/themes/eic_community/react/components/Block/NotifManagement/index.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  web/sites/default/default.settings.k8s.php
Labels: backend

#1500 [EICNET-1086]fix: Remove comment stats on activity stream for documents
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
Labels: enhancement, frontend

#1508 [EICNET-2386]chore: Remove view members permission from GM role
  config/sync/group.role.group-member.yml
  lib/modules/eic_groups/eic_groups.module
Labels: enhancement, backend

#1509 [EICNET-2410]chore: Allow p tags in basic_html text format
  config/sync/filter.format.basic_text.yml
Labels: enhancement, backend

#1512 [EICNET-2429]fix: Use /members-pending for the manage join request link
  config/sync/language/en/message.template.notify_new_membership_request.yml
  config/sync/message.template.notify_new_membership_request.yml
Labels: enhancement, backend

#1511 [EICNET-2426]fix: Do not show comments block in edit form
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
Labels: backend

#1447 EICNET-1441: Enable Gallery and Document CTs for Organisations.
  config/sync/group.content_type.organisation-group_node-document.yml
  config/sync/group.content_type.organisation-group_node-gallery.yml
  config/sync/migrate_plus.migration.upgrade_d7_content_membership.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_share_to_group_content.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_book.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_content_membership.yml
Labels: backend, migration

#1519 Feature/eicnet 2378 files migration fix
  config/sync/migrate_plus.migration.upgrade_d7_file_audio_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_file_image_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_file_undefined_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_file_video_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum_gallery_slides_paragraph.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  config/sync/migrate_plus.migration.upgrade_d7_user.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_audio_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_image_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_undefined_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_video_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum_gallery_slides_paragraph.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user.yml
Labels: backend, migration

#1507 EICNET-XXXX: Fix comments migration.
  config/sync/migrate_plus.migration.upgrade_d7_comment.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml
Labels: backend, migration

#1506 Feature/eicnet 1811 eu login
  config/sync/migrate_plus.migration.upgrade_d7_user_authmap.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_authmap.yml
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserUpdateResource.php
Labels: backend, migration

#1510 [EICNET-1113]fix: Get data from solr for event statistics
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#1493 [EICNET-2413]fix: Sort correctly content title from ss_ and not tm_
  config/sync/context.context.drafts.yml
  config/sync/context.context.events_overview.yml
  config/sync/context.context.group_search.yml
  config/sync/context.context.groups.yml
  config/sync/context.context.search.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php
Labels: backend

#1503 [EICNET-2423]fix: Send author avatar if exists in tagged comment
  lib/themes/eic_community/includes/preprocess/comments/comment.inc
  lib/themes/eic_community/mails/src/templates/user_tagged.mjml
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: frontend

#1492 EICNET-2422: Comments can not be liked
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: frontend

#1491 [EICNET-2022]feat: send notification when group request has been denied
  config/sync/core.entity_form_display.group.group.default.yml
  config/sync/core.entity_form_display.message.notify_group_request_denied.default.yml
  config/sync/core.entity_view_display.message.notify_group_request_denied.default.yml
  config/sync/core.entity_view_display.message.notify_group_request_denied.mail_body.yml
  config/sync/core.entity_view_display.message.notify_group_request_denied.mail_subject.yml
  config/sync/field.field.message.notify_group_request_denied.field_group_ref.yml
  config/sync/field.field.message.notify_group_request_denied.field_reason.yml
  config/sync/field.storage.message.field_reason.yml
  config/sync/language/en/message.template.notify_group_request_denied.yml
  config/sync/message.template.notify_group_request_denied.yml
  config/sync/workflows.workflow.groups.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/GroupsModerationHelper.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
Labels: backend

#1487 EICNET-2024: Group type notification - request to join (GO notification rework)
  config/sync/language/en/message.template.notify_new_membership_request.yml
  config/sync/message.template.notify_new_membership_request.yml
Labels: backend

#1473 [EICNET-2390]fix: do not show links for archived group
  config/sync/workflows.workflow.groups.yml
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/ArchivedRouteAccessCheck.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
Labels: backend

#1501 [EICNET-2025]chore: Change contact links in message templates
  config/sync/language/en/message.template.notify_block_request_accepted.yml
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_group_requested.yml
  config/sync/message.template.notify_block_request_accepted.yml
  config/sync/message.template.notify_group_membership_pending.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_group_requested.yml
Labels: enhancement, backend

#1514 [EICNET-2421]chore: Change breadcrumbs for edit account & profile pages
  lib/modules/eic_user/eic_user.services.yml
  lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php
  lib/modules/eic_user/src/Routing/UserRouteSubscriber.php
Labels: enhancement, backend

#1515 [EICNET-1892]fix: Improvide title & og_title tags for all contents
  config/sync/metatag.metatag_defaults.global.yml
  config/sync/metatag.metatag_defaults.media__eic_document.yml
  config/sync/metatag.metatag_defaults.node.yml
Labels: enhancement, backend

#1528 Release 0.37.0
  config/sync/metatag.metatag_defaults.global.yml
  config/sync/metatag.metatag_defaults.media__eic_document.yml
  config/sync/metatag.metatag_defaults.node.yml
Labels: enhancement, backend, frontend

#1527 EICNET-2377: Warning when importing content membership
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: bug, backend, migration

#1530 EICNET-2257: Allow users missing their profile to logout.
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
Labels: backend

#1531 EICNET-1811: Fix EU Login config to prepare for different environments.
  .env.docker
  config/sync/cas.settings.yml
  config/sync/config_ignore.settings.yml
  web/sites/default/default.settings.k8s.php
  web/sites/default/default.settings.local.php
Labels: backend

#1529 EICNET-XXXX: Skip ignored entities.
  config/sync/migrate_plus.migration.upgrade_d7_content_membership.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_share_to_group_content.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_content_membership.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_share_to_group_content.yml
Labels: backend, migration

#1534 [EICNET-2043]feat: Add most active for groups + fix overview block config
  lib/modules/eic_flags/src/FlagType.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessorInterface.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroup.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/ContributionSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserInvitesListSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserTaggingCommentsSourceType.php
Labels: backend

#1553 [EICNET-2045]feat: Calculate most active score for User entity in SOLR
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/modules/eic_user/src/UserHelper.php
Labels: backend

#1540 [EICNET-2045]feat: Calculate most active score for User entity in SOLR
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
  lib/modules/eic_user/src/UserHelper.php
Labels: backend

#1538 [EICNET-2044]feat: Add most active sort for organisations
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
Labels: backend

#1556 [EICNET-2049]feat: Add most active score for discussions
  config/sync/context.context.group_discussions_overviews.yml
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
  lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
  lib/modules/eic_statistics/src/StatisticsHelper.php
Labels: backend

#1543 EICNET-2437: Front-end content form for the content type Event
  config/sync/core.entity_form_display.node.event.default.yml
Labels: backend, frontend

#1545 EICNET-1794: Front-end content form for the content type Stories
  config/sync/core.entity_form_display.node.story.default.yml
Labels: backend, frontend

#1547 EICNET-1798: Front-end content form for the content type Discusssions
  config/sync/core.entity_form_display.node.discussion.default.yml
Labels: backend, frontend

#1549 EICNET-1799: Front-end content form for the content type Wiki page
  config/sync/core.entity_form_display.node.wiki_page.default.yml
Labels: backend, frontend

#1551 EICNET-1801: Front-end content form for the content type Gallery
  config/sync/core.entity_form_display.node.gallery.default.yml
  lib/themes/eic_community/sass/components/_form.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/drupal_tabs.scss
Labels: backend, frontend

#1552 EICNET-1802: Front-end content form for the content type Video
  config/sync/core.entity_form_display.node.video.default.yml
Labels: backend, frontend

#1539 EICNET-1795: Front-end content form for the group type Group
  config/sync/core.entity_form_display.group.group.default.yml
  lib/themes/eic_community/sass/components/_form.scss
Labels: backend, frontend

#1541 EICNET-1796 Front-end content form for the group type Event
  config/sync/core.entity_form_display.group.event.default.yml
  lib/themes/eic_community/sass/components/_form.scss
Labels: backend, frontend

#1555 EICNET-2463: Error when trying to create a News in a group
  lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
Labels: bug, backend

#1537 EICNET-2425: Group type notification - request to join (GO notification): organization token
  config/sync/language/en/message.template.notify_new_member_joined.yml
  config/sync/language/en/message.template.notify_new_membership_request.yml
  config/sync/message.template.notify_new_member_joined.yml
  config/sync/message.template.notify_new_membership_request.yml
  lib/modules/eic_groups/src/Hooks/GroupTokens.php
Labels: backend

#1558 Feature/eicnet 2297 action forms config part 2
  config/sync/context.context.global_action_forms.yml
  config/sync/context.context.group_global.yml
  lib/modules/eic_admin/config/schema/eic_admin.schema.yml
  lib/modules/eic_admin/src/Controller/ActionFormsController.php
  lib/modules/eic_admin/src/Plugin/Block/ActionFormDescriptionBlock.php
  lib/modules/eic_admin/src/Plugin/Condition/ActionForms.php
  lib/modules/eic_admin/src/Service/ActionFormsManager.php
  lib/themes/eic_community/includes/preprocess/blocks/block.inc
Labels: backend

#1522 EICNET-2435: Migrate Flags
  config/sync/migrate_plus.migration.upgrade_d7_flag_follow_group.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_follow_node.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_follow_node_event.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_follow_taxonomy_term.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_highlight_content.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_like_group.yml
  config/sync/migrate_plus.migration.upgrade_d7_flag_like_node.yml
  config/sync/migrate_plus.migration.upgrade_d7_user_to_profile.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.services.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_follow_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_follow_node.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_follow_node_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_follow_taxonomy_term.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_highlight_content.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_like_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_flag_like_node.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_to_profile.yml
  lib/modules/eic_migrate/src/Plugin/migrate/process/DuplicatedFlag.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/Flag.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/FlagIncludeNodeTypes.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/FlagTaxonomyTermWithSmedIds.php
Labels: backend, migration

#1525 Feature/eicnet 2442 fix media borwser filter
  config/sync/field.field.node.discussion.field_related_downloads.yml
  config/sync/views.view.media_library.yml
  lib/modules/eic_media/eic_media.module
Labels: backend

#1542 EICNET-1797: Front-end content form for the group type Organisation
  config/sync/core.entity_form_display.group.organisation.default.yml
  lib/themes/eic_community/sass/components/_form.scss
Labels: backend, frontend

#1562 [EICNET-2045]fix: Resync dependant entities when adding comment
  lib/modules/eic_groups/src/Controller/DiscussionController.php
Labels: backend

#1554 EICNET-1792: Front-end content form for the content type Page (Basic page)
  config/sync/core.entity_form_display.node.page.default.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: backend, frontend

#1559 [EICNET-1780]fix: Remove some useless sorting
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
Labels: backend

#1536 [EICNET-2396]chore: Remove node cache invalidate from record view
  lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  web/sites/default/default.settings.local.php
Labels: enhancement, backend

#1557 [EICNET-2452]feat: Inject js ckeditor settings into comments block
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/WysiswigEditor.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/entrypoint.js
  lib/themes/eic_community/sass/compositions/_comment-form.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/wysiwig.scss
Labels: frontend, react

#1544 EICNET-1793: Front-end content form for the content type News
  config/sync/core.entity_form_display.node.news.default.yml
  lib/modules/eic_comments/eic_comments.module
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_moderation/src/Hooks/FormOperations.php
  lib/themes/eic_community/includes/alter/form/group.inc
  lib/themes/eic_community/includes/alter/form/node.inc
  lib/themes/eic_community/includes/alter/theme_suggestions/form.inc
  lib/themes/eic_community/sass/components/_form.scss
  lib/themes/eic_community/templates/form/container--empty.html.twig
  lib/themes/eic_community/templates/form/eic-group-edit-form.html.twig
  lib/themes/eic_community/templates/form/node-edit-form.html.twig
Labels: backend, frontend

#1570 [EICNET-2472]feat: Create a queue for late reindex entities into solr
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Hooks/CronOperations.php
  lib/modules/eic_groups/src/Plugin/QueueWorker/ReIndexContentSearchApi.php
  lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_user/src/EventSubscriber/FlagEventSubscriber.php
  web/sites/default/default.settings.k8s.php
  web/sites/default/default.settings.local.php
Labels: enhancement, backend

#1569 [EICNET-2043]feat: On new content or like/dislike resync group
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: backend

#1572 [EICNET-2455]fix: set correct url for contributors
  lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
Labels: backend

#1575 EICNET-2473: Fix moderation state field in FE forms
  lib/themes/eic_community/includes/preprocess/form/form-element.inc
Labels: bug, backend, frontend

#1574 [EICNET-2342]fix: Add like stats to discussion teaser
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
Labels: react

#1573 [EICNET-2371]fix: Add discussion case to show draft for user
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1563 EICNET-2460: I should not be able to see "manage members" as GM in organizations
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.group-a416e6833.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-bf4b46c3a.yml
  config/sync/group.role.group-eca6128ca.yml
  config/sync/group.role.group-owner.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-owner.yml
  config/sync/views.view.eic_group_members.yml
  lib/modules/eic_deploy/eic_deploy.install
  lib/modules/eic_deploy/eic_deploy.module
  lib/modules/eic_groups/eic_groups.group.permissions.yml
Labels: bug, backend

#1577 EICNET-2461: Sharing content to another group should be filtered on the availability of that CT in that specific group
  lib/modules/eic_groups/modules/eic_share_content/eic_share_content.routing.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/themes/eic_community/includes/preprocess/common.inc
Labels: backend

#1580 EICNET-2462: I should not be able to delete myself as a member of a group without transferring ownership
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
Labels: backend

#1581 EICNET-2341: CT document does not have the comment block listed
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
Labels: backend, frontend

#1532 EICNET-2302: Enable and configure oe_webtools_analytics module.
  config/sync/core.extension.yml
  config/sync/oe_webtools_analytics.settings.yml
Labels: backend

#1561 EICNET-2464: Add "My events" and "My organisations" in user profile page
  config/sync/search_api.index.global.yml
  config/sync/views.view.global_index_group_content.yml
  config/sync/views.view.groups.yml
  lib/modules/eic_events/src/Plugin/search_api/processor/EventWeightState.php
  lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/templates/group/group--event--teaser.html.twig
  lib/themes/eic_community/templates/group/group--organisation--teaser.html.twig
Labels: backend, frontend

#1584 EICNET-2477: Content flags in sidebar look bigger than it should
  lib/themes/eic_community/templates/content/node--document--full.html.twig
  lib/themes/eic_community/templates/content/node--event--full.html.twig
  lib/themes/eic_community/templates/content/node--gallery--full.html.twig
  lib/themes/eic_community/templates/content/node--story--full.html.twig
  lib/themes/eic_community/templates/content/node--video--full.html.twig
Labels: bug, frontend

#1568 [EICNET-2066]feat: Implement group archived check for different entity/action
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Access/ArchivedRouteAccessCheck.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
  lib/modules/eic_messages/src/Controller/ActivityStreamController.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroup.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/themes/eic_community/sass/compositions/_state-banner.scss
  lib/themes/eic_community/templates/blocks/eic-group-header-block.html.twig
Labels: backend

#1571 [EICNET/2066] create test for group achive
  e2e/cypress/integration/group/archive.spec.js
Labels: cypress

#1588 EICNET-2269: Help and guidance edit button is aligned all the way to the left
  config/sync/context.context.node_local_tasks.yml
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
  lib/themes/eic_community/templates/content/node--book--full.html.twig
Labels: backend, frontend

#1595 EICNET-2141: regression - error when trying to publish a book
  lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
Labels: bug, backend

#1587 EICNET-2454: Owner does not see draft Discussion and Events in overview
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: bug, backend

#1591 EICNET-2468: Fix wrong group type for events.
  config/sync/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
Labels: backend, migration

#1602 Feature/eicnet 2487 searc index sanitize text
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessor.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
Labels: backend

#1597 [EICNET-2045]feat:Resync also owner of the content when new content
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentSearchApi.php
  lib/modules/eic_groups/src/Plugin/QueueWorker/ReIndexContentSearchApi.php
Labels: backend

#1599 EICNET-2489: Create fixture for Global events
  config/sync/context.context.group_wiki_page.yml
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/src/Generator/GroupTypeEventGenerator.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
Labels: enhancement, backend

#1594 EICNET-2456: Latest members show placeholder [ORGANISATION NAME]
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
Labels: backend

#1609 EICNET-284: Make body and language fields optional in media type document
  config/sync/field.field.media.eic_document.field_body.yml
  config/sync/field.field.media.eic_document.field_language.yml
Labels: backend

#1612 [EICNET]fix: Check if user's email is valid before sending a notification
  lib/modules/eic_messages/src/Plugin/QueueWorker/MessageNotifyQueueWorker.php
Labels: bug, backend

#1603 [EICNET-1173] Do not display the social share button on private contents
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: backend

#1610 EICNET-1316: Node 'Document' migration (Improvements)
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/field.field.node.document.field_body.yml
  config/sync/field.field.node.document.field_language.yml
  config/sync/field.storage.node.field_document_type.yml
  config/sync/field.storage.node.field_language.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
Labels: backend

#1611 EICNET-2078: Pass comments body through basic_text filter and make us…
  lib/modules/eic_groups/src/Controller/DiscussionController.php
Labels: backend

#1601 [EICNET] Digest test UI
  config/sync/config_split.config_split.development.yml
  config/sync/config_split.config_split.test.yml
  config/sync/mailsystem.settings.yml
  lib/modules/eic_messages/modules/eic_digest_test/eic_digest_test.info.yml
  lib/modules/eic_messages/modules/eic_digest_test/eic_digest_test.links.menu.yml
  lib/modules/eic_messages/modules/eic_digest_test/eic_digest_test.routing.yml
  lib/modules/eic_messages/modules/eic_digest_test/src/Form/DigestTestUI.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Service/DigestCollector.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Service/DigestManager.php
Labels: enhancement, backend

#1614 EICNET-2164: Group permission fix
  config/sync/eic_groups.group_features.eic_groups_anchor_group_events.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_members.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_news.yml
  lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
  lib/modules/oec_group_features/oec_group_features.info.yml
  lib/modules/oec_group_features/oec_group_features.services.yml
  lib/modules/oec_group_features/src/GroupFeatureHelper.php
  lib/modules/oec_group_features/src/Hooks/EntityOperations.php
Labels: backend

#1621 EICNET-2493: Update package guzzlehttp/guzzle
  composer.lock
Labels: backend

#1564 Feature/eicnet xxxx action forms
  config/sync/core.entity_form_display.group_content.event-group_membership_request.default.yml
  config/sync/core.entity_form_display.group_content.group-group_membership_request.default.yml
  config/sync/eic_admin.action_forms.entity.group.group_request_membership.yml
  config/sync/eic_admin.action_forms.entity.group_content.group_reject_membership.yml
  lib/modules/eic_admin/eic_admin.services.yml
  lib/modules/eic_admin/src/Plugin/Block/ActionFormDescriptionBlock.php
  lib/modules/eic_admin/src/Service/ActionFormsManager.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
Labels: backend

#1618 Feature/eicnet 2492 migration sanitise text
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_article.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_book.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  docker/php/Dockerfile
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_article.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_book.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/src/Constants/Misc.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/HtmlSanitizer.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/MediaWysiwygFilter.php
Labels: backend, migration

#1619 EICNET-2510: Add tags migration.
  config/sync/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_tag.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_tag.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/VocabTag.php
Labels: backend, migration

#1623 EICNET-2512: Ignore duplicated entries when migrating path redirects from URL alias
  config/sync/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/src/Plugin/migrate/process/DuplicatedRedirect.php
Labels: backend, migration
