Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-11, with the labels that each got.

#2048 Feature/eicnet 2847 story type
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.mail_teaser.yml
  config/sync/core.entity_view_display.node.story.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.story.field_vocab_story_type.yml
  config/sync/field.storage.node.field_vocab_story_type.yml
  config/sync/language.content_settings.taxonomy_term.story_type.yml
  config/sync/search_api.index.global.yml
  config/sync/taxonomy.vocabulary.story_type.yml
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/StoryGenerator.php
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/TaxonomyGenerator.php
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
  lib/modules/eic_taxonomy/eic_taxonomy.info.yml
  lib/modules/eic_taxonomy/eic_taxonomy.install
Labels: backend

#2055 Feature/eicnet 2928 block base64 images
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/editor.editor.basic_text.yml
  config/sync/editor.editor.filtered_html.yml
  config/sync/editor.editor.full_html.yml
Labels: backend

#2057 Feature/eicnet 2714 block node add page
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_content/eic_content.services.yml
  lib/modules/eic_content/src/Routing/RouteSubscriber.php
  lib/modules/eic_groups/src/ForbiddenOrphanContentTypes.php
Labels: backend

#2058 EICNET-2728: Make topics mandatory for Group GT.
  config/sync/field.field.group.group.field_vocab_topics.yml
Labels: backend

#2060 Feature/eicnet 2926 archived group join
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/ArchivedRouteAccessCheck.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
Labels: backend

#2056 EICNET-2615: Add parent_group_title in the meta & OG title of nodes within a group
  lib/modules/eic_groups/eic_groups.module
Labels: enhancement, backend

#2063 EICNET-2934: [Group access] Issue with groups access
  config/sync/core.extension.yml
Labels: bug, backend

#2053 EICNET-2739: [User profile] remove confusing text
  config/sync/field.field.profile.member.field_vocab_topic_interest.yml
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
Labels: enhancement, backend

#2061 EICNET-2929: Duplicated item in news and stories in the email digest
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: bug, backend

#2062 EICNET-2664: As SA/SCM, I want an option in the CMS so that I can manage the roles of the platform users
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_user/src/Hooks/FormAlter.php
Labels: enhancement, backend

#2066 EICNET-2919: Solr crash when indexing a Story
  config/sync/search_api.index.global.yml
Labels: bug, backend

#2067 Feature/eicnet 2920 cancel user account
  lib/modules/eic_admin/eic_admin.module
  lib/modules/eic_groups/src/Hooks/CronOperations.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
Labels: backend

#2070 Feature/eicnet 2811 anonymous invitations
  config/sync/group.content_type.event-group_invitation.yml
  config/sync/group.content_type.group-group_invitation.yml
  config/sync/group.content_type.organisation-group_invitation.yml
  lib/modules/eic_groups/src/Hooks/GroupTokens.php
Labels: backend

#2071 Hotfix/eicnet 2811 anonymous invitations
  config/sync/group.content_type.event-group_invitation.yml
  config/sync/group.content_type.group-group_invitation.yml
  config/sync/group.content_type.organisation-group_invitation.yml
  lib/modules/eic_groups/src/Hooks/GroupTokens.php
Labels: backend

#2072 EICNET-2924: Add missing 'edit memberships' permission.
  lib/modules/eic_groups/eic_groups.install
Labels: backend

#2050 Feature/eicnet 2874 drupal core upgrade
  composer.json
  composer.lock
  composer.patches.json
  config/sync/cas_mock_server.settings.yml
  config/sync/core.entity_view_display.media.document.media_library.yml
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.media.image.full.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.photo.default.yml
  config/sync/core.entity_view_display.media.photo.media_library.yml
  config/sync/core.entity_view_display.media.remote_video.default.yml
  config/sync/core.entity_view_display.media.remote_video.media_library.yml
  config/sync/core.entity_view_display.media.video.media_library.yml
  config/sync/core.extension.yml
  config/sync/eic_groups.settings.yml
  config/sync/search_api.index.global.yml
  config/sync/system.site.yml
  config/sync/views.view.comment.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
  config/sync/views.view.user_admin_people.yml
Labels: backend
