Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-04, with the labels that each got.

#1351 [EICNET-2060] add url on item in notif management
  lib/themes/eic_community/react/components/Block/NotifManagement/components/RowNotif.js
Labels: frontend

#1348 [EICNET-2057] remove mobile menu event
  lib/themes/eic_community/eic_community.libraries.yml
  lib/themes/eic_community/js/common/drupal.ecl.js
  lib/themes/eic_community/js/common/overides.js
Labels: frontend

#1344 EICNET-899: Migration of users (phase 2)
  config/sync/migrate_plus.migration.upgrade_d7_user.yml
  config/sync/migrate_plus.migration.upgrade_d7_user_to_profile.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_to_profile.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/UserWithSMEDIds.php
Labels: backend

#1353 EICNET-284: Migrate "document" media type (phase 2)
  config/sync/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/FileCompleteWithSMEDIds.php
Labels: backend

#1340 [EICNET] improve Front end navigation
  lib/themes/eic_community/templates/html/html.html.twig
Labels: frontend

#1365 EICNET-2208: Add targeted_markets migration.
  config/sync/migrate_plus.migration.smed_target_markets_lvl1.yml
  config/sync/migrate_plus.migration.smed_target_markets_lvl2.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_target_markets_lvl1.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_target_markets_lvl2.yml
Labels: backend

#1359 [EICNET-2274]fix: Add correct group id to highlight content from
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
Labels: react

#1364 EICNET-2279: Patch Drupal core to ignore missing files instead of fail.
  composer.lock
  composer.patches.json
  config/sync/migrate_plus.migration.upgrade_d7_file.yml
  config/sync/migrate_plus.migration.upgrade_d7_file_private.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_private.yml
Labels: backend, migration

#1379 [EICNET-2061] Notification fixes related to group & group contents
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
Labels: enhancement, backend

#1377 [EICNET-1449] Video on demand
  config/sync/core.extension.yml
  config/sync/field.storage.media.field_media_video_file.yml
  docker/php/dev.ini
  e2e/cypress/integration/vod/vod.js
  lib/modules/eic_default_content/src/Generator/CoreGenerator.php
  lib/modules/eic_vod/eic_vod.info.yml
  lib/modules/eic_vod/eic_vod.routing.yml
  lib/modules/eic_vod/eic_vod.services.yml
  lib/modules/eic_vod/src/Controller/VODController.php
  lib/modules/eic_vod/src/EicVodServiceProvider.php
  lib/modules/eic_vod/src/Service/VODClient.php
  lib/modules/eic_vod/src/Service/VODFileService.php
  lib/modules/eic_vod/src/StreamWrapper/RemoteStreamWrapperTrait.php
  lib/modules/eic_vod/src/StreamWrapper/VODStream.php
  lib/themes/eic_community/eic_community.libraries.yml
  lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
  lib/themes/eic_community/includes/preprocess/field/field--media--video.inc
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/react/components/Block/StreamVideo/entrypoint.js
  lib/themes/eic_community/react/components/Block/StreamVideo/index.js
  lib/themes/eic_community/sass/components/_media-container.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/_videojs.scss
  lib/themes/eic_community/templates/field/field--field-video-media.html.twig
  lib/themes/eic_community/webpack.mix.js
  web/sites/default/default.settings.local.php
Labels: backend, frontend

#1374 [EICNET-2015]feat: Do not create/send messages during migrations
  lib/modules/eic_messages/eic_messages.services.yml
  lib/modules/eic_messages/src/Service/MessageBus.php
  lib/modules/eic_migrate/eic_migrate.info.yml
  lib/modules/eic_migrate/eic_migrate.module
  lib/modules/eic_migrate/src/Commands/MigrateToolsOverrideCommands.php
  lib/modules/eic_migrate/src/EicMigrateServiceProvider.php
  lib/modules/eic_migrate/src/Plugin/Validation/Constraint/MigrationRunningMessagesConstraint.php
  lib/modules/eic_migrate/src/Plugin/Validation/Constraint/MigrationRunningMessagesConstraintValidator.php
Labels: enhancement, backend

#1385 [EICNET-2291]fix: Authorize user to view their unpublished content
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.event-member.yml
Labels: backend

#1373 [EICNET-2060]chore: Sort by created DESC
  lib/modules/eic_user/src/Controller/MySettingsController.php
Labels: enhancement, backend

#1380 [EICNET-2296] fix front end on media form
  lib/themes/eic_community/sass/overrides/_media-library.scss
Labels: frontend

#1370 EICNET-2196: Update book page URL pattern and add missing variables to the Theme (Rework)
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/themes/eic_community/sass/components/_navigation-list.scss
Labels: backend

#1371 EICNET-2034: Group type notification - group deleted (rework)
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: bug, backend

#1389 EICNET-XXXX: Replace topics statistics documents from media to node.
  lib/modules/eic_topics/src/TopicsManager.php
Labels: bug, backend

#1368 Feature/eicnet 1828 organisation type access
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVisibility.php
Labels: backend

#1383 [EICNET-1970]fix: Prefilter the group book page from search API and add groups in drafts
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1384 [EICNET-2301] add group invitation cancellation
  lib/themes/eic_community/.prettierrc
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/patterns/compositions/confirmations/cancel_user_invitation.html.twig
  lib/themes/eic_community/sass/components/_button.scss
  lib/themes/eic_community/styleguide/bundles/discussion.stories.js
  lib/themes/eic_community/styleguide/bundles/group.stories.js
  lib/themes/eic_community/styleguide/bundles/project.stories.js
  lib/themes/eic_community/styleguide/bundles/story.stories.js
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
Labels: frontend

#1391 [EICNET-2313]fix: do not always put parent published to true for group
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
Labels: backend

#1388 [EICNET] refactor featured content expand collapse
  lib/themes/eic_community/patterns/compositions/featured-content-collapse-expand.html.twig
  lib/themes/eic_community/patterns/compositions/organisation/organisation.details.html.twig
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: frontend

#1396 [EICNET] Upload cypress artifacts no mather what
  .gitlab-ci.yml
Labels: enhancement, cypress

#1355 EICNET-1316: Node 'Document' migration (phase 2)
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_document.yml
Labels: backend

#1372 EICNET-1321: Node 'Wiki page' migration (phase 2)
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/field.field.node.wiki_page.field_language.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
Labels: backend

#1366 EICNET-1315: Node 'Discussion' migration (phase 2)
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.discussion.default.yml
  config/sync/core.entity_view_display.node.discussion.teaser.yml
  config/sync/core.entity_view_display.node.news.default.yml
  config/sync/core.entity_view_display.node.news.teaser.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/field.field.node.discussion.field_language.yml
  config/sync/field.field.node.news.field_language.yml
  config/sync/field.field.node.wiki_page.field_language.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/src/Plugin/migrate/process/MediaWysiwygFilter.php
Labels: backend

#1361 EICNET-2158: CK editor additional options for D9
  composer.json
  composer.libraries.json
  composer.lock
  composer.patches.json
  config/sync/core.extension.yml
  config/sync/editor.editor.basic_text.yml
  config/sync/editor.editor.filtered_html.yml
  config/sync/editor.editor.full_html.yml
  config/sync/filter.format.basic_text.yml
  config/sync/filter.format.filtered_html.yml
  config/sync/filter.format.full_html.yml
Labels: backend

#1408 EICNET-2291: Fix group content view access.
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
Labels: bug, backend

#1403 [EICNET-2029]feat: Notify all SCM/SA for reminder of group waiting for approval
  config/sync/core.entity_form_display.message.notify_group_wait_approval.default.yml
  config/sync/core.entity_view_display.message.notify_group_wait_approval.default.yml
  config/sync/core.entity_view_display.message.notify_group_wait_approval.mail_body.yml
  config/sync/core.entity_view_display.message.notify_group_wait_approval.mail_subject.yml
  config/sync/field.field.message.notify_group_wait_approval.field_event_executing_user.yml
  config/sync/field.field.message.notify_group_wait_approval.field_group_ref.yml
  config/sync/language/en/message.template.notify_group_wait_approval.yml
  config/sync/message.template.notify_group_wait_approval.yml
  lib/modules/eic_groups/src/Hooks/CronOperations.php
  web/sites/default/default.settings.local.php
Labels: backend

#1407 [EICNET-1851] add icon for file type pdf
  lib/themes/eic_community/images/sprite/custom/document_pdf.svg
  lib/themes/eic_community/patterns/components/filelist.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
Labels: frontend

#1393 Feature/eicnet 191 group migration
  composer.lock
  composer.patches.json
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  lib/modules/eic_migrate/eic_migrate.services.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/GroupFeatures.php
Labels: backend, migration

#1404 EICNET-2034: Group type notification - group deleted (rework 2)
  config/sync/language/en/message.template.notify_delete_request_accepted.yml
  config/sync/language/en/message.template.notify_group_deleted.yml
  config/sync/message.template.notify_delete_request_accepted.yml
  config/sync/message.template.notify_group_deleted.yml
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: bug, backend

#1417 [EICNET-1449]fix: Clean file names
  lib/modules/eic_vod/src/Service/VODFileService.php
Labels: enhancement, backend

#1402 EICNET-2078: Migration of comments (phase 2)
  config/sync/migrate_plus.migration.upgrade_d7_comment.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml
Labels: backend, migration

#1410 EICNET-1445: File download counter migration
  config/sync/migrate_plus.migration.upgrade_d7_file_download_counter.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_download_counter.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/FileDownloadCounter.php
Labels: backend, migration

#1412 EICNET-1444: Statistics node counter migration
  config/sync/migrate_plus.migration.upgrade_d7_node_view_counter.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_view_counter.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/NodeViewCounter.php
Labels: backend, migration

#1416 [EICNET-2036]feat: If a TU is promoted to group-admin, send a notify message
  config/sync/core.entity_form_display.message.notify_group_admin_promoted.default.yml
  config/sync/core.entity_view_display.message.notify_group_admin_promoted.default.yml
  config/sync/core.entity_view_display.message.notify_group_admin_promoted.mail_body.yml
  config/sync/core.entity_view_display.message.notify_group_admin_promoted.mail_subject.yml
  config/sync/field.field.message.notify_group_admin_promoted.field_group_owner.yml
  config/sync/field.storage.message.field_group_owner.yml
  config/sync/language/en/message.template.notify_group_admin_promoted.yml
  config/sync/message.template.notify_group_admin_promoted.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
Labels: backend

#1395 EICNET-2315: GO can not access Members Pending page
  lib/modules/eic_groups/eic_groups.install
  lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
  lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
Labels: bug, backend

#1425 EICNET-1438: Message migration (stream messages)
  config/sync/migrate_plus.migration.upgrade_d7_message_stream.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_message_stream.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/MessageStreamSource.php
Labels: backend, migration

#1381 EICNET-2294: Migrate Event nodes
  config/sync/migrate_plus.migration.upgrade_d7_comment.yml
  config/sync/migrate_plus.migration.upgrade_d7_message_stream.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_message_stream.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/MessageStreamSource.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/NodeCompleteWithSMEDIds.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/NodeEventCompleteWithSMEDIds.php
Labels: enhancement, backend, migration

#1426 EICNET-2032: Group type notification - group blocked (improvements)
  config/sync/language/en/message.template.notify_block_request_accepted.yml
  config/sync/message.template.notify_block_request_accepted.yml
Labels: backend

#1424 [EICNET-2232]feat: Send message correctly formated for contact user
  config/sync/core.entity_form_display.message.notify_contact_user.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_user.mail_subject.yml
  config/sync/field.field.message.notify_contact_user.field_body.yml
  config/sync/field.field.message.notify_contact_user.field_sender.yml
  config/sync/field.field.message.notify_contact_user.field_subject.yml
  config/sync/field.storage.message.field_body.yml
  config/sync/field.storage.message.field_sender.yml
  config/sync/field.storage.message.field_subject.yml
  config/sync/language/en/message.template.notify_contact_user.yml
  config/sync/message.template.notify_contact_user.yml
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: backend

#1419 EICNET-1443: Path redirect migration
  config/sync/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
  config/sync/migrate_plus.migration.upgrade_d7_group_path_redirect.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_path_redirect.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_url_alias_to_path_redirect.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/GroupOldPathRedirect.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/GroupPathRedirect.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/PathRedirect.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
Labels: backend, migration

#1423 EICNET-1313: Node 'Photo' migration (improvements)
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
Labels: backend, migration

#1378 [EICNET-1320]feat: Add smed integrations for field_vocab_geo
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.teaser.yml
  config/sync/field.field.node.story.field_language.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_article.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_article.yml
Labels: backend

#1427 EICNET-2370: Allow SA/SCM to bypass groups workflow permissions.
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#1428 [EICNET-2362]feat: Send email with self copy to current user
  config/sync/core.entity_form_display.message.notify_contact_user_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_subject.yml
  config/sync/field.field.message.notify_contact_user_copy.field_body.yml
  config/sync/field.field.message.notify_contact_user_copy.field_subject.yml
  config/sync/language/en/message.template.notify_contact_user_copy.yml
  config/sync/message.template.notify_contact_user.yml
  config/sync/message.template.notify_contact_user_copy.yml
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: backend

#1422 [EICNET-2037]feat: Update message for group/event request
  config/sync/core.entity_form_display.message.notify_new_member_joined.default.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.default.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.mail_body.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.mail_subject.yml
  config/sync/field.field.message.notify_new_member_joined.field_related_organisation.yml
  config/sync/field.storage.message.field_related_organisation.yml
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_new_member_joined.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_new_member_joined.yml
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
Labels: backend

#1399 News & Stories - fix inconsistenties FE vs design
  config/sync/user.role.anonymous.yml
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/patterns/compositions/editorial-header.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/featured-stories.html.twig
  lib/themes/eic_community/patterns/compositions/featured-topics.html.twig
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/compositions/_editorial-header.scss
  lib/themes/eic_community/templates/content/node--story--full.html.twig
  lib/themes/eic_community/templates/layout/page--node--story.html.twig
Labels: bug, backend, frontend

#1433 Release 0.36.0
  config/sync/core.entity_form_display.message.notify_contact_user_copy.default.yml
  config/sync/core.entity_form_display.message.notify_new_member_joined.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.default.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.mail_body.yml
  config/sync/core.entity_view_display.message.notify_new_member_joined.mail_subject.yml
  config/sync/field.field.message.notify_contact_user_copy.field_body.yml
  config/sync/field.field.message.notify_contact_user_copy.field_subject.yml
  config/sync/field.field.message.notify_new_member_joined.field_related_organisation.yml
  config/sync/field.storage.message.field_related_organisation.yml
  config/sync/language/en/message.template.notify_contact_user_copy.yml
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_new_member_joined.yml
  config/sync/message.template.notify_contact_user.yml
  config/sync/message.template.notify_contact_user_copy.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_new_member_joined.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
  lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
  lib/modules/eic_user/src/Plugin/Block/NotificationsSettingsBlock.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/patterns/compositions/editorial-header.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/featured-stories.html.twig
  lib/themes/eic_community/patterns/compositions/featured-topics.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/sass/components/_form.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/compositions/_editorial-header.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/templates/content/node--story--full.html.twig
  lib/themes/eic_community/templates/layout/page--node--story.html.twig
Labels: backend

#1161 Feature/eicnet 1811 eu login
  composer.json
  composer.lock
  composer.patches.json
  config/development/eic_user_login.settings.yml
  config/sync/cas.settings.yml
  config/sync/cas_mock_server.settings.yml
  config/sync/config_ignore.settings.yml
  config/sync/config_split.config_split.development.yml
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.compact.yml
  config/sync/core.entity_view_display.user.user.default.yml
  config/sync/core.entity_view_display.user.user.teaser.yml
  config/sync/core.extension.yml
  config/sync/oe_authentication.settings.yml
  config/sync/views.view.user_admin_people.yml
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/modules/eic_user/config/install/field.field.user.user.field_message_from_service.yml
  lib/modules/eic_user/config/install/field.field.user.user.field_updated_profile_by_service.yml
  lib/modules/eic_user/config/install/field.field.user.user.field_updated_profile_by_user.yml
  lib/modules/eic_user/config/install/field.field.user.user.field_user_status.yml
  lib/modules/eic_user/config/install/field.storage.user.field_message_from_service.yml
  lib/modules/eic_user/config/install/field.storage.user.field_updated_profile_by_service.yml
  lib/modules/eic_user/config/install/field.storage.user.field_updated_profile_by_user.yml
  lib/modules/eic_user/config/install/field.storage.user.field_user_status.yml
  lib/modules/eic_user/modules/eic_user_login/config/install/eic_user_login.settings.yml
  lib/modules/eic_user/modules/eic_user_login/config/schema/eic_user_login.schema.yml
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.info.yml
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.install
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.links.menu.yml
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.module
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.routing.yml
  lib/modules/eic_user/modules/eic_user_login/eic_user_login.services.yml
  lib/modules/eic_user/modules/eic_user_login/src/Constants/SmedUserStatuses.php
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
  lib/modules/eic_user/modules/eic_user_login/src/Exception/SmedUserLoginException.php
  lib/modules/eic_user/modules/eic_user_login/src/Form/SettingsForm.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserConnection.php
  lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
  lib/modules/eic_webservices/eic_webservices.module
  lib/modules/eic_webservices/src/Hooks/FormOperations.php
  patches/cas/cas-dispatch_EVENT_PRE_LOGIN_before_active_check.patch
Labels: backend

#1435 [EICNET-2233]feature: if send_copy is checked, send a self copy
  config/sync/core.entity_form_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_subject.yml
  config/sync/field.field.message.notify_contact_global_copy.field_body.yml
  config/sync/field.field.message.notify_contact_global_copy.field_sender.yml
  config/sync/field.field.message.notify_contact_global_copy.field_subject.yml
  config/sync/message.template.notify_contact_global_copy.yml
  lib/modules/eic_contact/eic_contact.module
Labels: backend

#1282 EICNET-2109: Patch views_Export_module to support S3 storage.
  composer.lock
  composer.patches.json
Labels: backend

#1434 [EICNET-2372]feature: Send confirmation notification to the current user that sent the contact form
  config/sync/core.entity_form_display.message.notify_contact_global_confirm.default.yml
  config/sync/core.entity_form_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_global_confirm.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.default.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_body.yml
  config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_subject.yml
  config/sync/field.field.message.notify_contact_global_confirm.field_sender.yml
  config/sync/field.field.message.notify_contact_global_confirm.field_subject.yml
  config/sync/field.field.message.notify_contact_global_copy.field_body.yml
  config/sync/field.field.message.notify_contact_global_copy.field_sender.yml
  config/sync/field.field.message.notify_contact_global_copy.field_subject.yml
  config/sync/language/en/message.template.notify_contact_global_confirm.yml
  config/sync/language/en/message.template.notify_mt_contact_global.yml
  config/sync/message.template.notify_contact_global_confirm.yml
  config/sync/message.template.notify_contact_global_copy.yml
  lib/modules/eic_contact/eic_contact.module
Labels: backend

#1430 EICNET-2281: Not authorized and wrong link in status message after creating gallery
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/PathautoGenerator.php
Labels: bug, backend

#1409 [EICNET-2060] fix search enter reload the page and fix zoom on input on IOS
  lib/themes/eic_community/react/components/Block/NotifManagement/index.js
  lib/themes/eic_community/sass/compositions/_my-notifications.scss
  lib/themes/eic_community/sass/compositions/_subnavigation.scss
Labels: frontend

#1418 Feature/eicnet 1538 organisations migration
  config/sync/core.entity_form_display.group.organisation.default.yml
  config/sync/core.entity_view_display.group.organisation.default.yml
  config/sync/field.field.group.organisation.field_vocab_geo_selling.yml
  config/sync/field.storage.group.field_vocab_geo_selling.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  config/sync/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_organisation_types.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_organisation_types.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/GroupFeatures.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/FieldValue.php
Labels: backend, migration

#1441 [EICNET-2382]chore: Add create entity CTAs on global overview pages
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
  lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc
Labels: enhancement, backend

#1420 [EICNET-2091] add last page in pagination on mobile
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
  lib/themes/eic_community/sass/compositions/_pagination.scss
Labels: frontend, react

#1444 [EICNET-2211]feat: Hide news/stories from organisation as anonymous
  e2e/cypress/integration/articles/articles.spec.js
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1440 [EICNET-2267] 2nd indent on comments also triggers a message for parent comment which is 2 levels higher
  config/sync/language/en/message.template.sub_new_comment_on_content.yml
  config/sync/language/en/message.template.sub_new_comment_reply.yml
  config/sync/message.template.sub_new_comment_on_content.yml
  config/sync/message.template.sub_new_comment_reply.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
Labels: enhancement, backend

#1448 [EICNET-2385] set viewport height to min 100vh
  lib/themes/eic_community/patterns/layout/base.html.twig
  lib/themes/eic_community/sass/compositions/_4xx.scss
  lib/themes/eic_community/sass/core/_viewport.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/templates/layout/page--4xx.html.twig
Labels: frontend

#1438 [EICNET-688] Fix entity tree widget autocomplete
  lib/themes/eic_community/react/components/Field/EntityTree/Result/Search.js
Labels: frontend, react

#1452 [EICNET-2360]chore: Display the overview message block on global events
  config/sync/context.context.group_event_homepage.yml
  lib/modules/eic_default_content/src/Generator/TaxonomyGenerator.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
Labels: enhancement, backend

#1453 [EICNET]feat: Add a job to collect an SBOM file
  .gitlab-ci.yml
Labels: enhancement

#1460 [EICNET-2362]fix: add quote to wysiwyg to respect design in message
  config/sync/editor.editor.filtered_html.yml
  config/sync/editor.editor.full_html.yml
  config/sync/language/en/message.template.notify_contact_global_copy.yml
  config/sync/language/en/message.template.notify_contact_user_copy.yml
  config/sync/message.template.notify_contact_user_copy.yml
  config/sync/migrate_plus.migration.upgrade_d7_comment.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
Labels: backend

#1458 [EICNET-2020]fix: Add type machine name instead of type label
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_group_request_submitted.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_group_request_submitted.yml
Labels: backend

#1456 [EICNET-2361]fix: Set correct redirect url to contact user
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_group_request_submitted.yml
  config/sync/language/en/message.template.notify_mt_contact_global.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_group_request_submitted.yml
  config/sync/message.template.notify_mt_contact_global.yml
Labels: backend

#1454 [EICNET]chore: Add default settings for k8s
  web/sites/default/default.settings.k8s.php
Labels: backend

#1459 [EICNET-2105]chore: Hide contributors on comments for news
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
Labels: backend

#1446 [EICNET-2386]chore: Add an 'edit members' link to group management dropdown
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: enhancement, backend

#1449 [EICNET-2232]fix: Add correct user link to contact in the email
  config/sync/language/en/message.template.notify_contact_user.yml
  config/sync/message.template.notify_contact_user.yml
Labels: backend

#1468 [EICNET-2397] Display moderation state as tag for groups
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: enhancement, backend, frontend

#1466 Feature/eicnet 191 event group migration
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  lib/modules/eic_migrate/src/Plugin/migrate/process/GroupFeatures.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/NodeEventCompleteWithSMEDIds.php
Labels: backend, migration

#1471 [EICNET-2080]chore: Move the account header component into a plugin block
  lib/modules/eic_user/eic_user.module
  lib/modules/eic_user/src/Plugin/Block/AccountHeaderBlock.php
  lib/modules/eic_user/templates/account-header-block.html.twig
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/patterns/compositions/global-header.html.twig
Labels: enhancement, backend

#1464 [EICNET-2399]fix: Replace some deprecated codes
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_overviews/eic_overviews.module
  lib/modules/eic_overviews/src/Form/OverviewPageForm.php
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_theme_helper/eic_theme_helper.module
  lib/modules/eic_theme_helper/src/Plugin/Field/FieldFormatter/MediaThumbnailUrlFormatter.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/eic_community.theme
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/includes/preprocess/preprocess.inc
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
Labels: enhancement, backend

#1465 [EICNET-2369]fix: Add underline on every link in messages
  config/sync/language/en/message.template.like_comment.yml
  config/sync/language/en/message.template.notify_delete_request_denied.yml
  config/sync/language/en/message.template.notify_group_membership_pending.yml
  config/sync/language/en/message.template.notify_new_deletion_request.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_admin.yml
  config/sync/language/en/message.template.notify_transfer_owner_req_accept.yml
  config/sync/message.template.like_comment.yml
  config/sync/message.template.like_content.yml
  config/sync/message.template.like_media.yml
  config/sync/message.template.log_group_state_change.yml
  config/sync/message.template.log_group_visibility_change.yml
  config/sync/message.template.log_masquerade_user.yml
  config/sync/message.template.log_req_owner_transfer_accepted.yml
  config/sync/message.template.notify_block_request_accepted.yml
  config/sync/message.template.notify_contact_user.yml
  config/sync/message.template.notify_content_approved.yml
  config/sync/message.template.notify_content_needs_review.yml
  config/sync/message.template.notify_content_ready_for_review.yml
  config/sync/message.template.notify_content_status_changed.yml
  config/sync/message.template.notify_delete_request_accepted.yml
  config/sync/message.template.notify_delete_request_archived.yml
  config/sync/message.template.notify_delete_request_denied.yml
  config/sync/message.template.notify_group_access_change.yml
  config/sync/message.template.notify_group_admin_promoted.yml
  config/sync/message.template.notify_group_deleted.yml
  config/sync/message.template.notify_group_membership_pending.yml
  config/sync/message.template.notify_group_re_published.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_group_request_submitted.yml
  config/sync/message.template.notify_group_requested.yml
  config/sync/message.template.notify_group_wait_approval.yml
  config/sync/message.template.notify_membership_request_rej.yml
  config/sync/message.template.notify_new_archival_request.yml
  config/sync/message.template.notify_new_deletion_request.yml
  config/sync/message.template.notify_new_member_joined.yml
  config/sync/message.template.notify_new_membership_request.yml
  config/sync/message.template.notify_new_transfer_owner_req.yml
  config/sync/message.template.notify_transf_owner_expire_admin.yml
  config/sync/message.template.notify_transf_owner_expire_owner.yml
  config/sync/message.template.notify_transfer_owner_req_accept.yml
  config/sync/message.template.notify_transfer_owner_req_cancel.yml
  config/sync/message.template.notify_transfer_owner_req_denied.yml
  config/sync/message.template.notify_user_tagged_on_comment.yml
  config/sync/message.template.notify_welcome_user_to_group.yml
  config/sync/message.template.sub_new_comment_on_content.yml
  config/sync/message.template.sub_new_comment_reply.yml
Labels: backend

#1472 [EICNET-2404]fix: Keep selected values for entity tree widget on form error
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
Labels: backend

#1474 [EICNET-2395]feat: Disable cache on views based on search_api
  config/sync/views.view.groups_homepage.yml
  config/sync/views.view.taxonomy_related_content.yml
Labels: backend

#1457 [EICNET-2320]feat: Add drupal/raven and sentry variables
  .env.docker
  composer.json
  composer.lock
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  config/sync/raven.settings.yml
Labels: enhancement
