Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-03, with the labels that each got.

#1203 EICNET-2116: News articles within organisation can be promoted on homepage
  config/sync/views.view.latest_news_and_stories.yml
  lib/modules/eic_default_content/src/Generator/NewsGenerator.php
  lib/modules/oec_group_flex/oec_group_flex.module
  lib/modules/oec_group_flex/src/Plugin/views/filter/GroupVisibility.php
Labels: backend

#1201 EICNET-1991: Make image fields optional for organisations.
  config/sync/field.field.group.organisation.field_header_visual.yml
  config/sync/field.field.group.organisation.field_thumbnail.yml
Labels: backend

#1202 [EICNET-1985]fix: If user is not logged in, do not authorize organisations
  lib/modules/eic_groups/eic_groups.module
Labels: backend

#1210 [EICNET-1961]feat: Create the "following" activities overview
  config/sync/context.context.following.yml
  config/sync/context.context.interests.yml
  config/sync/context.context.my_profile.yml
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/eic_user.services.yml
  lib/modules/eic_user/src/Controller/MyProfileController.php
  lib/modules/eic_user/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_user/src/Plugin/Block/MyProfileHeaderBlock.php
Labels: backend

#1207 [EICNET-1742]feat: Implement template + refactor about page organisation
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/templates/group/group--organisation--about-page.html.twig
Labels: backend

#1208 [EICNET-2111]feat: Add highlight comment parameter on the URL
  config/sync/core.entity_form_display.message.notify_user_tagged_on_comment.default.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.default.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_body.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_subject.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_group_events.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_members.yml
  config/sync/eic_groups.group_features.eic_groups_anchor_news.yml
  config/sync/field.field.group.organisation.field_header_visual.yml
  config/sync/field.field.group.organisation.field_thumbnail.yml
  config/sync/field.field.message.notify_user_tagged_on_comment.field_referenced_node.yml
  config/sync/language/en/message.template.notify_user_tagged_on_comment.yml
  config/sync/message.template.notify_user_tagged_on_comment.yml
  config/sync/search_api.index.global.yml
  config/sync/views.view.groups_homepage.yml
  config/sync/views.view.latest_news_and_stories.yml
  lib/modules/eic_default_content/src/Generator/NewsGenerator.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/GroupPageAccessChecker.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/modules/eic_messages/src/Service/CommentMessageCreator.php
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupEvent.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/oec_group_flex/oec_group_flex.module
  lib/modules/oec_group_flex/src/Plugin/views/filter/GroupVisibility.php
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/entrypoint.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js
Labels: backend, frontend, react

#1199 EICNET-1940: Email notification for user tagging in comments (improvements - email notification)
  config/sync/core.entity_form_display.message.notify_user_tagged_on_comment.default.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.default.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_body.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_subject.yml
  config/sync/field.field.message.notify_user_tagged_on_comment.field_referenced_node.yml
  config/sync/language/en/message.template.notify_user_tagged_on_comment.yml
  config/sync/message.template.notify_user_tagged_on_comment.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/modules/eic_media/eic_media.module
  lib/modules/eic_messages/src/Service/CommentMessageCreator.php
  lib/themes/eic_community/includes/preprocess/comments/comment.inc
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/entrypoint.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: backend

#1205 [EICNET-1746]feat: Add field search api event weight state + teaser event
  config/sync/context.context.following.yml
  config/sync/search_api.index.global.yml
  config/sync/views.view.organisation_content.yml
  config/sync/workflows.workflow.group_wiki.yml
  lib/modules/eic_events/src/Constants/Event.php
  lib/modules/eic_events/src/Plugin/search_api/processor/EventWeightState.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessor.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php
  lib/themes/eic_community/data/teaser/event.data.js
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/patterns/compositions/event/event.teaser.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
  lib/themes/eic_community/sass/components/_content-type-indicator.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/templates/content/node--event--teaser.html.twig
Labels: backend

#1213 EICNET-2123: Remove old workflow configurations
  config/sync/workflows.workflow.group_wiki.yml
Labels: backend

#1198 EICNET-2097: Teaser image height fix.
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1204 EICNET-1728: Fix styling of progress bar.
  lib/themes/eic_community/sass/components/_progress.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: frontend

#1192 EICNET-2114: Fix permission tab in Event about page
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: bug, backend

#1219 [EICNET]fix: Set type as multi array in teaser event
  lib/themes/eic_community/includes/preprocess/groups/event.inc
Labels: backend

#1218 [EICNET-2129]fix: put body of about page as raw
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/patterns/compositions/extended-list/extended-list-item.html.twig
Labels: backend

#1200 EICNET-2110: Share content: make sure users can share to the groups they belong only
  config/sync/views.view.admin_groups.yml
  config/sync/workflows.workflow.groups.yml
  lib/modules/eic_groups/modules/eic_share_content/eic_share_content.services.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_groups/src/GroupsModerationHelper.php
  lib/themes/eic_community/includes/preprocess/common.inc
Labels: enhancement, backend

#1217 Feature/eicnet 2115 add missing bread crumbs inside groups
  lib/modules/eic_flags/src/Plugin/Flag/EntityFlagType.php
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/EICGroupsHelperInterface.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/modules/eic_groups/src/Hooks/Preprocess.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVisibility.php
Labels: backend

#1194 [EICNET]chore: Restore the PHP dockerfile
  docker-compose.yml
  docker/php/Dockerfile
Labels: backend

#1211 Feature/eicnet 1319 node share migration
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_share_to_group_content.yml
  lib/modules/eic_migrate/src/Plugin/migrate/process/NodeShareGroupContentType.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/OgMembership.php
Labels: backend

#1225 EICNET-2116: News articles within organisation can be promoted on homepage (rework)
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#1230 [EICNET-1962]feat: Implement method to prefilter some fields to avoid empty values
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
Labels: backend

#1234 [EICNET-1952]feat: Create my groups overview, filters, subnav menu item, ...
  config/sync/context.context.groups.yml
  config/sync/context.context.my_profile.yml
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: backend, react

#1231 [EICNET-2071] remove bg color on img in editorial header
  lib/themes/eic_community/sass/compositions/_editorial-header.scss
Labels: frontend

#1228 [EICNET-1991] change empty state image for organisation teaser
  lib/themes/eic_community/images/sprite/custom/organisation_circle.svg
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
Labels: frontend, react

#1232 EICNET-1493: Groups - Group owner in group teaser links to groups overview (rework)
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
Labels: bug, backend

#1224 EICNET-2134: Default workflow breaks group statistics
  lib/modules/eic_content/src/Constants/DefaultContentModerationStates.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#1197 [EICNET-1942]fix: Add cache context for HP actions and breadcrumbs activity feed
  lib/modules/eic_user/eic_user.services.yml
  lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php
  lib/modules/eic_user/src/Controller/MyProfileController.php
  lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php
  lib/modules/eic_user/src/Plugin/Block/UserHeaderBlock.php
  lib/modules/eic_user/templates/user-header-block.html.twig
  lib/themes/eic_community/includes/preprocess/theme/eic-content-actions.inc
Labels: backend

#1216 EICNET-2054: Help and guidance contact box: back-end
  config/sync/block_content.type.contact_box.yml
  config/sync/context.context.book_pages.yml
  config/sync/core.entity_form_display.block_content.contact_box.default.yml
  config/sync/core.entity_view_display.block_content.contact_box.default.yml
  config/sync/field.field.block_content.contact_box.body.yml
  config/sync/field.field.block_content.contact_box.field_cta_button.yml
  config/sync/field.field.block_content.contact_box.field_title.yml
  config/sync/field.storage.block_content.field_cta_button.yml
  config/sync/language.content_settings.block_content.contact_box.yml
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
  lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
  lib/modules/eic_deploy/eic_deploy.install
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/themes/eic_community/includes/preprocess/blocks/block--contact-box.inc
  lib/themes/eic_community/includes/preprocess/blocks/block.inc
  lib/themes/eic_community/patterns/components/navigation-list/navigation-list-items.html.twig
  lib/themes/eic_community/patterns/components/navigation-list/navigation-list.html.twig
  lib/themes/eic_community/templates/blocks/block--eic-contact-box-help-guindance.html.twig
  lib/themes/eic_community/templates/blocks/block--eic-content-book-navigation.html.twig
  lib/themes/eic_community/templates/layout/page--node--book.html.twig
  lib/themes/eic_community/templates/layout/page--node--wiki-page.html.twig
Labels: backend, frontend

#1240 [EICNET-1956]feat: Add events activities source type
  config/sync/context.context.events.yml
  config/sync/core.entity_form_display.group.event.default.yml
  config/sync/core.entity_view_display.group.event.default.yml
  config/sync/core.entity_view_display.group.event.small_teaser.yml
  config/sync/core.entity_view_display.group.event.teaser.yml
  config/sync/field.field.group.event.field_funding_source.yml
  config/sync/field.storage.group.field_funding_source.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_events/src/Plugin/search_api/processor/EventWeightState.php
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/templates/search-overview-block.html.twig
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend

#1242 [EICNET]fix: Encode the : char within REQUEST_URI
  lib/modules/eic_helper/src/StackMiddleware/HeaderMapper.php
Labels: backend

#1233 EICNET-2061: Unsubscribe/On-Off for notification settings
  config/sync/core.entity_form_display.message.sub_content_interest_published.default.yml
  config/sync/core.entity_form_display.message.sub_group_content_shared.default.yml
  config/sync/core.entity_form_display.message.sub_group_content_updated.default.yml
  config/sync/core.entity_form_display.message.sub_new_discussion_published.default.yml
  config/sync/core.entity_form_display.message.sub_new_group_content_published.default.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.default.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_content_interest_published.notify_weekly_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.default.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_weekly_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.default.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_group_content_updated.notify_weekly_digest.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.default.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_new_discussion_published.notify_weekly_digest.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.default.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.notify_daily_digest.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.notify_email_body.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.notify_email_subject.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.notify_monthly_digest.yml
  config/sync/core.entity_view_display.message.sub_new_group_content_published.notify_weekly_digest.yml
  config/sync/field.field.message.sub_content_interest_published.field_referenced_node.yml
  config/sync/field.field.message.sub_group_content_shared.field_group_ref.yml
  config/sync/field.field.message.sub_group_content_updated.field_group_ref.yml
  config/sync/field.field.message.sub_new_discussion_published.field_group_ref.yml
  config/sync/field.field.message.sub_new_group_content_published.field_group_ref.yml
  config/sync/field.storage.message.field_node_ref.yml
  lib/modules/eic_messages/eic_messages.info.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.services.yml
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Service/SubscriptionMessageChecker.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Service/SubscriptionMessageCreator.php
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Plugin/Block/NotificationsSettingsBlock.php
  lib/modules/eic_user/src/Service/NotificationSettingsManager.php
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#1245 [EICNET-2147]remove bump when we load more activity
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: frontend, react

#1226 add label in overview
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: frontend, react

#1243 [EICNET-2142] Organisation contact information: expandable addresses
  lib/themes/eic_community/patterns/compositions/organisation/organisation.details.html.twig
  lib/themes/eic_community/sass/compositions/_featured-list.scss
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: frontend

#1249 [EICNET-1942]fix: Replace my activity stream by my interests
  lib/modules/eic_user/src/Controller/MyProfileController.php
Labels: backend

#1212 EICNET-2113: Add 'administer members' permissions to relevant roles in Organisation group type
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.organisation-4c7e676f7.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
Labels: backend

#1253 EICNET-673: Add a field_message to the eic_moderated_workflow message templates to hold the revision log
  config/sync/core.entity_form_display.message.notify_content_approved.default.yml
  config/sync/core.entity_form_display.message.notify_content_needs_review.default.yml
  config/sync/core.entity_form_display.message.notify_content_ready_for_review.default.yml
  config/sync/core.entity_view_display.message.notify_content_approved.default.yml
  config/sync/core.entity_view_display.message.notify_content_approved.mail_body.yml
  config/sync/core.entity_view_display.message.notify_content_approved.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_content_needs_review.default.yml
  config/sync/core.entity_view_display.message.notify_content_needs_review.mail_body.yml
  config/sync/core.entity_view_display.message.notify_content_needs_review.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_content_needs_review.notify_email_body.yml
  config/sync/core.entity_view_display.message.notify_content_ready_for_review.default.yml
  config/sync/core.entity_view_display.message.notify_content_ready_for_review.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_content_ready_for_review.notify_email_body.yml
  config/sync/field.field.message.notify_content_approved.field_message.yml
  config/sync/field.field.message.notify_content_needs_review.field_message.yml
  config/sync/field.field.message.notify_content_ready_for_review.field_message.yml
  config/sync/field.storage.message.field_message.yml
  config/sync/language/en/message.template.notify_content_approved.yml
  config/sync/language/en/message.template.notify_content_needs_review.yml
  config/sync/language/en/message.template.notify_content_ready_for_review.yml
  config/sync/message.template.notify_content_approved.yml
  config/sync/message.template.notify_content_needs_review.yml
  config/sync/message.template.notify_content_ready_for_review.yml
  lib/modules/eic_default_content/src/Generator/NewsGenerator.php
  lib/modules/eic_default_content/src/Generator/OrganisationGenerator.php
  lib/modules/eic_default_content/src/Generator/StoryGenerator.php
  lib/modules/eic_moderation/config/install/field.field.message.notify_content_approved.field_message.yml
  lib/modules/eic_moderation/config/install/field.field.message.notify_content_needs_review.field_message.yml
  lib/modules/eic_moderation/config/install/field.field.message.notify_content_ready_for_review.field_message.yml
  lib/modules/eic_moderation/config/install/field.storage.message.field_message.yml
  lib/modules/eic_moderation/src/Hooks/EntityOperations.php
Labels: backend

#1254 EICNET-1993: Drupal default workflow improvements in message creations
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Hooks/FormOperations.php
Labels: bug, backend

#1250 [EICNET-1959]fix: Put parent breadcrumb for activities user
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php
Labels: backend

#1255 EICNET-2120: Make sure we don't show the group sharing link if user doesn't have access to it
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/themes/eic_community/includes/preprocess/common.inc
Labels: backend

#1256 EICNET-1940: Email notification for user tagging in comments (Fixes)
  config/sync/language/en/message.template.notify_user_tagged_on_comment.yml
  config/sync/message.template.notify_user_tagged_on_comment.yml
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: bug, backend

#1257 [EICNET] Enable UIT
  config/sync/core.extension.yml
  config/sync/locale.settings.yml
Labels: backend

#1252 EICNET-2072: Group overview with "view all" links below every content block have a faulty link
  config/sync/views.view.group_discussions.yml
  config/sync/views.view.group_documents.yml
  config/sync/views.view.group_events.yml
  config/sync/views.view.group_related_groups.yml
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: bug, backend

#1263 [EICNET-1952]fix: Replace method used to get unpublished groups where user is owner
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: backend

#1264 [EICNET-1953]fix: Set correct label for topic filter and search input
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/ContributionSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
Labels: backend, react

#1246 [EICNET-1746]feat: Add statistics to teaser event + correct country and team url fix
  config/sync/views.view.organisation_content.yml
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/patterns/compositions/featured-content-collection.html.twig
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: backend

#1272 [EICNET-1943] send icon_file_path to my activity view
  lib/modules/eic_user/templates/user-activity-subnavigation-block.html.twig
  lib/themes/eic_community/styleguide/bundles/member.stories.js
Labels: frontend

#1229 [EICNET-2138] add space between image and info in organization member teaser
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1261 EICNET-2169: Error when create a book page without assigning it to a book
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
Labels: bug, backend

#1271 EICNET-1818: Update CTA button URI of contact box block
  lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
  lib/modules/eic_deploy/eic_deploy.install
Labels: bug, backend

#1259 EICNET-2137: Deny access to GO/GA to group edit page for blocked groups.
  lib/modules/eic_groups/src/Access/GroupPageAccessChecker.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Routing/RouteSubscriber.php
Labels: backend

#1269 [EICNET-2176]chore: Move styles for user tagged messages within template
  config/sync/language/en/message.template.notify_user_tagged_on_comment.yml
  config/sync/message.template.notify_user_tagged_on_comment.yml
  lib/themes/eic_community/includes/preprocess/content/message.inc
  lib/themes/eic_community/templates/content/message.html.twig
  lib/themes/eic_community/templates/mimemail/mimemail-message--message-notify--notify-user-tagged-on-comment.html.twig
  lib/themes/eic_community/templates/mimemail/mimemail-message.html.twig
Labels: enhancement

#1265 [EICNET]chore: Clear indexes on local setup
  .env.docker
  Makefile
  docker-compose.yml
  docker/php/Dockerfile
Labels: enhancement, backend

#1267 [EICNET-2179]fix: Use new SOLR field for group topic name
  lib/modules/eic_topics/src/Constants/Topics.php
Labels: backend

#1274 EICNET-2003: Group approved banner "Click here" link improvements
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
  lib/themes/eic_community/templates/blocks/eic-group-moderated-message-box.html.twig
Labels: backend

#1275 EICNET-2184: Provide more clear subject in email notifications
  config/sync/language/en/message.template.notify_admin_group_new_member.yml
  config/sync/language/en/message.template.notify_group_access_change.yml
  config/sync/language/en/message.template.notify_group_admin_demoted.yml
  config/sync/language/en/message.template.notify_group_admin_promoted.yml
  config/sync/language/en/message.template.notify_group_archived.yml
  config/sync/language/en/message.template.notify_group_membership_pending.yml
  config/sync/language/en/message.template.notify_group_published.yml
  config/sync/language/en/message.template.notify_group_request_approved.yml
  config/sync/language/en/message.template.notify_group_request_submitted.yml
  config/sync/language/en/message.template.notify_group_requested.yml
  config/sync/language/en/message.template.notify_group_unpublished.yml
  config/sync/language/en/message.template.notify_membership_request_rej.yml
  config/sync/language/en/message.template.notify_welcome_user_to_group.yml
  config/sync/language/en/message.template.sub_content_interest_published.yml
  config/sync/language/en/message.template.sub_group_content_shared.yml
  config/sync/language/en/message.template.sub_group_content_updated.yml
  config/sync/language/en/message.template.sub_new_comment_on_content.yml
  config/sync/language/en/message.template.sub_new_comment_reply.yml
  config/sync/language/en/message.template.sub_new_content_recommendation.yml
  config/sync/language/en/message.template.sub_new_discussion_published.yml
  config/sync/language/en/message.template.sub_new_group_content_published.yml
  config/sync/language/en/message.template.sub_own_group_content_updated.yml
  config/sync/language/en/message.template.sub_site_event_pub_interest.yml
  config/sync/message.template.notify_admin_group_new_member.yml
  config/sync/message.template.notify_group_access_change.yml
  config/sync/message.template.notify_group_admin_demoted.yml
  config/sync/message.template.notify_group_admin_promoted.yml
  config/sync/message.template.notify_group_archived.yml
  config/sync/message.template.notify_group_membership_pending.yml
  config/sync/message.template.notify_group_published.yml
  config/sync/message.template.notify_group_request_approved.yml
  config/sync/message.template.notify_group_request_submitted.yml
  config/sync/message.template.notify_group_requested.yml
  config/sync/message.template.notify_group_unpublished.yml
  config/sync/message.template.notify_membership_request_rej.yml
  config/sync/message.template.notify_welcome_user_to_group.yml
  config/sync/message.template.sub_content_interest_published.yml
  config/sync/message.template.sub_group_content_shared.yml
  config/sync/message.template.sub_group_content_updated.yml
  config/sync/message.template.sub_new_comment_on_content.yml
  config/sync/message.template.sub_new_comment_reply.yml
  config/sync/message.template.sub_new_content_recommendation.yml
  config/sync/message.template.sub_new_discussion_published.yml
  config/sync/message.template.sub_new_group_content_published.yml
  config/sync/message.template.sub_own_group_content_updated.yml
  config/sync/message.template.sub_site_event_pub_interest.yml
Labels: backend

#1278 EICNET-2171: Fix quote author in News
  lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--quote.inc
  lib/themes/eic_community/sass/components/_blockquote.scss
  lib/themes/eic_community/styleguide/components/blockquote.stories.js
Labels: bug, backend, frontend

#1281 EICNET-2174: Group activity stream cannot be viewed by non logged (anonymous) users
  lib/modules/eic_deploy/eic_deploy.install
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
Labels: bug, backend

#1284 [EICNET-1956]fix: Add more translations keys + filter on same day
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/DateField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
Labels: backend, react

#1266 [EICNET-1908]fix: Add teams cta + ignore anonymous user + add language filter
  config/sync/context.context.group_members_overviews.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Search/Sources/UserInvitesListSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserTaggingCommentsSourceType.php
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/patterns/compositions/organisation/organisation.member.teaser.html.twig
  lib/themes/eic_community/styleguide/compositions/teaser.stories.js
Labels: backend, frontend

#1287 EICNET-2175: Fix overviews access for SA/SCM/DA in Events and Organisations.
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.organisation-4c7e676f7.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
Labels: backend

#1280 EICNET-2182: Create eic_dummy_content_type module.
  lib/modules/eic_dummy_content_type/config/install/core.base_field_override.node.dummy.promote.yml
  lib/modules/eic_dummy_content_type/config/install/core.entity_form_display.node.dummy.default.yml
  lib/modules/eic_dummy_content_type/config/install/core.entity_view_display.node.dummy.default.yml
  lib/modules/eic_dummy_content_type/config/install/core.entity_view_display.node.dummy.teaser.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.body.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_date_range.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_disclaimer.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_discussion_type.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_document_media.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_document_type.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_dummy_checkboxes.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_dummy_file.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_dummy_test.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_dummy_test_2.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_email.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_image.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_link.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_location.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_number_integer.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_organised_by.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_related_contributors.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_related_groups.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_social_links.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_text_plain_long.yml
  lib/modules/eic_dummy_content_type/config/install/field.field.node.dummy.field_vocab_topics.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_dummy_checkboxes.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_dummy_file.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_dummy_test.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_dummy_test_2.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_email.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_number_integer.yml
  lib/modules/eic_dummy_content_type/config/install/field.storage.node.field_text_plain_long.yml
  lib/modules/eic_dummy_content_type/config/install/language.content_settings.node.dummy.yml
  lib/modules/eic_dummy_content_type/config/install/node.type.dummy.yml
  lib/modules/eic_dummy_content_type/eic_dummy_content_type.info.yml
  lib/modules/eic_dummy_content_type/eic_dummy_content_type.install
  lib/modules/eic_dummy_content_type/eic_dummy_content_type.module
Labels: backend, frontend

#1283 EICNET-2181: Documents - Topic label links to same page
  config/sync/core.entity_view_display.node.document.default.yml
Labels: bug, backend

#1285 EICNET-2172: No avatar shown on news articles
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#1268 Feature/eicnet 2096 wiki navigation
  lib/themes/eic_community/data/wiki/items.data.js
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-groups-wiki-book-navigation.inc
  lib/themes/eic_community/js/components/drupal.navigation-list.js
  lib/themes/eic_community/patterns/components/navigation-list/navigation-list-items.html.twig
  lib/themes/eic_community/sass/components/_navigation-list.scss
  lib/themes/eic_community/styleguide/bundles/group.stories.js
Labels: frontend

#1292 [EICNET-1745]fix: set correct statistics + invalidate cache when event like
  lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_statistics/eic_statistics.services.yml
  lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
  lib/modules/eic_statistics/src/StatisticsHelper.php
  lib/themes/eic_community/includes/preprocess/common.inc
Labels: backend

#1270 EICNET-2160: Make sure only allowed workflow states show up in groups.
  lib/modules/eic_moderation/eic_moderation.module
  lib/modules/eic_moderation/src/Hooks/FormOperations.php
  lib/modules/eic_moderation/src/Service/ContentModerationManager.php
Labels: backend

#1286 [EICNET-1810]chore: Add delete/archival request links to organisations
  config/sync/group.content_type.group_content_type_544ffa9c3791b.yml
  config/sync/group.content_type.group_content_type_b47cbb19c399d.yml
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
Labels: enhancement, backend

#1299 [EICNET]fix: Set default order for news in organisation by created date
  config/sync/views.view.organisation_content.yml
Labels: backend

#1300 [EICNET]fix: Add view group permission to GM
  config/sync/group.role.organisation-member.yml
Labels: backend

#1276 Feature/eicnet comments edit tag user
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupComponents/TaggedUsersModal.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
  lib/themes/eic_community/sass/compositions/_comment.scss
Labels: frontend, react

#1289 [EICNET-2185] Top contributor
  lib/themes/eic_community/data/teaser/index.js
  lib/themes/eic_community/patterns/compositions/member-information-block.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.full.html.twig
  lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/TopContrib.js
  lib/themes/eic_community/sass/compositions/_comment.scss
  lib/themes/eic_community/sass/compositions/_contact-information-block.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/styleguide/bundles/member.stories.js
  lib/themes/eic_community/styleguide/compositions/teaser.stories.js
Labels: frontend, react

#1291 organisation contact collapsed adress
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
  lib/themes/eic_community/templates/group/group--organisation--full.html.twig
Labels: frontend

#1304 EICNET-2135: TU cannot view comments of content in public groups
  lib/modules/eic_deploy/eic_deploy.install
  lib/modules/eic_deploy/eic_deploy.module
  lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PublicVisibility.php
  lib/themes/eic_community/sass/compositions/_comment-overview.scss
Labels: backend

#1297 [EICNET]feat: Create a form to update every groups permissions from their group types
  lib/modules/eic_admin/eic_admin.links.menu.yml
  lib/modules/eic_admin/eic_admin.routing.yml
  lib/modules/eic_admin/src/Form/UpdateAllGroupPermissionsForm.php
Labels: backend

#1007 EICNET-1711: Topic Detail FE.
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/themes/eic_community/data/activity-stream.data.js
  lib/themes/eic_community/data/featured-content-collection/group.data.js
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/patterns/compositions/discussion-thread.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/patterns/compositions/topic/topic.details.html.twig
  lib/themes/eic_community/react/components/Block/ActivityStream/index.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/CommentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DiscussionStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/DocumentStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/EventStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/VideoStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/WikiStreamResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
  lib/themes/eic_community/sass/components/_tag.scss
  lib/themes/eic_community/sass/compositions/_activity-stream.scss
  lib/themes/eic_community/sass/compositions/_comment-thread.scss
  lib/themes/eic_community/sass/compositions/_comment.scss
  lib/themes/eic_community/sass/compositions/_discussion-thread.scss
  lib/themes/eic_community/sass/compositions/_featured-content-collection.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
  lib/themes/eic_community/sass/schema/_typography.scss
  lib/themes/eic_community/styleguide/bundles/topic.stories.js
  lib/themes/eic_community/templates/content/node--document--teaser.html.twig
Labels: frontend

#1305 EICNET-2196: Update book page URL pattern and add missing variables to the Theme
  config/sync/pathauto.pattern.books.yml
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-content-book-navigation.inc
Labels: backend

#1303 Feature/eicnet 1303 smed taxonomy organisation size
  config/sync/core.entity_form_display.taxonomy_term.organisation_sizes.default.yml
  config/sync/core.entity_view_display.taxonomy_term.organisation_sizes.default.yml
  config/sync/field.field.taxonomy_term.organisation_sizes.field_smed_id.yml
  config/sync/language.content_settings.taxonomy_term.organisation_sizes.yml
  config/sync/migrate_plus.migration.smed_organisation_sizes.yml
  config/sync/taxonomy.vocabulary.organisation_sizes.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_organisation_sizes.yml
Labels: backend

#1293 EICNET-2187: Fix issue with double base path in views more links.
  lib/modules/eic_topics/eic_topics.module
Labels: backend

#1288 EICNET-2132: TU can not reply on comment in News article (organisations)
  lib/modules/eic_groups/eic_groups.install
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: backend

#1309 [EICNET-2179]feat: Set correct topic name field in solr to prefilter on
  lib/modules/eic_topics/eic_topics.module
Labels: backend

#1277 [EICNET-2055] change icone in my profile btn in notif management
  lib/modules/eic_user/src/Plugin/Block/UserHeaderBlock.php
  lib/themes/eic_community/patterns/compositions/member/email-notification.html.twig
Labels: frontend

#1307 [EICNET] add template for page 4xx
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/templates/layout/page--4xx.html.twig
Labels: frontend

#1311 Feature/eicnet 1291 smed taxonomy event types
  config/sync/core.entity_form_display.taxonomy_term.global_event_type.default.yml
  config/sync/core.entity_view_display.taxonomy_term.global_event_type.default.yml
  config/sync/field.field.group.event.field_vocab_event_type.yml
  config/sync/field.field.taxonomy_term.global_event_type.field_display_to_users.yml
  config/sync/field.field.taxonomy_term.global_event_type.field_smed_id.yml
  config/sync/field.storage.taxonomy_term.field_display_to_users.yml
  config/sync/language.content_settings.taxonomy_term.global_event_type.yml
  config/sync/migrate_plus.migration.smed_event_types.yml
  config/sync/taxonomy.vocabulary.global_event_type.yml
  lib/modules/eic_events/eic_events.module
  lib/modules/eic_events/src/Constants/Event.php
  lib/modules/eic_events/src/Hooks/FormOperations.php
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_event_types.yml
Labels: backend

#1313 [EICNET-2191]fix: Do not authorized the group node overview for all outsider
  config/sync/group.role.organisation-4c7e676f7.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-dcb2f93df.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-outsider.yml
  config/sync/group.role.organisation-owner.yml
Labels: backend

#1312 [EICNET-1990]fix: Use entity reference autocomplete widget for file document topics
  config/sync/core.entity_form_display.media.eic_document.default.yml
Labels: backend

#1314 [EICNET-2197]fix: Add access to SA SCM to edit their own book
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
Labels: backend

#1319 EICNET-1815: Critical actions admin view (improvements)
  config/sync/language/en/message.template.log_request_accepted.yml
  config/sync/message.template.log_request_accepted.yml
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
Labels: bug, backend

#1306 Feature/eicnet 1827 group visibility tree widget
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/modules/eic_groups/modules/eic_organisations/src/Plugin/CustomRestrictedVisibility/RestrictedOrganisationTypes.php
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: backend

#1320 [EICNET-2201]fix: Show own contents even in draft for current user
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: backend

#1317 [EICNET-2105]fix: Do not render empty content_after region
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/themes/eic_community/patterns/layout/base.html.twig
Labels: backend

#1321 Feature/eicnet 2189
  config/sync/context.context.group_group_homepage.yml
  config/sync/views.view.group_events.yml
  lib/themes/eic_community/includes/preprocess/content/node--event.inc
  lib/themes/eic_community/sass/compositions/_base-layout.scss
  lib/themes/eic_community/templates/content/node--event--small-teaser.html.twig
Labels: backend, frontend

#1326 [EICNET-2122] Fix click outside bug
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Labels: bug, frontend

#1323 Feature/eicnet 237 smed taxonomy regions countries
  config/sync/core.entity_form_display.taxonomy_term.target_markets.default.yml
  config/sync/core.entity_view_display.taxonomy_term.target_markets.default.yml
  config/sync/field.field.taxonomy_term.target_markets.field_smed_id.yml
  config/sync/migrate_plus.migration.smed_regions_countries_lvl1.yml
  config/sync/migrate_plus.migration.smed_regions_countries_lvl2.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_regions_countries_lvl1.yml
  lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_regions_countries_lvl2.yml
Labels: backend

#1316 [EICNET-1450]fix: Activity stream item statistics endpoint
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_statistics/eic_statistics.routing.yml
  lib/modules/eic_statistics/src/Controller/EntityStatisticsController.php
  lib/modules/eic_statistics/src/StatisticsHelper.php
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
Labels: enhancement, backend, frontend

#1324 [EICNET]fix: remove view unpublished group permission from TU
  config/sync/group.role.organisation-dcb2f93df.yml
  config/sync/workflows.workflow.groups.yml
Labels: bug, backend

#1329 [EICNET]fix: Fix wrong published condition
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: bug

#1336 [EICNET-2026]feat: Send e-mails when a membership request is approved
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.info.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.services.yml
  lib/modules/eic_groups/modules/eic_group_membership/src/EventSubscriber/MembershipTransitionSubscriber.php
Labels: enhancement, backend

#1335 Implement cypress automated test
  .env.docker
  .gitlab-ci.yml
  Makefile
  docker-compose.yml
  e2e/.gitignore
  e2e/.npmrc
  e2e/Dockerfile
  e2e/cypress.json
  e2e/cypress/fixtures/example.json
  e2e/cypress/integration/group/group.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/commands.js
  e2e/cypress/support/index.js
  e2e/package-lock.json
  e2e/package.json
  lib/modules/eic_user/eic_user.module
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
Labels: backend, frontend

#1315 [EICNET-2200] change group teaser title style
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1328 EICNET-2190: Related groups does not shift left when certain groups are not visible to that user
  lib/modules/eic_groups/eic_groups.module
Labels: bug, backend

#1333 EICNET-2227: Create a text filter to add divs around tables.
  config/sync/core.extension.yml
  config/sync/filter.format.filtered_html.yml
  config/sync/filter.format.full_html.yml
  lib/modules/eic_wysiwyg/eic_wysiwyg.info.yml
  lib/modules/eic_wysiwyg/src/Plugin/Filter/FilterTableDivs.php
Labels: backend

#1345 [EICNET-1810]fix: TU should not request archival/deletion
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
Labels: enhancement, backend

#1341 EICNET-2034: Group type notification - group deleted
  config/sync/core.entity_form_display.message.notify_group_deleted.default.yml
  config/sync/core.entity_view_display.message.notify_group_deleted.default.yml
  config/sync/core.entity_view_display.message.notify_group_deleted.mail_body.yml
  config/sync/core.entity_view_display.message.notify_group_deleted.mail_subject.yml
  config/sync/field.field.message.notify_group_deleted.field_entity_type.yml
  config/sync/field.field.message.notify_group_deleted.field_event_executing_user.yml
  config/sync/field.field.message.notify_group_deleted.field_referenced_entity_label.yml
  config/sync/language/en/message.template.notify_group_deleted.yml
  config/sync/message.template.notify_group_deleted.yml
  lib/modules/eic_groups/eic_groups.api.php
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Entity/Group.php
  lib/modules/eic_messages/eic_messages.module
  lib/modules/eic_messages/src/Service/GroupMessageCreator.php
  lib/modules/eic_messages/src/Util/NotificationMessageTemplates.php
Labels: enhancement, backend

#1339 [EICNET-1910] Remove field_vocab_topics in media
  config/sync/core.entity_form_display.media.eic_document.default.yml
  config/sync/core.entity_view_display.media.eic_document.default.yml
  config/sync/core.entity_view_display.media.eic_document.download.yml
  config/sync/core.entity_view_display.media.eic_document.media_library.yml
  config/sync/core.entity_view_display.media.eic_document.oe_theme_main_content.yml
  config/sync/field.field.media.eic_document.field_vocab_topics.yml
  config/sync/field.storage.media.field_vocab_topics.yml
Labels: backend

#1347 [EICNET]chore: add access test for organisation/s, people, 404
  docker-compose.yml
  e2e/cypress/integration/global/access-page-check.spec.js
Labels: QA

#1331 [EICNET]chore: refactor the solr search controller
  config/sync/context.context.drafts.yml
  config/sync/search_api.index.global.yml
  e2e/cypress/helper/login.js
  e2e/cypress/integration/group/group.spec.js
  e2e/cypress/integration/user/activity/my-drafts.spec.js
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
  lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/modules/eic_user/eic_user.routing.yml
  lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php
Labels: enhancement, backend

#1350 [EICNET]feat: Add permissions to edit members in organisation
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-owner.yml
Labels: backend

#1349 EICNET-2248: Message notification for group owner fix (new token)
  config/sync/language/en/message.template.notify_group_access_change.yml
  config/sync/language/en/message.template.notify_group_request_submitted.yml
  config/sync/language/en/message.template.notify_membership_request_rej.yml
  config/sync/language/en/message.template.notify_new_member_joined.yml
  config/sync/language/en/message.template.notify_new_membership_request.yml
  config/sync/language/en/message.template.notify_welcome_user_to_group.yml
  config/sync/message.template.notify_group_access_change.yml
  config/sync/message.template.notify_group_request_submitted.yml
  config/sync/message.template.notify_membership_request_rej.yml
  config/sync/message.template.notify_new_member_joined.yml
  config/sync/message.template.notify_new_membership_request.yml
  config/sync/message.template.notify_welcome_user_to_group.yml
  lib/modules/eic_groups/src/Hooks/GroupTokens.php
Labels: backend

#1310 EICNET-1378: Automatically unfollow group + group content when user leaves a group
  config/sync/eic_group_membership.settings.yml
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/FlagHelper.php
  lib/modules/eic_groups/modules/eic_group_membership/composer.json
  lib/modules/eic_groups/modules/eic_group_membership/config/install/eic_group_membership.settings.yml
  lib/modules/eic_groups/modules/eic_group_membership/drush.services.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/src/Commands/GroupMembershipCommands.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Service/SubscriptionMessageChecker.php
Labels: enhancement, backend

#1357 [EICNET-2152]fix: remove access for anonymous user to /people
  lib/modules/eic_groups/eic_groups.module
Labels: backend

#1356 [EICNET-2256]feat: Add x-requested-with to handle ajax call for custom endpoints
  lib/modules/eic_groups/src/EventSubscriber/SearchApiSubscriber.php
Labels: backend

#1358 Feature/eicnet 2273 event group invitations
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.group_content.event-group_invitation.default.yml
  config/sync/core.entity_view_display.group_content.event-group_invitation.default.yml
  config/sync/field.field.group_content.event-group_invitation.field_invitation_counter.yml
  config/sync/field.field.group_content.event-group_invitation.group_roles.yml
  config/sync/field.field.group_content.event-group_invitation.invitation_status.yml
  config/sync/field.field.group_content.event-group_invitation.invitee_mail.yml
  config/sync/group.content_type.event-group_invitation.yml
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
  config/sync/group.role.event-owner.yml
Labels: backend

#1362 EICNET cypress move login and cookies in command and delete helpers
  e2e/cypress/helper/login.js
  e2e/cypress/integration/group/group.spec.js
  e2e/cypress/integration/user/activity/my-drafts.spec.js
  e2e/cypress/support/commands.js
Labels: cypress
