Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-01, with the labels that each got.

#1001 Feature/eicnet group wiki detailed rework
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/themes/eic_community/includes/preprocess/navigation/menu-local-tasks.inc
  lib/themes/eic_community/js/components/drupal.navigation-list.js
  lib/themes/eic_community/sass/components/_navigation-list.scss
  lib/themes/eic_community/sass/compositions/_editorial-article.scss
  lib/themes/eic_community/templates/content/node--wiki-page--full.html.twig
  lib/themes/eic_community/templates/layout/page--node--wiki-page.html.twig
Labels: frontend

#996 [EICNET-1853] gallery/file detailed front end rework
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/patterns/components/filelist.html.twig
  lib/themes/eic_community/patterns/compositions/filelist/filelist.gallery.html.twig
  lib/themes/eic_community/react/components/Block/Gallery/FileInfo.jsx
  lib/themes/eic_community/react/components/Block/Gallery/Gallery.jsx
  lib/themes/eic_community/react/components/Block/Gallery/Image.jsx
  lib/themes/eic_community/react/components/Block/Gallery/entrypoint.js
  lib/themes/eic_community/sass/components/_filelist.scss
  lib/themes/eic_community/sass/components/_gallery.scss
Labels: frontend

#993 [EICNET-1851] group library overview teaser rework
  lib/themes/eic_community/images/sprite/custom/document.svg
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/LikeLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/Meta.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend, react

#1016 [EICNET-1101]feat: Handle likes differently when indexing
  config/sync/context.context.group_files_overviews.yml
  config/sync/search_api.index.global.yml
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
Labels: backend

#1013 [EICNET-1608]feat: Set big number on maxlength for selecting users in group
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: backend

#1010 [EICNET-1766] user avatat empty state
  lib/themes/eic_community/images/sprite/custom/user.svg
  lib/themes/eic_community/patterns/components/author.html.twig
  lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TaggedUsers.js
  lib/themes/eic_community/react/components/Block/Gallery/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Discussion/Comment.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
  lib/themes/eic_community/react/components/Utils/UserImage.js
  lib/themes/eic_community/sass/components/_author.scss
  lib/themes/eic_community/styleguide/compositions/gallery.stories.js
Labels: frontend, react

#998 [EICNET] Group members overview and group global search rework
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/modules/eic_search/templates/search-overview-block.html.twig
  lib/themes/eic_community/images/sprite/custom/group_administrator.svg
  lib/themes/eic_community/images/sprite/custom/group_owner.svg
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/sass/compositions/_filter-sidebar.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend, react

#1011 [EICNET-1850] Overview header tags
  lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js
  lib/themes/eic_community/sass/components/_tag.scss
Labels: frontend

#1014 [EICNET-1889] add hover effect on Highlighted icon
  lib/themes/eic_community/sass/components/_highlight.scss
Labels: frontend

#1015 [EICNET-1895] bugfix missing div container for document librabry
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
Labels: frontend, react

#1017 EICNET-1858: group ownership transfer confirmation (rework expiration)
  config/sync/core.entity_form_display.message.notify_transf_owner_expire_admin.default.yml
  config/sync/core.entity_form_display.message.notify_transf_owner_expire_owner.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.mail_subject.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_entity_type.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_entity_url.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_referenced_entity_label.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_referenced_flag.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_entity_type.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_entity_url.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_referenced_entity_label.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_referenced_flag.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_admin.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_owner.yml
  config/sync/message.template.notify_transf_owner_expire_admin.yml
  config/sync/message.template.notify_transf_owner_expire_owner.yml
  lib/modules/eic_flags/eic_flags.api.php
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Hooks/CronOperations.php
  lib/modules/eic_flags/src/RequestStatus.php
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/HandlerInterface.php
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_groups/modules/eic_group_membership/src/Plugin/views/field/TransferOwnershipStatus.php
  lib/modules/eic_messages/eic_messages.module
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: enhancement, backend

#1019 EICNET-1835: User profile my groups (rework)
  config/sync/views.view.groups.yml
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/templates/user/user--full.html.twig
Labels: backend

#1031 [EICNET-1902]feat: Add navigation on the organisation group type
  config/sync/oec_group_features.group_type_features.organisation.yml
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupAnnouncements.php
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: backend

#953 [EICNET] Use curlimages/curl for the notify job
  .gitlab-ci.yml
Labels: enhancement, backend

#1003 EICNET-1872: Display breadcrumb bellow page banner in topic detail page
  config/sync/context.context.global_breadcrumbs.yml
  lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
  lib/themes/eic_community/templates/layout/page--taxonomy--term.html.twig
Labels: backend

#1018 EICNET-1373: Keep user invite members choice when creating a group
  config/sync/field.field.group.group.field_group_invite_members.yml
  lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
Labels: backend

#1026 EICNET-1602: Fix URL aliases for group content entities
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php
  lib/modules/eic_groups/eic_groups.module
Labels: bug, backend

#1033 EICNET-1649: Display local tasks in a select field (rework)
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_content/modules/eic_content_book/eic_content_book.module
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
  lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php
Labels: bug, backend

#1037 EICNET-852: Overview page banner (rework)
  lib/modules/eic_overviews/src/Entity/OverviewPage.php
  lib/modules/eic_overviews/src/OverviewPageHtmlRouteProvider.php
Labels: backend

#1036 EICNET-1369: EICNET-1369 Adapt comment section on video detail page (rework)
  lib/modules/eic_content/src/Hooks/EntityOperationsContributor.php
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
Labels: bug, backend

#1041 EICNET-1526: Fix group overviews access. (rework)
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
Labels: backend

#1030 EICNET-1860: Group latest activity
  lib/modules/eic_comments/src/Constants/Comments.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupLatestActivity.php
Labels: backend

#1035 EICNET-1860: Group members data export
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberCommentCount.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberContentCount.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberLatestActivity.php
Labels: backend

#1023 [EICNET-1474]fix: Be able to search in fullname and not only first or last name
  lib/modules/eic_content/src/Services/EntityTreeManager.php
Labels: backend

#1021 [EICNET-1590]feat: Add correct key for "changed" value in sort
  config/sync/context.context.group_files_overviews.yml
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
Labels: backend, react

#1022 EICNET-1725: Error when adding same topic of interest multiple times in user profile
  config/sync/core.entity_form_display.profile.member.default.yml
Labels: backend

#1027 [EICNET-1643] responsive form improvement
  lib/themes/eic_community/templates/form/form.html.twig
Labels: frontend

#1008 [EICNET-1732]chore: Package updates
  composer.lock
Labels: backend

#1045 EICNET-1699: SA & SCM cannot add documents to a blocked group
  composer.lock
  composer.patches.json
Labels: bug, backend

#1046 EICNET-1761: Fix footer menu links
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#1044 [EICNET-1916] change "reply to" to "reply" and remove name
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: frontend, react

#1005 EICNET-1858: Group ownership transfer confirmation (Rework)
  config/sync/core.entity_form_display.flagging.transfer_owner_request_group.default.yml
  config/sync/core.entity_form_display.message.notify_transf_owner_expire_admin.default.yml
  config/sync/core.entity_form_display.message.notify_transf_owner_expire_owner.default.yml
  config/sync/core.entity_form_display.message.notify_transfer_group_ownership.default.yml
  config/sync/core.entity_view_display.flagging.transfer_owner_request_group.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_admin.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.default.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transf_owner_expire_owner.mail_subject.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.default.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.mail_body.yml
  config/sync/core.entity_view_display.message.notify_transfer_group_ownership.mail_subject.yml
  config/sync/field.field.flagging.transfer_owner_request_group.field_request_timeout.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_entity_type.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_entity_url.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_referenced_entity_label.yml
  config/sync/field.field.message.notify_transf_owner_expire_admin.field_referenced_flag.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_entity_type.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_entity_url.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_referenced_entity_label.yml
  config/sync/field.field.message.notify_transf_owner_expire_owner.field_referenced_flag.yml
  config/sync/field.field.message.notify_transfer_group_ownership.field_group_ref.yml
  config/sync/field.field.message.notify_transfer_group_ownership.field_related_user.yml
  config/sync/field.storage.flagging.field_request_timeout.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_admin.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_owner.yml
  config/sync/language/en/message.template.notify_transfer_group_ownership.yml
  config/sync/language/en/message.template.notify_transfer_owner_req_accept.yml
  config/sync/message.template.notify_transf_owner_expire_admin.yml
  config/sync/message.template.notify_transf_owner_expire_owner.yml
  config/sync/message.template.notify_transfer_group_ownership.yml
  config/sync/message.template.notify_transfer_owner_req_accept.yml
  config/sync/views.view.eic_group_members.yml
  lib/modules/eic_flags/eic_flags.api.php
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Controller/FlagRequestController.php
  lib/modules/eic_flags/src/Form/NewRequestForm.php
  lib/modules/eic_flags/src/Form/RequestCloseForm.php
  lib/modules/eic_flags/src/Hooks/CronOperations.php
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_flags/src/RequestStatus.php
  lib/modules/eic_flags/src/Routing/EntityRequestRouteProvider.php
  lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
  lib/modules/eic_flags/src/Service/BlockRequestHandler.php
  lib/modules/eic_flags/src/Service/HandlerInterface.php
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/src/Plugin/views/field/TransferOwnershipStatus.php
  lib/modules/eic_messages/eic_messages.module
  lib/modules/eic_messages/src/Service/RequestMessageCreator.php
Labels: enhancement, backend

#1039 [EICNET-1808] Visual - Bullet points
  lib/themes/eic_community/data/extended-list/interests.data.js
  lib/themes/eic_community/sass/compositions/_extended-list.scss
Labels: frontend

#1048 [EICNET-1852] Group library overview
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
  lib/themes/eic_community/sass/compositions/_pagination.scss
Labels: frontend

#1020 Feature/eicnet 1860 data export 2
  composer.json
  composer.lock
  composer.patches.json
  config/sync/core.extension.yml
  config/sync/views.view.admin_groups.yml
  config/sync/views.view.eic_admin_groups_data_export.yml
  lib/modules/eic_admin/config/install/views.view.eic_admin_groups_data_export.yml
  lib/modules/eic_admin/eic_admin.links.action.yml
  lib/modules/eic_admin/eic_admin.links.menu.yml
  lib/modules/eic_admin/eic_admin.links.task.yml
  lib/modules/eic_admin/eic_admin.routing.yml
  lib/modules/eic_comments/src/Constants/Comments.php
  lib/modules/eic_content/eic_content.module
  lib/modules/eic_content/eic_content.services.yml
  lib/modules/eic_content/src/Annotation/ContentMetric.php
  lib/modules/eic_content/src/ContentMetricInterface.php
  lib/modules/eic_content/src/ContentMetricPluginBase.php
  lib/modules/eic_content/src/ContentMetricPluginManager.php
  lib/modules/eic_content/src/Plugin/ContentMetric/ContentDownloads.php
  lib/modules/eic_content/src/Plugin/views/field/ContentMetrics.php
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/FlagHelper.php
  lib/modules/eic_groups/eic_groups.info.yml
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
  lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Annotation/GroupMetric.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupMetricInterface.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupMetricPluginBase.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupMetricPluginManager.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupComments.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupContent.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupContributors.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupDownloads.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupFlags.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupInvitations.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupMembers.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/GroupMetric/GroupMembershipRequests.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupLatestActivity.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberCommentCount.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberContentCount.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberHelper.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberLatestActivity.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMetrics.php
Labels: backend

#1065 [EICNET-1604]fix: Encapsulate the email FROm by <>
  lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
Labels: backend

#1064 [EICNET-1634]fix: Handle events group menu active on detail
  lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php
  lib/modules/eic_overviews/src/GroupOverviewPages.php
Labels: backend

#1063 [EICNET-1516]feat: Implement news article label for facet
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
Labels: backend, frontend, react

#1050 EICNET-1689: Homepage last updated groups (rework 2)
  config/sync/views.view.groups_homepage.yml
  lib/modules/eic_search/src/Plugin/views/cache/SearchApiTagCachePerUser.php
Labels: bug, backend

#1051 EICNET-1927: TU cannot create draft from published story
  composer.lock
  composer.patches.json
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.trusted_user.yml
Labels: bug, backend

#1054 EICNET-1754: Footer site name
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#1057 EICNET-1937: Custom restriction visibility options not shown in group add form
  lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php
Labels: bug, backend

#1060 EICNET-962: Group alias update create redirects (rework group content node URL alias)
  lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentUrlAliasUpdate.php
Labels: bug, backend

#1061 EICNET-1835: Fix title in user profile tab "My interests"
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: backend

#1069 Feature/eicnet 1859 group content moderation
  composer.json
  composer.lock
  composer.patches.json
  config/sync/core.extension.yml
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-member.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-member.yml
  config/sync/group.role.group-owner.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-member.yml
  config/sync/group.role.organisation-owner.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.service_authentication.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
Labels: enhancement, backend

#978 [EICNET-358] feat: Introduce the global contact form
  composer.json
  composer.lock
  config/sync/antibot.settings.yml
  config/sync/config_ignore.settings.yml
  config/sync/contact.form.contact_form.yml
  config/sync/contact.settings.yml
  config/sync/context.context.contact_page.yml
  config/sync/context.context.contact_page_anonymous.yml
  config/sync/core.entity_form_display.contact_message.contact_form.default.yml
  config/sync/core.entity_form_display.taxonomy_term.contact_category.default.yml
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/core.entity_view_display.contact_message.contact_form.default.yml
  config/sync/core.entity_view_display.taxonomy_term.contact_category.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.block_content.page_banner.field_body.yml
  config/sync/field.field.block_content.page_banner.field_subtitle.yml
  config/sync/field.field.contact_message.contact_form.field_contact_category.yml
  config/sync/field.field.taxonomy_term.contact_category.field_target_email.yml
  config/sync/field.storage.contact_message.field_contact_category.yml
  config/sync/field.storage.taxonomy_term.field_target_email.yml
  config/sync/language.content_settings.taxonomy_term.contact_category.yml
  config/sync/taxonomy.vocabulary.contact_category.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_contact/eic_contact.info.yml
  lib/modules/eic_contact/eic_contact.module
  lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
  lib/modules/eic_default_content/src/Generator/TaxonomyGenerator.php
  lib/modules/eic_default_content/src/Generator/UserGenerator.php
  lib/themes/eic_community/includes/preprocess/blocks/block--basic.inc
  lib/themes/eic_community/includes/preprocess/blocks/block.inc
  lib/themes/eic_community/templates/blocks/block--contact-banner.html.twig
  lib/themes/eic_community/templates/blocks/block--contact-intro-anonymous.html.twig
  lib/themes/eic_community/templates/blocks/block--contact-intro-authenticated.html.twig
Labels: enhancement, backend

#1070 [EICNET]fix: Do a check if there is a parent node book
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php
Labels: backend

#1042 [EICNET-1837] Not Authorized shown after TU leaves private group
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
Labels: enhancement, backend

#1067 EICNET-1920: Fix breadcrumb for News and Stories.
  lib/modules/eic_content/src/ContentBreadcrumbBuilder.php
Labels: backend

#1034 [EICNET-296] Homepage upcoming events
  lib/themes/eic_community/sass/components/_timestamp.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#972 EICNET-1718: Add missing read more links to topic related content views.
  lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
  lib/modules/eic_topics/eic_topics.info.yml
  lib/modules/eic_topics/eic_topics.module
  lib/modules/eic_topics/eic_topics.services.yml
  lib/modules/eic_topics/src/TopicsManager.php
  lib/modules/eic_user/src/UserHelper.php
  lib/themes/eic_community/includes/preprocess/blocks/block--topics-statistics.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: backend

#1058 [EICNET-1939] group search change title sidebar
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: frontend, react

#1074 [EICNET-1898] add global search on mobile
  lib/themes/eic_community/sass/compositions/_mainmenu.scss
Labels: frontend

#1053 EICNET-1697: Show non published groups to power users. (rework)
  lib/modules/eic_search/src/Controller/SolrSearchController.php
Labels: backend

#1077 EICNET-XXXX: Group URL alias cron issues
  lib/modules/eic_groups/src/Hooks/Pathauto.php
Labels: bug, backend

#1073 EICNET-1859: Add missing group permissions to view own unpublished content.
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-member.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-member.yml
  config/sync/group.role.group-owner.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-member.yml
  config/sync/group.role.organisation-outsider.yml
  config/sync/group.role.organisation-owner.yml
Labels: backend

#1075 [EICNET-1919] add highlight and change style of user in library
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/Meta.js
  lib/themes/eic_community/sass/components/_filelist.scss
  lib/themes/eic_community/sass/components/_highlight.scss
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1080 [EICNET-1917] Comments front-end mobile
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/sass/compositions/_comment-form.scss
  lib/themes/eic_community/sass/compositions/_discussion-thread.scss
Labels: frontend

#1059 Feature/eicnet 1527 group events flags
  config/sync/core.entity_view_display.node.discussion.default.yml
  config/sync/core.entity_view_display.node.document.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.gallery.default.yml
  config/sync/core.entity_view_display.node.video.default.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  lib/modules/eic_flags/eic_flags.module
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/FlagHelper.php
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_flags/src/Plugin/Flag/EntityFlagType.php
Labels: backend

#1062 EICNET-1661: Topics detail page (rework)
  config/sync/search_api.index.global.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
  config/sync/views.view.taxonomy_related_content.yml
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
  lib/modules/eic_topics/eic_topics.permissions.yml
  lib/modules/eic_user/eic_user.module
  lib/themes/eic_community/includes/preprocess/views.inc
Labels: bug, backend

#1082 EICNET-1974: Fix Group feature permissions issue
  lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
  lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
  lib/modules/oec_group_features/src/Hooks/EntityOperations.php
Labels: bug, backend

#1084 [EICNET-1238]feat: Disable by default field notification and activity for certain types
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Hooks/FormOperations.php
Labels: backend

#1090 [EICNET-190]fix: Add organisation permissions to outsider roles
  config/sync/config_ignore.settings.yml
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-outsider.yml
  config/sync/system.site.yml
Labels: backend

#1081 EICNET-1977: Error when creating a Global event as a Trusted user
  config/sync/group.type.event.yml
Labels: bug, backend

#1072 [EICNET-1335] add tooltip on highlight icon
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/package-lock.json
  lib/themes/eic_community/package.json
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/sass/components/_highlight.scss
Labels: frontend, react

#1094 [EICNET-1744] add required field
  lib/themes/eic_community/sass/components/_form.scss
Labels: frontend

#1095 [EICNET-1895] add space between two highlighted teaser
  lib/themes/eic_community/sass/compositions/_teaser.scss
Labels: frontend

#1092 (draft)[EICNET-1744]feat: Re-order field offers and needs
  config/sync/core.entity_form_display.group.organisation.default.yml
Labels: backend, frontend

#1105 [EICNET-1851]feat: On Library teaser item set dynamic like action
  lib/modules/eic_groups/eic_groups.routing.yml
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/Access/LikeGroupContentAccessCheck.php
  lib/modules/eic_groups/src/Controller/GroupOperationsController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/LikeLink.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Services/UrlHelper.js
Labels: backend, frontend, react

#1100 [EICNET-1745]feat: Latest news in organisation
  config/sync/group.role.organisation-dcb2f93df.yml
  config/sync/group.role.organisation-member.yml
  config/sync/group.role.organisation-outsider.yml
  config/sync/image.style.large.yml
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/patterns/compositions/story/story.teaser.html.twig
Labels: backend, frontend, react

#1089 [EICNET-1879] add current page in url
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/react/components/Utils/Url.js
  lib/themes/eic_community/sass/compositions/_pagination.scss
Labels: frontend, react

#1047 [EICNET]chore: Add a deploy job to the migration env
  .gitlab-ci.yml
Labels: enhancement

#1078 EICNET-1479: Global event detailed (improvements)
  config/sync/pathauto.pattern.group_event.yml
Labels: backend

#1079 EICNET-1975: Adapt URL for adding a group/event on homepage
  lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php
Labels: backend

#1085 EICNET-1450: Counters in activity stream (improvements)
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
Labels: backend

#1101 EICNET-1987: Cache issues in account header
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#1087 EICNET-1886: Comments are shown for non-group members
  config/sync/group.role.group-outsider.yml
  config/sync/group.role.organisation-4c7e676f7.yml
  config/sync/group.role.organisation-dcb2f93df.yml
  config/sync/group.role.organisation-outsider.yml
  lib/modules/eic_groups/eic_groups.install
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
Labels: backend

#1102 [EICNET-1896]feat: Add extraclasses for tag color in group teaser
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/sass/components/_tag.scss
Labels: backend

#1086 [EICNET-1821]feat: Handle blocked group state with group content
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
Labels: backend

#1076 [EICNET-1780]feat: add filter private + sort created
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
Labels: backend

#1083 [EICNET-841]feat: Set dynamic search placeholder and set case-insensitive
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/CollapsedOptions.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
  lib/themes/eic_community/sass/compositions/_filter-sidebar.scss
Labels: backend, frontend, react

#1098 Feature/eicnet 1785 organisation webservice
  config/sync/core.entity_form_display.group.organisation.default.yml
  config/sync/core.entity_view_display.group.organisation.default.yml
  config/sync/field.field.group.organisation.field_address.yml
  config/sync/field.field.group.organisation.field_smed_id.yml
  config/sync/rest.resource.eic_webservices_organisation.yml
  config/sync/rest.resource.eic_webservices_organisation_update.yml
  config/sync/user.role.service_authentication.yml
  lib/modules/eic_groups/modules/eic_organisations/src/OrganisationsHelper.php
  lib/modules/eic_webservices/eic_webservices.services.yml
  lib/modules/eic_webservices/src/ParamConverter/SmedIdConverter.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationUpdateResource.php
  lib/modules/eic_webservices/src/Utility/EicWsHelper.php
  lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
Labels: backend

#1110 Feature/eicnet 1853 gallery detailed
  config/sync/core.extension.yml
  lib/themes/eic_community/images/sprite/custom/share.svg
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/patterns/components/filelist.html.twig
  lib/themes/eic_community/react/components/Block/ShareModal/index.js
  lib/themes/eic_community/sass/components/_filelist.scss
  lib/themes/eic_community/sass/components/_gallery.scss
  lib/themes/eic_community/sass/compositions/_featured-list.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
  lib/themes/eic_community/sass/overrides/_viewport-modal.scss
  lib/themes/eic_community/templates/content/node--gallery--full.html.twig
Labels: frontend

#1104 [EICNET-1847] edit btn in show filter
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
Labels: frontend, react

#1103 [EICNET-1986] add space between notifications
  lib/themes/eic_community/sass/compositions/_notification-banner.scss
Labels: frontend

#1113 [EICNET-1880]feat: Add overview url prefiltered by topic
  config/sync/search_api.index.global.yml
  lib/modules/eic_overviews/src/GlobalOverviewPages.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
Labels: backend

#1107 [EICNET-1101]fix: Use correct label + sort option
  config/sync/context.context.group_files_overviews.yml
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
Labels: backend
