Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-06, with the labels that each got.

#1608 Feature/eicnet 2294 event migration rework
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.small_teaser.yml
  config/sync/core.entity_view_display.node.event.teaser.yml
  config/sync/field.field.node.event.field_document_additional.yml
  config/sync/field.field.node.event.field_document_agenda.yml
  config/sync/field.field.node.event.field_document_presentations.yml
  config/sync/field.storage.node.field_document_additional.yml
  config/sync/field.storage.node.field_document_agenda.yml
  config/sync/field.storage.node.field_document_presentations.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  config/sync/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_event_type.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_event_type.yml
Labels: backend, migration

#1625 Feature/eicnet 2510 migrate tags
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_discussion.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_document.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_news.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
  lib/modules/eic_migrate/src/Constants/Misc.php
  lib/modules/eic_migrate/src/Plugin/migrate/process/HtmlSanitizer.php
Labels: backend, migration

#1630 EICNET-2513: Editing a comment with user tag makes that user disappear after saving
  lib/modules/eic_groups/src/Controller/DiscussionController.php
Labels: bug, backend

#1633 EICNET-2430: Theme: fix breaking erros with missing fields
  lib/themes/eic_community/includes/preprocess/events.inc
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: bug, backend

#1632 Feature/eicnet 2078 comments migration rework
  config/sync/migrate_plus.migration.upgrade_d7_comment.yml
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml
  lib/modules/eic_migrate/src/Plugin/migrate/D7Comment.php
  lib/themes/eic_community/includes/preprocess/content/media.inc
Labels: backend, migration

#1626 EICNET-1321: Node 'Wiki page' migration (improvements phase 3)
  config/sync/context.context.group_wiki_page.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.default.yml
  config/sync/core.entity_view_display.node.wiki_page.teaser.yml
  config/sync/field.field.node.wiki_page.field_comments.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_groups/eic_groups.module
  lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
  lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_book.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_group.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/eic_migrate.services.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/Book.php
Labels: backend, frontend, migration

#1643 [EICNET-2490] Digest e-mail changes
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Collector/GroupCollector.php
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/templates/message/message--notify-digest.html.twig
Labels: bug, backend

#1646 [EICNET-1173]fix: Take the group budle into account
  lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
  lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/content/node--video.inc
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: bug, backend

#1644 [EICNET-2525]fix: Add correct transition permissions for drupal scm/sa
  config/sync/group.role.organisation-a416e6833.yml
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-bf4b46c3a.yml
  config/sync/group.role.organisation-eca6128ca.yml
  config/sync/group.role.organisation-owner.yml
Labels: backend

#1645 [EICNET-2524]fix: Generate temporary url on select users in tagging comment
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TaggedUsers.js
Labels: react

#1629 EICNET-1313: Node 'Photo' migration (improvements phase 3)
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  lib/modules/eic_migrate/src/Plugin/migrate/source/NodeCompletePhotoalbum.php
  lib/modules/eic_migrate/src/Plugin/migrate/source/PhotoalbumPhotoRelationship.php
  lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
Labels: backend, migration

#1637 EICNET-2519: Enable entity tree widget in language fields
  config/sync/core.entity_form_display.node.discussion.default.yml
  config/sync/core.entity_form_display.node.document.default.yml
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_form_display.node.video.default.yml
  config/sync/core.entity_form_display.node.wiki_page.default.yml
Labels: backend

#1649 [EICNET-2522]fix: If member is group admin he should see content even if group is restricted
  lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1654 [EICNET-2497]fix: Hide field_language in wiki
  config/sync/core.entity_view_display.node.wiki_page.default.yml
Labels: backend

#1642 [EICNET-2521]fix: Do not show flag actions on event group type
  lib/themes/eic_community/includes/preprocess/events.inc
Labels: backend

#1653 [EICNET] Subscription for global events
  config/sync/core.entity_form_display.message.sub_group_content_shared.default.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.default.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.mail_body.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.mail_subject.yml
  config/sync/core.entity_view_display.message.sub_group_content_shared.notify_digest.yml
  config/sync/core.entity_view_display.message.sub_new_comment_on_content.notify_digest.yml
  config/sync/core.entity_view_display.message.sub_site_event_pub_interest.default.yml
  config/sync/core.entity_view_display.message.sub_site_event_pub_interest.mail_body.yml
  config/sync/core.entity_view_display.message.sub_site_event_pub_interest.mail_subject.yml
  config/sync/core.entity_view_display.message.sub_site_event_pub_interest.notify_digest.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.teaser.yml
  config/sync/eic_admin.action_forms.entity.group_content.group_reject_membership.yml
  config/sync/field.field.message.sub_group_content_shared.field_referenced_node.yml
  config/sync/field.field.message.sub_group_content_shared.field_share_message.yml
  config/sync/field.field.message.sub_group_content_shared.field_source_group.yml
  config/sync/language/en/message.template.sub_group_content_shared.yml
  config/sync/language/en/message.template.sub_site_event_pub_interest.yml
  config/sync/message.template.sub_group_content_shared.yml
  config/sync/message.template.sub_site_event_pub_interest.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
  lib/modules/eic_groups/modules/eic_share_content/eic_share_content.info.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Event/MessageSubscriptionEvents.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/MessageSubscriptionEventSubscriber.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Service/SubscriptionMessageChecker.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Service/SubscriptionMessageCreator.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Collector/GroupCollector.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Collector/InterestCollector.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Constants/DigestSubscriptions.php
  lib/modules/eic_messages/modules/eic_subscription_digest/src/Service/DigestCollector.php
  lib/themes/eic_community/includes/preprocess/content/message.inc
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/templates/content/mail_teaser/event.mail_teaser.html.twig
  lib/themes/eic_community/templates/content/mail_teaser/node.mail_teaser.html.twig
  lib/themes/eic_community/templates/group/group--event--mail-teaser.html.twig
  lib/themes/eic_community/templates/message/message--notify-digest.html.twig
  lib/themes/eic_community/templates/mimemail/mimemail-message.html.twig
Labels: backend

#1650 EICNET-2435: Migrate Flags (Improvements)
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
Labels: backend, migration

#1666 [EICNET]chore: Package updates
  composer.lock
  composer.patches.json
Labels: backend

#1662 EICNET-1318: Make field_document_type optional for galleries.
  config/sync/field.field.node.gallery.field_document_type.yml
Labels: backend

#1665 EICNET-2294: Fix wrong destiniation field name.
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml
Labels: backend, migration

#1663 EICNET-191: Handle paragraphs field for Event GT.
  config/sync/core.entity_form_display.group.event.default.yml
  lib/modules/eic_events/eic_events.module
  lib/modules/eic_events/src/Constants/Event.php
  lib/modules/eic_events/src/Hooks/EntityOperations.php
  lib/modules/eic_events/src/Hooks/FormOperations.php
Labels: backend, migration

#1639 EICNET-1320: Node 'Story' migration (improvements phase 2)
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.default.yml
  config/sync/core.entity_view_display.node.story.mail_teaser.yml
  config/sync/core.entity_view_display.node.story.teaser.yml
  config/sync/field.field.node.story.field_related_groups.yml
  config/sync/field.field.node.story.field_vocab_geo.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend, migration

#1652 Feature/eicnet 2311 ownership transfer action form
  composer.lock
  composer.patches.json
  config/sync/context.context.group_content_global.yml
  config/sync/eic_admin.action_forms.entity.group.group_request_membership.yml
  config/sync/eic_admin.action_forms.entity.group_content.group_approve_membership.yml
  config/sync/eic_admin.action_forms.entity.group_content.group_reject_membership.yml
  config/sync/eic_admin.action_forms.ginvite.invitation.accept.yml
  config/sync/eic_admin.action_forms.ginvite.invitation.bulk.confirm.yml
  config/sync/eic_admin.action_forms.ginvite.invitation.bulk.yml
  config/sync/eic_admin.action_forms.group_archival_request.yml
  config/sync/eic_admin.action_forms.group_deletion_request.yml
  config/sync/eic_admin.action_forms.group_membership_delete.yml
  config/sync/eic_admin.action_forms.group_membership_edit.yml
  config/sync/eic_admin.action_forms.group_ownership_transfer_request.yml
  config/sync/eic_admin.action_forms.group_ownership_transfer_request_accept.yml
  config/sync/eic_admin.action_forms.group_ownership_transfer_request_deny.yml
  docker/php/dev.ini
  lib/modules/eic_admin/config/schema/eic_admin.action_forms.schema.yml
  lib/modules/eic_admin/eic_admin.services.yml
  lib/modules/eic_admin/src/Form/ActionFormsForm.php
  lib/modules/eic_admin/src/Plugin/Condition/ActionForms.php
  lib/modules/eic_admin/src/Routing/RouteSubscriber.php
  lib/modules/eic_admin/src/Service/ActionFormsManager.php
  lib/modules/eic_flags/src/Form/NewRequestForm.php
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.services.yml
  lib/modules/eic_groups/modules/eic_group_membership/src/Routing/RouteSubscriber.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
Labels: backend

#1675 EICNET-2458: Fix wrong array key in activity stream block.
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
Labels: bug, backend

#1671 [EICNET-2536]fix: Send first selected language to Solr
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
Labels: backend

#1672 EICNET-2285: Rebuild group permission resets Joining method
  lib/modules/eic_admin/src/Form/UpdateAllGroupPermissionsForm.php
Labels: bug, backend

#1676 [EICNET-2537]chore: Change label for the unpublish transition
  config/sync/workflows.workflow.eic_moderated_workflow.yml
  lib/modules/eic_moderation/config/install/workflows.workflow.eic_moderated_workflow.yml
Labels: backend

#1677 [EICNET]fix: Check for most active default sort if we are in group context
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1680 [EICNET-2548]fix: Add recommend source type and strict private visibility
  lib/modules/eic_recommend_content/src/Access/RecommendContentAccessCheck.php
  lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
  lib/modules/eic_search/src/Search/Sources/UserRecommendSourceType.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: backend

#1659 EICNET-2297: Fix issue with cancel links under subdirectory.
  composer.lock
  composer.patches.json
Labels: bug, backend

#1685 [EICNET-2046]fix: Resync user when joining group and comment
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
  lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
Labels: backend

#1688 [EICNET-2434]fix: Implement url for user on global result
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: react

#1684 EICNET-2538: SCM can Add Page to a global event
  config/sync/group.content_type.event-group_node-page.yml
Labels: backend

#1687 EICNET-2546: Double group navigation items shown for organizations
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/GroupGenerator.php
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/GroupTypeEventGenerator.php
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/OrganisationGenerator.php
Labels: bug, backend

#1690 [EICNET-2550]chore: Icons for file attachments in events
  config/sync/config_split.config_split.development.yml
  lib/themes/eic_community/includes/preprocess/groups/group.inc
Labels: bug, backend

#1679 EICNET-2542: Post Content shown for TU on Files page in Pending group
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
  lib/modules/eic_search/templates/search-overview-block.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
  lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: bug, backend

#1695 EICNET-2534: Event website is not shown
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.small_teaser.yml
  config/sync/core.entity_view_display.node.event.teaser.yml
  config/sync/field.field.node.event.field_link.yml
  config/sync/field.storage.node.field_link.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml
Labels: backend, migration

#1699 [EICNET]chore: Package updates
  composer.lock
Labels: backend

#1682 Action forms: Take into account the base path while matching paths.
  lib/modules/eic_admin/src/Service/ActionFormsManager.php
  lib/themes/eic_community/includes/alter/form/form.inc
Labels: backend

#1683 EICNET-1320: Node 'Story' migration (improvements phase 3)
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend, migration

#1711 Feature/eicnet 2554 web service fixes
  config/sync/config_ignore.settings.yml
  lib/modules/eic_webservices/src/Controller/SubRequestController.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicEntityResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserUpdateResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EventUpdateResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/GroupResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationUpdateResource.php
Labels: backend

#1681 EICNET-191: Allow HTML in full_text_content paragaph body.
  config/sync/core.entity_view_display.paragraph.full_text_content.default.yml
  config/sync/field.field.paragraph.full_text_content.field_body.yml
  lib/themes/eic_community/includes/preprocess/events.inc
  lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--full-text-content.inc
  lib/themes/eic_community/patterns/compositions/text-block.html.twig
  lib/themes/eic_community/templates/group/group--event--full.html.twig
  lib/themes/eic_community/templates/paragraphs/paragraph--full-text-content.html.twig
Labels: backend, migration

#1703 EICNET-2563: Comment in discussions overview teaser in not rendered as html
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Discussion/Comment.js
Labels: bug, frontend

#1705 [EICNET-1664] fix: user image in comment email
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_body.yml
  config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_subject.yml
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: backend, frontend

#1706 EICNET-2556: As a user I can create empty comments (Improvements)
  lib/modules/eic_groups/src/Controller/DiscussionController.php
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
Labels: bug, backend, frontend

#1708 EICNET-2564: Pending membership requests link is not shown in the group management dropdown
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#1717 EICNET-390: Allow video medias in News and Stories documents
  config/sync/field.field.node.news.field_document_media.yml
  config/sync/field.field.node.story.field_document_media.yml
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
Labels: backend

#1707 [EICNET-2495]fix: Replace my groups by react component
  lib/modules/eic_search/eic_search.module
  lib/modules/eic_search/eic_search.services.yml
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/Sources/SourceType.php
  lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
  lib/modules/eic_search/src/Search/Sources/UserProfile/MyGroupsSourceType.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/modules/eic_search/templates/search-overview-block.html.twig
  lib/themes/eic_community/includes/preprocess/users/user.inc
  lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
  lib/themes/eic_community/react/components/Block/Overview/index.js
Labels: backend, react

#1701 [EICNET-2535]fix: Do not use the search_api_reverse_reference but load correctly the gid from group content
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
Labels: backend

#1715 EICNET-2562: Prevent legacy paragraphs to be silently populated.
  config/sync/core.entity_form_display.group.event.default.yml
Labels: backend

#1712 EICNET-2435: Migrate Flags (Fix regressions)
  lib/modules/eic_flags/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/FlagEventSubscriber.php
Labels: backend, migration

#1722 Feature/eicnet 2311 ownership transfer action form
  config/sync/context.context.global_action_forms.yml
  config/sync/eic_admin.action_forms.group_membership_join.yml
  config/sync/eic_admin.action_forms.group_membership_leave.yml
  lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
  lib/modules/eic_groups/modules/eic_group_membership/src/GroupMembershipHelper.php
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/themes/eic_community/includes/alter/form/form.inc
  lib/themes/eic_community/sass/components/_link.scss
  lib/themes/eic_community/sass/compositions/_action-form.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: backend, frontend

#1714 EICNET-226: Migrate "image" media type (Add default alt text)
  config/sync/migrate_plus.migration.upgrade_d7_file_image_to_media.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_image_to_media.yml
Labels: backend, migration

#1716 EICNET-2004: Group creation status banners - published (Fixes)
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
Labels: bug, backend

#1713 EICNET-1443: Path redirect migration (improvements)
  config/sync/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
  config/sync/migrate_plus.migration.upgrade_d7_group_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_path_redirect.yml
Labels: backend, migration

#1727 EICNET-2311: Don't try to render the submit as danger button as this …
  lib/themes/eic_community/includes/alter/form/form.inc
Labels: backend

#1728 [EICNET-2590] fix: remove menu search overflow
  lib/themes/eic_community/sass/compositions/_mainmenu.scss
Labels: frontend

#1704 [EICNET-2558] feat: add Quill link formatter
  lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/WysiswigEditor.js
Labels: frontend, react

#1733 EICNET-XXXX: Re-add scheduler patch.
  composer.lock
  composer.patches.json
Labels: backend

#1737 EICNET-XXXX: Fix new service name for reading time.
  lib/themes/eic_community/includes/preprocess/layout/page.inc
Labels: backend

#1739 [EICNET-2539] fix: set error text in red
  lib/themes/eic_community/sass/components/_messages.scss
  lib/themes/eic_community/sass/eic_community.screen.scss
Labels: frontend

#1709 [EICNET-2434]fix: Set correctly url dynamically depending proxy
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
Labels: react

#1738 Feature/eicnet 1323 fix last comment timestamp
  config/sync/core.entity_form_display.node.discussion.default.yml
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
Labels: backend

#1741 Feature/eicnet 1934 book reorder
  composer.json
  composer.lock
  config/sync/core.extension.yml
  lib/themes/eic_community/includes/alter/form/form.inc
  lib/themes/eic_community/includes/alter/theme_suggestions/table.inc
Labels: backend

#1735 EICNET-2526: Update my invitations view.
  config/sync/views.view.my_invitations.yml
Labels: backend

#1725 EICNET-2423: Fix comment notification template
  lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
Labels: bug, backend
