Repository EIC-EA/EIC-community-D8, pull requests merged in 2022-07, with the labels that each got.

#1718 EICNET-975: Show author in News and Story document teasers
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/patterns/components/attachment.html.twig
Labels: backend

#1732 EICNET-2541: Shared event in organisation is not shown
  lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
Labels: bug, backend

#1736 EICNET-1335: Hide highlight icon for trusted users if content is not highlighted
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js
Labels: bug, frontend

#1743 EICNET-2598: Groups without an image in /groups should show the default empty image
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: frontend

#1730 EICNET-1438: Message migration (Fix activity stream overview)
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
Labels: bug, backend, migration

#1751 [EICNET-2480]chore: Chand the way we create message on event insert
  lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/EntityOperations.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: bug, backend

#1750 [EICNET-2611]fix: Fix cypress issues with new comment from Quill
  docker/php/Dockerfile
  e2e/cypress.json
  e2e/cypress/integration/global/permissions-check.spec.js
  e2e/cypress/integration/group/group.spec.js
  e2e/cypress/support/commands.js
Labels: cypress

#1752 [EICNET]fix: Restore form alter hooks
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
Labels: bug, backend

#1753 Feature/eicnet 2311 ownership transfer action form
  config/sync/eic_admin.action_forms.group_membership_delete.yml
  config/sync/eic_admin.action_forms.group_ownership_transfer_request_cancel.yml
  config/sync/language/en/message.template.notify_new_transfer_owner_req.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_admin.yml
  config/sync/language/en/message.template.notify_transf_owner_expire_owner.yml
  config/sync/language/en/message.template.notify_transfer_owner_req_accept.yml
  config/sync/language/en/message.template.notify_transfer_owner_req_cancel.yml
  config/sync/message.template.notify_new_transfer_owner_req.yml
  config/sync/message.template.notify_transf_owner_expire_admin.yml
  config/sync/message.template.notify_transf_owner_expire_owner.yml
  config/sync/message.template.notify_transfer_owner_req_accept.yml
  config/sync/message.template.notify_transfer_owner_req_cancel.yml
  lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
  lib/modules/eic_user/src/Hooks/FormAlter.php
  lib/themes/eic_community/patterns/layout/base.html.twig
  lib/themes/eic_community/sass/components/_form.scss
Labels: backend

#1755 EICNET-918: Point to the edit form instead of the last revision.
  config/sync/language/en/message.template.notify_content_ready_for_review.yml
Labels: backend

#1757 EICNET-2160: Get rid of submit for approval and ask changes transitions in Organisations
  config/sync/group.role.organisation-admin.yml
  config/sync/group.role.organisation-owner.yml
Labels: backend

#1759 EICNET-2603: Add the MAnage invitations link to group dropdown.
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#1747 EICNET-2525: Allow GMs to save News in organisations.
  config/sync/group.role.organisation-member.yml
Labels: bug, backend

#1740 EICNET-2597: Whenever a user accepts his last invitation, he still sees the warning message that an invitation is awaiting his feedback
  lib/modules/eic_groups/eic_groups.services.yml
  lib/modules/eic_groups/src/EventSubscriber/GinviteSubscriber.php
Labels: bug, backend

#1760 EICNET-2332: Add alt text to field video.
  config/sync/field.field.node.news.field_video.yml
  config/sync/field.field.node.story.field_video.yml
  config/sync/field.field.node.video.field_video_media.yml
Labels: backend

#1742 EICNET-2539: No validation error message shown when required fields in inactive tabs are empty
  composer.lock
  composer.patches.json
  config/sync/core.entity_form_display.group.organisation.default.yml
  config/sync/core.entity_form_display.node.gallery.default.yml
  config/sync/core.entity_form_display.node.news.default.yml
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.entity_form_display.node.video.default.yml
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/themes/eic_community/react/components/Field/EntityTree/entrypoint.js
  lib/themes/eic_community/react/components/Field/EntityTree/index.js
Labels: backend, frontend

#1761 [EICNET-2596]fix: Use group bundle when checking for content in groups helper
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
Labels: bug, backend

#1744 EICNET-390: Implement video player in Story video.
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/templates/content/node--story--full.html.twig
Labels: backend

#1754 EICNET-1815: Critical actions admin view (Fix request deletion)
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
Labels: bug, backend

#1765 EICNET-2602: Add missing permission for GO/GA to administer membership requests.
  config/sync/group.role.event-admin.yml
  config/sync/group.role.event-owner.yml
  config/sync/group.role.group-admin.yml
  config/sync/group.role.group-owner.yml
Labels: backend

#1749 [EICNET-2610]fix: Fix solr indexing issues due to null group/file
  lib/themes/eic_community/includes/preprocess/content/node--document.inc
Labels: backend

#1763 EICNET-1438: Fix issue that breaks activity stream list after loading more results
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
Labels: frontend

#1764 EICNET-2609: Options to "Send notification" and "Post message in activity stream" should be enabled by default
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
  lib/modules/eic_messages/src/Hooks/FormOperations.php
Labels: backend

#1766 EICNET-2613: Recommend content - Putting an enter inside comment field does not show up in the email
  lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
Labels: bug, backend

#1771 EICNET-2621: Cron error when sending notification about recommended organisation
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/templates/group/mail_teaser/group--organisation--mail-teaser.html.twig
Labels: bug, backend

#1772 EICNET-1160: As a TU I can upload a document when creating a story (Improvements in media language display)
  lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
  lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
  lib/themes/eic_community/includes/preprocess/field/field.inc
Labels: backend

#1756 EICNET-2605: TU sees Delete profile button but access to page is not authorized
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: bug, backend

#1767 Feature/eicnet 2595 archived content visibility
  config/sync/workflows.workflow.default.yml
  lib/modules/eic_content/src/Constants/DefaultContentModerationStates.php
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
Labels: backend

#1776 EICNET-2526: Update copy for invite accept action form.
  config/sync/eic_admin.action_forms.ginvite.invitation.accept.yml
Labels: backend

#1758 EICNET-2612: Fix issue in BookTokens class that is thrown when re-generating URL aliases
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php
Labels: bug, backend

#1774 [EICNET-2439]chore: Add Content title and link on some e-mails
  config/sync/language/en/message.template.sub_group_content_updated.yml
  config/sync/language/en/message.template.sub_new_group_content_published.yml
  config/sync/message.template.sub_group_content_updated.yml
  config/sync/message.template.sub_new_group_content_published.yml
Labels: bug, backend

#1777 EICNET-1320: Story migration (Set default disclaimer during migration)
  lib/modules/eic_default_content/eic_default_content.services.yml
  lib/modules/eic_default_content/modules/eic_dummy_content/eic_dummy_content.services.yml
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/NewsGenerator.php
  lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/StoryGenerator.php
  lib/modules/eic_default_content/src/Generator/FragmentGenerator.php
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend, migration

#1779 [EICNET-2480]fix: Send content shared notifications to following users
  config/sync/core.entity_view_display.message.sub_new_group_content_published.default.yml
  config/sync/language/en/message.template.sub_group_content_shared.yml
  config/sync/message.template.sub_group_content_shared.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
  lib/modules/eic_groups/modules/eic_share_content/eic_share_content.services.yml
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
  lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
Labels: bug, backend

#1778 [EICNET]feat: Use expertise field from user instead of topics
  lib/modules/eic_topics/src/TopicsManager.php
Labels: backend

#1775 [EICNET-2046]feat: Process total groups/events calculation after
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
Labels: backend

#1773 [EICNET-2614]feat: Add cypress coverage organisation
  e2e/cypress/integration/group/group.spec.js
  e2e/cypress/integration/organisation/organisation.spec.js
  e2e/cypress/support/commands.js
  e2e/cypress/support/index.js
Labels: cypress

#1784 [EICNET-2631]feat: Set organisations statistics url
  lib/modules/eic_topics/src/TopicsManager.php
Labels: backend

#1788 [EICNET-2638]fix: Do not render video component for youtube videos
  lib/themes/eic_community/react/components/Block/ShareModal/components/ShareModal.js
  lib/themes/eic_community/react/components/Block/StreamVideo/entrypoint.js
Labels: frontend

#1786 [EICNET-2589]chore: Increase margin top for discussion titles
  lib/themes/eic_community/sass/compositions/_discussion-thread.scss
Labels: frontend

#1785 EICNET-2632: fix pagination display
  lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js
Labels: frontend, react

#1781 EICNET-2627: Prevent duplicate redirect migration.
  lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
Labels: backend, migration

#1799 EICNET-2299: Group deletion action form typo.
  config/sync/eic_admin.action_forms.group_deletion_request.yml
Labels: backend

#1806 EICNET-2634: Wiki tab is not present for GM (and below) in global events
  lib/modules/eic_groups/src/Hooks/EntityOperations.php
Labels: bug, backend

#1798 EICNET-2603: Add missing permissinons in Event GT.
  config/sync/group.role.event-a416e6833.yml
  config/sync/group.role.event-bf4b46c3a.yml
  config/sync/group.role.event-eca6128ca.yml
Labels: backend

#1768 EICNET-2204: Group teaser archived status
  lib/themes/eic_community/includes/preprocess/groups/event.inc
  lib/themes/eic_community/includes/preprocess/groups/group.inc
  lib/themes/eic_community/includes/preprocess/groups/organisation.inc
  lib/themes/eic_community/patterns/compositions/event/event.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
  lib/themes/eic_community/patterns/compositions/organisation/organisation.teaser.html.twig
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
Labels: backend, frontend

#1809 EICNET-1334: Add latest comment to discussion teaser on discussions overview
  lib/modules/eic_flags/eic_flags.services.yml
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
  lib/modules/eic_groups/src/Controller/DiscussionController.php
Labels: backend

#1791 EICNET-2601: I cannot highlight items in global events
  config/sync/group.role.event-admin.yml
  lib/modules/eic_groups/src/Access/HighlightGroupContentAccessCheck.php
  lib/modules/eic_groups/src/EICGroupsHelper.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
Labels: backend

#1793 [EICNET-2639]feat: Use solr search for topic statistics
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/modules/eic_topics/eic_topics.services.yml
  lib/modules/eic_topics/src/TopicsManager.php
Labels: backend

#1789 EICNET-2457: Fix date created and timestamp sorting options for group source types
  config/sync/context.context.drafts.yml
  config/sync/context.context.events.yml
  config/sync/context.context.groups.yml
  lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
  lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
  lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
  lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php
  lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserProfile/MyEventsSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserProfile/MyGroupsSourceType.php
  lib/modules/eic_search/src/Search/Sources/UserProfile/MyOrganisationsSourceType.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: backend

#1794 EICNET-2592: enable modal scrolling
  lib/themes/eic_community/sass/core/_viewport.scss
Labels: frontend

#1816 EICNET-1091: As a GM I can see when content has been shared inside my group
  lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
Labels: bug, backend

#1812 EICNET-1144: Show latest members on the group activity stream page (Hide for anonymous)
  lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
  lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
Labels: backend

#1820 EICNET-XXXX: Packages update.
  composer.lock
Labels: backend

#1800 EICNET-2311: Fix typo.
  config/sync/eic_admin.action_forms.group_archival_request.yml
  config/sync/eic_admin.action_forms.group_membership_edit.yml
  config/sync/eic_admin.action_forms.group_ownership_transfer_request_cancel.yml
  lib/modules/eic_flags/src/Form/RequestCancelForm.php
  lib/themes/eic_community/sass/components/_checkbox.scss
Labels: backend

#1818 Feature/eicnet 2643 login splash page
  lib/modules/eic_user/modules/eic_user_login/src/Controller/MemberAccessController.php
  lib/modules/eic_user/src/Plugin/Block/AccountHeaderBlock.php
Labels: bug, backend

#1783 EICNET-2626: Remove unneeded entity types from search index.
  config/sync/search_api.index.global.yml
Labels: backend

#1797 EICNET-2636: Accepting request to archive as SA/SCM on news articles within global event returns server error
  lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
  lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
  lib/modules/eic_groups/src/GroupsModerationHelper.php
  lib/modules/eic_moderation/src/Constants/EICContentModeration.php
Labels: bug, backend

#1822 EICNET-2651: Share modal: share groups alphabetically.
  lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php
Labels: backend

#1824 EICNET-2649: Display the shared content message in activity stream item.
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
Labels: react

#1821 Feature/eicnet 2650 fix php warnings
  lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
  lib/modules/eic_search/src/Controller/SolrSearchController.php
  lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/themes/eic_community/templates/field/field--node--field-vocab-topics.html.twig
Labels: backend

#1826 Feature/eicnet 2624 organisation type migration web service
  config/sync/core.entity_form_display.taxonomy_term.organisation_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.organisation_types.default.yml
  config/sync/field.field.taxonomy_term.organisation_types.field_smed_id.yml
  config/sync/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_organisation_types.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_organisation_types.yml
  lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
Labels: backend, migration

#1827 EICNET-2659: Adapt SMED webservices response in case of existing entity.
  lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php
Labels: backend

#1829 Feature/eicnet 2661 news stories hompage block fix
  composer.patches.json
  config/sync/views.view.latest_news_and_stories.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend, migration

#1828 EICNET-2660: migrated bookpage challenges generates error with non admin user
  lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
  lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php
Labels: backend

#1830 Feature/eicnet 2662 maintenance
  composer.lock
  config/sync/context.context.drafts.yml
  config/sync/context.context.events.yml
  config/sync/context.context.groups.yml
  config/sync/facets.facet.discussions_regions_countries.yml
  config/sync/facets.facet.discussions_topics.yml
  config/sync/facets.facet.discussions_type.yml
  config/sync/facets.facet.global_members_job_title.yml
  config/sync/facets.facet.global_members_languages.yml
  config/sync/facets.facet.global_members_location_country_code.yml
  config/sync/facets.facet.global_members_topics_of_expertise.yml
  config/sync/facets.facet.groups_regions_countries.yml
  config/sync/facets.facet.groups_topics.yml
  config/sync/facets.facet.members_languages.yml
  config/sync/facets.facet.members_topics_of_expertise.yml
  config/sync/facets.facet.members_topics_of_interest.yml
  config/sync/facets.facet.search_content_type.yml
  config/sync/facets.facet.search_group_content_type.yml
  config/sync/facets.facet.search_group_regions_countries.yml
  config/sync/facets.facet.search_group_topics.yml
  config/sync/facets.facet.search_regions_countries.yml
  config/sync/facets.facet.search_topics.yml
  config/sync/filter.format.full_html.yml
  config/sync/search_api.index.global.yml
  config/sync/search_api_solr.solr_field_type.text_string_und_6_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_und_6_0_0.yml
  config/sync/search_api_solr.solr_field_type.text_und_7_0_0.yml
  config/sync/search_api_solr.solr_request_handler.request_handler_suggest_default_7_0_0.yml
  config/sync/views.view.global_index_group_content.yml
  config/sync/views.view.global_overviews.yml
  config/sync/views.view.group_overviews.yml
  config/sync/views.view.groups_homepage.yml
  config/sync/views.view.organisation_content.yml
  config/sync/views.view.taxonomy_related_content.yml
Labels: backend

#1804 EICNET-901: Show user display name in message notification about content recommendation
  config/sync/core.entity_form_display.message.notify_content_recommendation.default.yml
  config/sync/core.entity_view_display.message.notify_content_recommendation.default.yml
  config/sync/core.entity_view_display.message.notify_content_recommendation.mail_body.yml
  config/sync/core.entity_view_display.message.notify_content_recommendation.mail_subject.yml
  config/sync/field.field.message.notify_content_recommendation.field_receiver_email.yml
  config/sync/field.storage.message.field_receiver_email.yml
  lib/modules/eic_recommend_content/src/EventSubscriber/FlagEventSubscriber.php
  lib/themes/eic_community/includes/preprocess/content/message.inc
Labels: backend

#1831 Feature/eicnet xxxx book migration status fix
  config/sync/migrate_plus.migration.upgrade_d7_book.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_book.yml
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_book.yml
Labels: backend, migration

#1835 [EICNET]fix: Add null check for article introduction
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
Labels: react

#1843 Feature/eicnet xxxx go live quick fixes
  lib/modules/eic_webservices/eic_webservices.module
  lib/modules/eic_webservices/eic_webservices.services.yml
  lib/modules/eic_webservices/src/Plugin/Validation/Constraint/AddressFormatConstraint.php
  lib/modules/eic_webservices/src/Plugin/Validation/Constraint/AddressFormatConstraintValidator.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/GroupResourceBase.php
  lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php
  lib/modules/eic_webservices/src/Utility/WsRestHelper.php
  lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
  lib/themes/eic_community/templates/blocks/block--homepage-latest-news-stories.html.twig
Labels: backend

#1836 EICNET-2643: Make sure to redirect users to the member access page on log in or register CTAs
  lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
  lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
Labels: backend

#1856 EICNET-2686: Remove fake ogranisation from user card.
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
Labels: react

#1855 EICNET-2684: Remove email address from user profile page.
  lib/themes/eic_community/includes/preprocess/users/user.inc
Labels: backend

#1853 Feature/eicnet 2683 matomo
  .env.docker
  composer.json
  composer.lock
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  config/sync/matomo.settings.yml
  config/sync/oe_webtools_analytics.settings.yml
  config/sync/user.role.authenticated.yml
  web/sites/default/default.settings.k8s.php
  web/sites/default/default.settings.local.php
Labels: backend

#1838 [EICNET]fix: Get dynamic statistics from search api
  lib/themes/eic_community/includes/preprocess/blocks/block--facts-figures.inc
Labels: backend

#1861 EICNET-2683: Do not let users opt-out from matomo.
  config/sync/matomo.settings.yml
Labels: backend

#1858 [EICNET-2688]fix: Set field to not required for field_vocab_geo
  config/sync/field.field.profile.member.field_vocab_geo.yml
Labels: backend

#1859 [EICNET-2687]fix: Change label target region & countries
  config/sync/field.field.profile.member.field_vocab_geo.yml
Labels: backend

#1862 EICNET-2690: Change incomplete profile message.
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
Labels: backend

#1860 EICNET-2679: Respect field format.
  lib/themes/eic_community/includes/preprocess/blocks/block--cta-tiles.inc
  lib/themes/eic_community/patterns/compositions/bulletin-block.html.twig
Labels: backend

#1863 EICNET-2695: Migration: missing group features for Events/Organisations
  config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
  lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
Labels: backend, migration
