Repository EIC-EA/EIC-community-D8, pull requests merged in 2023-08, with the labels that each got.

#2143 Feature/eicnet 2973 admin groups filters sorting
  config/sync/system.action.oec_group_visibility_change_action.yml
  config/sync/views.view.admin_groups.yml
  lib/modules/oec_group_flex/config/install/system.action.oec_group_visibility_change_action.yml
  lib/modules/oec_group_flex/oec_group_flex.module
  lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
  lib/modules/oec_group_flex/src/Plugin/Action/VisibilityChange.php
  lib/modules/oec_group_flex/src/Plugin/views/field/GroupVisibility.php
  lib/modules/oec_group_flex/src/Plugin/views/filter/GroupVisibility.php
  lib/modules/oec_group_flex/src/Plugin/views/sort/GroupVisibility.php
Labels: backend

#1982 EICNET-2824: Remove duplicated status message
  lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php
Labels: bug, backend

#2054 EICNET-2736: User account] remove text "explaining" email field since irrelevant
  lib/modules/eic_user/src/Hooks/FormAlter.php
Labels: enhancement, backend

#2068 EICNET-2923: Fix processing of discussions.
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
Labels: backend

#2075 [EICNET-2820]fix: email header logo
  lib/themes/eic_community/mails/mail-dist/digest.html
  lib/themes/eic_community/mails/mail-dist/header_footer.html
  lib/themes/eic_community/mails/mail-dist/layout.html
  lib/themes/eic_community/mails/src/templates/header_footer.mjml
Labels: frontend

#2124 EICNET-2845: Relabel restricted stories to private.
  lib/themes/eic_community/includes/preprocess/layout/page.inc
  lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
Labels: backend

#2076 EICNET-2942: Archived group is appearing to Trusted Users
  lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
  lib/modules/eic_search/src/Service/SolrSearchManager.php
Labels: bug, backend

#2139 Feature/eicnet 2774 gallery download
  config/sync/core.extension.yml
  config/sync/user.role.content_administrator.yml
  config/sync/user.role.sensitive.yml
  config/sync/user.role.site_admin.yml
  config/sync/user.role.trusted_user.yml
  lib/modules/eic_content/modules/eic_content_gallery/eic_content_gallery.info.yml
  lib/modules/eic_content/modules/eic_content_gallery/eic_content_gallery.permissions.yml
  lib/modules/eic_content/modules/eic_content_gallery/eic_content_gallery.routing.yml
  lib/modules/eic_content/modules/eic_content_gallery/src/Constants/GalleryNode.php
  lib/modules/eic_content/modules/eic_content_gallery/src/Controller/ArchiveDownloadController.php
  lib/modules/eic_helper/eic_helper.services.yml
  lib/modules/eic_helper/src/FileArchiver.php
  lib/themes/eic_community/react/components/Block/Gallery/FileInfo.jsx
Labels: backend, frontend

#2137 Feature/eicnet 2716 ckeditor limit
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.story.default.yml
  config/sync/core.extension.yml
Labels: backend

#2130 Feature/eicnet 2835 latest news stories
  config/sync/context.context.homepage.yml
  config/sync/context.context.homepage_anonymous.yml
  config/sync/views.view.content.yml
  config/sync/views.view.latest_news_and_stories.yml
  lib/themes/eic_community/includes/preprocess/views.inc
  lib/themes/eic_community/templates/views/views-view--latest-news-and-stories--homepage.html.twig
Labels: backend, frontend
